#include "ECSModules/Rendering/Systems/AnimationSystem.h"

#include "ECS/World.h"
#include "ECS/Entity.h"
#include "ECS/Query.h"
#include "ECS/ECSTemplates.h"

#include "Components/Animation/AnimatorRef.h"
#include "Components/Animation/SkeletonRef.h"
#include "Components/Animation/HumanoidRetargeterComponent.h"
#include "Components/Rendering/MeshRenderer.h"
#include "Components/Rendering/MorphTargetWeights.h"
#include "ECSModules/Rendering/SkeletonStore.h"
#include "ECSModules/Rendering/ClipStore.h"
#include "Assets/AnimationClip.h"
#include "Assets/AssetManager.h"
#include "Assets/ModelAsset.h"
#include "Assets/RuntimeHumanoidProfile.h"
#include "Engine/Rendering/AnimationSampling.h"
#include "Engine/Rendering/AnimationEventDispatch.h"
#include "Animation/PoseToSkinMatrices.h"
#include "Engine/Rendering/GPUAnimationDataStore.h"
#include "Engine/Rendering/RenderServices.h"
#include "Engine/Rendering/SkinPaletteAtlas.h"
#include "Logger/Logger.h"

#include "Animation/HumanoidImport.h"
#include "Animation/HumanoidRig.h"
#include "Animation/RetargetMap.h"
#include "Animation/SkeletonProfile.h"

#include "Core/Engine.h"

#include <algorithm>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <cmath>
#include <mutex>
#include <system_error>
#include <unordered_set>

namespace GameEngine { namespace Engine::Renderer {

using namespace GameEngine::Components;

namespace {

// Sibling sidecar path conventions used by ModelAsset::PostLoad. Mirrored
// here so the bootstrap path doesn't need a back-pointer to ModelAsset.
std::filesystem::path RigSidecarPathFor(const std::filesystem::path& modelPath)
{
    std::filesystem::path p = modelPath;
    p.replace_extension();
    p += ".humanoidrig.json";
    return p;
}

std::filesystem::path RetargetMapSidecarPath(const std::filesystem::path& tgtModelPath,
                                              const std::filesystem::path& srcModelPath)
{
    const std::string srcStem = srcModelPath.stem().string();
    const std::string tgtStem = tgtModelPath.stem().string();
    std::filesystem::path out = tgtModelPath.parent_path() /
        (srcStem + "_to_" + tgtStem + ".retargetmap.json");
    return out;
}

// Loads (or auto-imports + writes) the humanoid rig sidecar for `modelPath`.
// Returns null on failure.
//
// Identity contract: the returned rig's GUID matches what
// AssetManager.ResolveAssetGuid(sidecar) yields, AND the rig is registered
// in AssetManager.m_LoadedAssets under that GUID. This is required so the
// retarget map can persist a stable rig reference and downstream consumers
// (HumanoidRetargetSystem::ResolveRig) can look the rig up via
// AssetManager.GetAsset(guid). Without registration, those lookups silently
// fail and the entity falls back to bind pose at runtime — see the post-
// bootstrap T-pose bug.
const Animation::HumanoidRig* ResolveOrAutoImportRig(
    AssetManager& assetManager,
    const Animation::SkeletonProfile& profile,
    const std::filesystem::path& modelPath,
    const Animation::SkeletonData& fallbackSkel,
    std::shared_ptr<Animation::HumanoidRig>& outOwner)
{
    if (modelPath.empty()) return nullptr;

    const std::filesystem::path sidecar = RigSidecarPathFor(modelPath);
    std::error_code ec;
    if (std::filesystem::exists(sidecar, ec) && !ec)
    {
        const GUID rigGuid = assetManager.ResolveAssetGuid(sidecar);
        if (!rigGuid.IsNull())
        {
            auto fut = assetManager.LoadAssetAsync(rigGuid, AssetLoadPriority::High);
            auto asset = std::dynamic_pointer_cast<Animation::HumanoidRig>(fut.get());
            if (asset && asset->GetState() == AssetState::Loaded)
            {
                outOwner = std::move(asset);
                // LoadAssetAsync already populated AssetManager's loaded
                // cache, so no extra registration needed.
                return outOwner.get();
            }
        }
    }

    // Auto-import path: only viable when the skeleton in question is the
    // entity's own (target). For source rigs whose model is a different
    // FBX, the sidecar must already exist (PostLoad on the source FBX
    // produces it). We log + bail in that case.
    if (fallbackSkel.BoneCount == 0) return nullptr;

    // Derive the canonical GUID from the sidecar path FIRST so the rig's
    // identity is consistent with AssetManager's registry. Without this the
    // rig was constructed with GUID() (null), the map referenced this null
    // GUID, and ResolveRig later failed.
    const GUID rigGuid = assetManager.ResolveAssetGuid(sidecar);

    auto rig = std::make_shared<Animation::HumanoidRig>(rigGuid, sidecar);
    if (!Animation::AutoImportHumanoidRig(fallbackSkel, profile, *rig))
        return nullptr;

    rig->SetAutoGenerated(true);
    rig->SetProfileRef(profile.GetGUID());

    if (!rig->SaveToPath(sidecar))
        Logger::Log::Warning(
            "[AnimationSystem] failed to write humanoid sidecar '{}'", sidecar.string());
    else
        Logger::Log::Info(
            "[AnimationSystem] HumanoidRig auto-imported via heuristic for '{}'",
            modelPath.string());

    // Publish the in-memory rig into AssetManager so GetAsset(rigGuid)
    // resolves to this same instance. Without this the retarget pipeline
    // can't recover the rig from the map's saved GUID at play time.
    if (!rigGuid.IsNull())
        assetManager.RegisterLoadedAsset(rigGuid, rig);

    outOwner = std::move(rig);
    return outOwner.get();
}

bool IsTransformAnimPath(AnimPath path)
{
    return path == AnimPath::Translation || path == AnimPath::Rotation || path == AnimPath::Scale;
}

float SampleScalarChannel(const AnimChannel& channel, float time)
{
    if (channel.keys.empty())
        return 0.0f;

    size_t hi = 0;
    while (hi < channel.keys.size() && channel.keys[hi].time < time)
        ++hi;
    size_t lo = (hi == 0) ? 0 : (hi - 1);
    if (hi >= channel.keys.size())
        hi = channel.keys.size() - 1;

    const AnimKeyframe& k0 = channel.keys[lo];
    const AnimKeyframe& k1 = channel.keys[hi];
    const float dt = k1.time - k0.time;
    const float alpha = (dt > 0.0f) ? std::clamp((time - k0.time) / dt, 0.0f, 1.0f) : 0.0f;
    const AnimInterp segInterp = k0.hasSegmentInterpOverride ? k0.segmentInterp : channel.interp;
    if (segInterp == AnimInterp::Step || dt <= 0.0f)
        return k0.translation[0];
    return k0.translation[0] + (k1.translation[0] - k0.translation[0]) * alpha;
}

void ApplyMorphAnimationChannels(ECS::World& world,
                                 ECS::EntityHandle entity,
                                 const AnimationClip& clip,
                                 float time,
                                 const Components::MeshRenderer* meshRenderer,
                                 Components::MorphTargetWeights* morph)
{
    if (!meshRenderer || !morph || morph->weightCount == 0)
        return;

    const GUID modelGuid = meshRenderer->modelAssetGuid.ToGuid();
    if (modelGuid.IsNull())
        return;

    // The model comes from the engine's AssetManager; a host that never built
    // one has no model to resolve the morph targets from.
    AssetManager* assetManager = EngineCore::GetInstance().TryGetAssetManager();
    if (!assetManager)
        return;

    auto asset = assetManager->GetAsset(modelGuid);
    if (!asset)
        asset = assetManager->LoadAssetAsync(modelGuid).get();
    const auto* model = asset ? dynamic_cast<ModelAsset*>(asset.get()) : nullptr;
    if (!model || !model->IsLoaded() || meshRenderer->meshId >= model->GetMeshCount())
        return;

    const Mesh& mesh = model->GetMesh(meshRenderer->meshId);
    if (!mesh.HasMorphTargets())
        return;

    bool changed = false;
    const uint32 count = std::min<uint32>(morph->weightCount, static_cast<uint32>(mesh.MorphTargets.size()));
    for (const AnimChannel& channel : clip.GetChannels())
    {
        if (channel.path != AnimPath::MorphWeight)
            continue;
        if (channel.boneIndex != UINT32_MAX && mesh.SourceNodeIndex >= 0 &&
            channel.boneIndex != static_cast<uint32>(mesh.SourceNodeIndex))
            continue;

        for (uint32 i = 0; i < count; ++i)
        {
            const MorphTarget& target = mesh.MorphTargets[i];
            if (channel.targetNameId != 0)
            {
                const StringId targetId = target.Name.empty() ? 0u : HashStringId(target.Name);
                if (targetId != channel.targetNameId)
                    continue;
            }
            else if (!channel.targetName.empty() && channel.targetName != target.Name)
            {
                continue;
            }

            const float value = SampleScalarChannel(channel, time);
            if (std::abs(morph->weights[i] - value) > 1e-6f)
            {
                morph->weights[i] = value;
                changed = true;
            }
            break;
        }
    }

    if (changed)
    {
        ++morph->version;
        world.AddComponentImmediate(entity, *morph);
    }
}

// One line per skeleton that the GPU animation path cannot hold, naming its model.
// Once per process: the scene's animation system and the model thumbnail's each
// route the skeleton, on their own threads.
void WarnSkeletonOverGPULimitsOnce(uint32 skeletonId, const SkeletonData& skeleton)
{
    static std::mutex s_WarnedMutex;
    static std::unordered_set<uint32> s_WarnedSkeletons;
    {
        std::lock_guard<std::mutex> lock(s_WarnedMutex);
        if (!s_WarnedSkeletons.insert(skeletonId).second)
            return;
    }
    const std::string model = skeleton.SourceModelPath.empty()
        ? "skeleton " + std::to_string(skeletonId)
        : skeleton.SourceModelPath.filename().string();
    Logger::Log::Warning(
        "Skeleton of '{}' needs {} GPU bones (joints and their ancestors) and {} levels; the GPU animation "
        "path holds {} and {}, so it animates on the CPU path. Split the rig under those counts, or accept "
        "CPU sampling.",
        model, skeleton.JointClosure.size(), skeleton.JointClosureLevelCount(),
        GPUAnimationDataStore::kMaxBones, GPUAnimationDataStore::kMaxHierarchyLevels);
}

} // anonymous namespace

void AnimationSystem::Update(ECS::World& world, float32 deltaTime) {
    auto& clipStore = ClipStore::Instance();
    auto& skStore = SkeletonStore::Instance();

    // Phase 1 (sequential): advance animation time and collect per-runtime work items.
    // MeshRenderer is bound const: this query only reads modelAssetGuid/meshId
    // for morph channel routing. A mutable binding write-grants the column at
    // every visit (stamp-at-visit), which would fire Changed<MeshRenderer>
    // consumers every frame a clip plays anywhere in the scene.
    m_WorkItems.clear();
    auto q = world.Query<ECS::Write<AnimatorRef>,
                         ECS::Read<SkeletonRef>,
                         ECS::Optional<Components::MeshRenderer>,
                         ECS::Optional<Components::MorphTargetWeights>>();
    q.Each([&](ECS::EntityHandle entity,
               AnimatorRef& anim,
               const SkeletonRef& sref,
               const Components::MeshRenderer* meshRenderer,
               Components::MorphTargetWeights* morph) {
        if (anim.ClipIndex == 0 || sref.skeletonId == 0 || sref.runtimeId == 0) return;

        // Skip entities already routed through HumanoidRetargetSystem so we
        // don't double-sample the clip onto the (now-unused) AnimatorRef
        // path. The HumanoidRetargeter component takes precedence; the
        // animation wave runs Animation -> HumanoidRetarget sequentially.
        if (world.HasComponent<HumanoidRetargeterComponent>(entity)) return;

        auto clip = clipStore.Get(anim.ClipIndex);
        if (!clip) return;

        auto* skel = skStore.Get(sref.skeletonId);
        if (!skel || skel->BoneCount == 0) return;

        TickAnimatorRef(anim, clipStore, deltaTime, ClaimClipPlaybackEvents(world, entity));

        // Morph weights hard-cut to the incoming clip. Dual-sample lerp is
        // skeletal locals only.
        ApplyMorphAnimationChannels(world, entity, *clip, anim.Time, meshRenderer, morph);

        WorkItem item{};
        item.SkeletonId = sref.skeletonId;
        item.RuntimeId = sref.runtimeId;
        item.ClipIndex = anim.ClipIndex;
        item.Time = anim.Time;
        item.CachedSkeleton = skel;
        item.Entity = entity;
        item.PrevClipIndex = anim.IsBlending() ? anim.PrevClipIndex : 0u;
        item.PrevTime = anim.PrevTime;
        item.BlendAlpha = anim.BlendAlpha();
        m_WorkItems.push_back(item);
    });

    // Deduplicate by runtimeId — multi-submesh models sharing a runtimeId
    // collapse to one work item (last entity wins).
    {
        m_UniqueByRuntimeId.clear();
        for (size_t i = 0; i < m_WorkItems.size(); ++i)
            m_UniqueByRuntimeId[m_WorkItems[i].RuntimeId] = i;

        m_CompactedWorkItems.clear();
        m_CompactedWorkItems.reserve(m_UniqueByRuntimeId.size());
        for (auto& [id, idx] : m_UniqueByRuntimeId)
            m_CompactedWorkItems.push_back(m_WorkItems[idx]);
        m_WorkItems.swap(m_CompactedWorkItems);
    }

    // Idle-recompute-elision: compare this frame's palette input set against
    // last frame's byte-exactly (m_LastPaletteInputs contract in the header).
    // Runs BEFORE the empty-return so a runtime dropping out of the set (clip
    // cleared, entity destroyed) is observed as a change. Keyed on work-set
    // deltas, not IsPaused: a paused animator keeps its item but with frozen
    // time, which compares equal and stays elidable.
    {
        const auto timeBits = [](float32 t)
        {
            uint32 bits = 0;
            std::memcpy(&bits, &t, sizeof(bits));
            return bits;
        };
        bool paletteChanged = m_WorkItems.size() != m_LastPaletteInputs.size();
        if (!paletteChanged)
        {
            for (const WorkItem& item : m_WorkItems)
            {
                const auto it = m_LastPaletteInputs.find(item.RuntimeId);
                if (it == m_LastPaletteInputs.end() ||
                    it->second.SkeletonId != item.SkeletonId ||
                    it->second.ClipIndex != item.ClipIndex ||
                    it->second.TimeBits != timeBits(item.Time) ||
                    it->second.PrevClipIndex != item.PrevClipIndex ||
                    it->second.PrevTimeBits != timeBits(item.PrevTime) ||
                    it->second.BlendAlphaBits != timeBits(item.BlendAlpha))
                {
                    paletteChanged = true;
                    break;
                }
            }
        }
        if (paletteChanged)
        {
            m_LastPaletteInputs.clear();
            for (const WorkItem& item : m_WorkItems)
                m_LastPaletteInputs[item.RuntimeId] = PaletteInputs{
                    item.SkeletonId,
                    item.ClipIndex,
                    timeBits(item.Time),
                    item.PrevClipIndex,
                    timeBits(item.PrevTime),
                    timeBits(item.BlendAlpha)};
            if (m_RenderServices)
                m_RenderServices->NotifySkinPaletteContentChanged(world.GetWorldId());
        }
    }

    if (m_WorkItems.empty())
        return;

    // Phase 1.5: cross-rig auto-bootstrap. Detects work items where the
    // clip and skeleton don't share bone naming (the GPU path would write
    // the wrong bones; the CPU path would silently drop channels and
    // produce a mostly-T-pose). For those pairs we look up (or auto-import)
    // source + target HumanoidRigs from sidecar JSONs next to the source
    // FBXs, synthesize a default RetargetMap, and AddComponent<
    // HumanoidRetargeterComponent> on the entity. HumanoidRetargetSystem
    // (next system in the wave) then drives the entity properly.
    //
    // The work item is removed for this frame so AnimationSystem doesn't
    // also write a same-rig pose into the same skin matrices on the way
    // out. From frame N+1 forward the early-out at the top of the per-
    // entity lambda skips it because HasComponent<HumanoidRetargeter>
    // returns true.
    //
    // Every step of the phase — the content watchers, the source-set version,
    // the rig and profile lookups — goes through the engine's AssetManager, so
    // a host that never built one (a bare harness driving the system without
    // EngineCore::Initialize) has nothing to bootstrap from and skips the
    // phase instead of dereferencing a null manager. Phase 2 below still runs:
    // same-rig playback needs no assets.
    // Phase 15.3: source the AssetManager from EngineCore, not the
    // thread-local. AnimationSystem runs on the ECS schedule wave
    // which has no ScopedThreadAssetManager active, so
    // GetThreadCurrent() returns null here and the bootstrap path
    // silently bails at `if (!assetManager) continue;` below —
    // marking (skel,clip) attempted on the way out, so subsequent
    // frames also bail with no log line. EngineCore's AssetManager
    // is canonical for the whole engine. We also push it as the
    // thread-current for this scope so any reentrant Asset::Load
    // (e.g. ResolveOrAutoImportRig synchronous get) can resolve
    // imports inline.
    if (AssetManager* assetManager = EngineCore::GetInstance().TryGetAssetManager())
    {
        AssetManager::ScopedThreadAssetManager threadCtx(assetManager);
        if (!m_BootstrapWatching)
        {
            constexpr AssetType types[] = {AssetType::SkeletonProfile, AssetType::HumanoidRig,
                                           AssetType::RetargetMap, AssetType::Model, AssetType::Animation};
            for (size_t n = 0; n < m_BootstrapWatchers.size(); ++n)
                m_BootstrapWatchers[n] = AssetReloadInvalidator(
                    assetManager->GetEventDispatcher(), types[n],
                    [dirty = m_BootstrapContentDirty](const GUID&)
                    {
                        // Watcher callbacks own only a signal, never the system.
                        dirty->store(true, std::memory_order_release);
                    },
                    AssetReloadInvalidator::EventSet::ContentEvents);
            m_BootstrapWatching = true;
        }
        const auto sourceVersion = assetManager->GetSourceSetVersion();
        const auto reset = world.GetLifecycleResetGeneration();
        if (m_BootstrapContentDirty->exchange(false, std::memory_order_acq_rel) ||
            m_BootstrapSourceVersion != sourceVersion || m_BootstrapWorldId != world.GetWorldId() ||
            m_BootstrapWorldReset != reset)
        {
            m_BootstrapAttempted.clear();
            m_BootstrapSourceVersion = sourceVersion;
            m_BootstrapWorldId = world.GetWorldId();
            m_BootstrapWorldReset = reset;
        }

        struct Bootstrapped
        {
            ECS::EntityHandle Entity;
            ::GameEngine::Components::HumanoidRetargeterComponent Component;
        };
        std::vector<Bootstrapped> toAdd;
        std::vector<size_t> dropIndices; // indices into m_WorkItems to skip this frame
        std::unique_ptr<Animation::SkeletonProfile> profile;
        bool profileAttempted = false;

        for (size_t i = 0; i < m_WorkItems.size(); ++i)
        {
            const auto& item = m_WorkItems[i];
            const uint64_t key = (static_cast<uint64_t>(item.SkeletonId) << 32)
                                  | static_cast<uint64_t>(item.ClipIndex);
            if (m_BootstrapAttempted.count(key)) continue;

            // Phase 15.1: cross-rig detection. IsClipSkeletonGPUSafe says only
            // whether the GPU kernel can drive the pair: the skeleton fits the
            // kernel's limits and every channel's stored bone index names the
            // same bone in this skeleton. A clip authored on another rig whose
            // bone names sit at the same indices passes it and still needs
            // retargeting, so use a structural test instead.
            //
            // Fast path: compare the clip's source model path to the
            // skeleton's source model path. Different source models =
            // different rigs = bootstrap.
            auto clipForBootstrap = clipStore.Get(item.ClipIndex);
            if (!clipForBootstrap) continue;
            const std::filesystem::path tgtModelPath = item.CachedSkeleton->SourceModelPath;
            // Phase 15.4: prefer the explicit Phase-15.2 SourcePath, fall
            // back to the clip Asset's own path for clips registered with
            // ClipStore via paths other than ModelAsset::LoadFBX (cached
            // assets, scripting paths, hot-reload). For FBX-embedded clips
            // both should resolve to the same .fbx model path; the source
            // info is just the more authoritative form when present.
            std::filesystem::path srcModelPath = clipForBootstrap->GetSourcePath();
            if (srcModelPath.empty())
                srcModelPath = clipForBootstrap->GetPath();
            const bool sameSourceModel =
                !tgtModelPath.empty() && !srcModelPath.empty() && tgtModelPath == srcModelPath;
            if (sameSourceModel)
            {
                m_BootstrapAttempted.insert(key);
                continue;
            }
            // Phase 15.4: structural sniff over EVERY clip channel, not
            // just a body-bone subset. The Synty BusinessMale +
            // A_Walk_F_Masc case has identical body-bone hierarchy (same
            // family, same indices for Hips/Spine/UpperArm/UpperLeg) so a
            // body-only sniff is false-negative; the divergence is in
            // finger / face bones whose indices differ between the two
            // FBX exports. The pre-15.4 sniff also gated on "both source
            // paths empty" — Phase 15.2 populated those paths for clips
            // imported via ModelAsset::LoadFBX, but clips reaching this
            // path through other code (cached AnimationClip assets,
            // scripting-built clips, or a different staged copy of the
            // same FBX) can still have empty source paths.
            //
            // Signal: any channel whose stored source-skeleton boneIndex
            // doesn't match ResolveBoneIndex on the target = cross-rig.
            // Same-rig pairs always match because the clip's boneIndex
            // and the target's ResolveBoneIndex(name) are looking up the
            // same skeleton.
            {
                // Phase 22: classify the mismatch.
                //   - structuralMismatchSeen: at least one channel's stored
                //     boneIndex differs from the target's name-resolved index
                //     (rigs differ in bone ordering).
                //   - hasUnresolvableChannel: at least one channel's name
                //     does NOT exist on target at all (truly different rig
                //     families with non-overlapping bone sets — Mixamo vs
                //     MetaHuman, etc.).
                //
                // Same-family-different-ordering (Synty BusinessMale +
                // A_Walk_F_Masc) has structuralMismatchSeen=true but
                // hasUnresolvableChannel=false. AnimationSystem's CPU sample
                // path resolves channels by name and writes correct local
                // poses to the matching target bones — that's the right
                // path for these rigs. The retarget pipeline is for cases
                // where bone identities, scales, and bind orientations
                // differ (true cross-rig).
                // Self-consistency probe: a channel's stored boneIndex is
                // structurally consistent when it points to a bone whose
                // BoneNameIds entry matches the channel's targetNameId. This
                // mirrors IsClipSkeletonGPUSafe's per-channel test exactly so
                // the two paths can't disagree on routing — without this, an
                // FBX with duplicate leaf names (e.g. "_End") would pass the
                // GPU-safe gate but ALSO trip ResolveBoneIndex's first-name-hit
                // semantics here, causing structural-mismatch=true and
                // bootstrap-then-retarget. The sameSourceModel fast-path above
                // shields most cases, but clips lacking SourcePath (cached
                // .anim assets, scripting-built clips) reach this sniff.
                const auto& boneNameIds = item.CachedSkeleton->BoneNameIds;
                bool structuralMismatchSeen = false;
                uint32 channelsResolved = 0;
                uint32 channelsUnresolved = 0;
                for (const auto& channel : clipForBootstrap->GetChannels())
                {
                    if (!IsTransformAnimPath(channel.path)) continue;
                    if (channel.targetNameId == 0) continue;
                    if (channel.boneIndex == UINT32_MAX) continue;
                    const bool inRange = channel.boneIndex < item.CachedSkeleton->BoneCount
                                      && channel.boneIndex < boneNameIds.size();
                    if (inRange && boneNameIds[channel.boneIndex] == channel.targetNameId)
                    {
                        // Self-consistent — same-rig (possibly with duplicate
                        // names). Treat as resolved without consulting
                        // ResolveBoneIndex's first-hit collapse.
                        ++channelsResolved;
                        continue;
                    }
                    const uint32 resolved = item.CachedSkeleton->ResolveBoneIndex(
                        channel.targetNameId, UINT32_MAX);
                    if (resolved == UINT32_MAX) {
                        ++channelsUnresolved;
                        continue;
                    }
                    ++channelsResolved;
                    if (resolved != channel.boneIndex) {
                        structuralMismatchSeen = true;
                    }
                }
                if (!structuralMismatchSeen)
                {
                    m_BootstrapAttempted.insert(key);
                    continue;
                }
                // Phase 23 reverted: routing same-family pairs through CPU
                // sample produced a distorted pose because the clip's per-bone
                // local rotations are in the SOURCE skeleton's bind frame,
                // not the target's. Direct application without rebasing
                // bends bones at wrong angles (e.g., Synty BusinessMale ends
                // up bent 90° forward at the hips).
                //
                // The proper fix is `tgt_bind * inverse(src_bind) * key`
                // per matched bone, which requires the cross-rig retargeter
                // (HumanoidRetargetSystem). Even that path has math that
                // doesn't fully account for Synty's Character_BusinessMale_01
                // wrapper-bone hierarchy differences. Phase 24+ will tackle
                // a world-space-based retarget-pose bake that correctly
                // composes through wrapper bones.
                //
                // For now: fall through to the HumanoidRetargetSystem
                // bootstrap. The pose will be distorted but at least
                // recognizable (not inverted faces / lying-down).
            }

            // Successful bootstrap is entity-owned: snapshot restore can remove
            // the component and must allow the same pair to bootstrap again.
            // Failures are memoized until content, mounts or the world reset.
            Logger::Log::Info(
                "[AnimationSystem] auto-bootstrap: cross-rig detected "
                "(skeletonId={}, clipIndex={}, src='{}', tgt='{}')",
                item.SkeletonId, item.ClipIndex,
                srcModelPath.string(), tgtModelPath.string());

            if (!assetManager) {
                Logger::Log::Warning(
                    "[AnimationSystem] auto-bootstrap: AssetManager unavailable; skipping");
                continue;
            }
            // Reuse clipForBootstrap from the structural test above; tgt/srcModelPath
            // already resolved via item.CachedSkeleton->SourceModelPath / clipForBootstrap->GetSourcePath().
            [[maybe_unused]] const auto& clip = clipForBootstrap;
            if (tgtModelPath.empty() || srcModelPath.empty()) {
                Logger::Log::Warning(
                    "[AnimationSystem] auto-bootstrap: empty model path "
                    "(tgt='{}', src='{}'); skipping",
                    tgtModelPath.string(), srcModelPath.string());
                m_BootstrapAttempted.insert(key);
                continue;
            }

            if (!profileAttempted)
            {
                profile = LoadRuntimeHumanoidProfile(*assetManager);
                profileAttempted = true;
            }
            if (!profile)
            {
                Logger::Log::Warning("[AnimationSystem] auto-bootstrap: profile unavailable ('{}')",
                                     kRuntimeHumanoidProfilePath);
                m_BootstrapAttempted.insert(key);
                continue;
            }

            // Resolve target rig (we have its skeleton, so we can auto-
            // import on demand if the sidecar is missing).
            std::shared_ptr<Animation::HumanoidRig> tgtOwner;
            const Animation::HumanoidRig* tgtRig = ResolveOrAutoImportRig(
                *assetManager, *profile, tgtModelPath, *item.CachedSkeleton, tgtOwner);
            if (!tgtRig)
            {
                Logger::Log::Warning(
                    "[AnimationSystem] auto-bootstrap: target rig unresolved for '{}'",
                    tgtModelPath.string());
                m_BootstrapAttempted.insert(key);
                continue;
            }

            // Resolve source rig. We don't have the source skeleton in
            // memory here; rely on the sidecar that ModelAsset::PostLoad
            // produced when the source FBX was imported.
            std::shared_ptr<Animation::HumanoidRig> srcOwner;
            const Animation::HumanoidRig* srcRig = nullptr;
            const std::filesystem::path srcSidecar = RigSidecarPathFor(srcModelPath);
            std::error_code ec;
            const bool srcSidecarExists = std::filesystem::exists(srcSidecar, ec) && !ec;
            GUID srcRigGuid;
            if (srcSidecarExists)
            {
                srcRigGuid = assetManager->ResolveAssetGuid(srcSidecar);
                if (!srcRigGuid.IsNull())
                {
                    auto fut = assetManager->LoadAssetAsync(srcRigGuid, AssetLoadPriority::High);
                    srcOwner = std::dynamic_pointer_cast<Animation::HumanoidRig>(fut.get());
                    if (srcOwner && srcOwner->GetState() == AssetState::Loaded)
                        srcRig = srcOwner.get();
                }
                // Direct-disk fallback (same rationale as profile above):
                // stale registry / pre-Phase-16 cache may have rejected the
                // sidecar at scan time. Load directly from the existing file.
                //
                // Identity contract: derive the GUID from the sidecar path
                // and register the loaded rig with AssetManager so future
                // GetAsset(srcRig->GetGUID()) calls (e.g. from
                // HumanoidRetargetSystem::ResolveRig) succeed. Using
                // GUID::Generate() here would create a rig under a random
                // GUID that AssetManager has no record of, leading to silent
                // resolution failures and bind-pose fallback at runtime.
                if (!srcRig)
                {
                    GUID fallbackGuid = srcRigGuid;
                    if (fallbackGuid.IsNull())
                        fallbackGuid = assetManager->ResolveAssetGuid(srcSidecar);
                    if (fallbackGuid.IsNull())
                        fallbackGuid = GUID::Generate(); // last resort

                    auto fallback = std::make_shared<Animation::HumanoidRig>(
                        fallbackGuid, srcSidecar);
                    if (fallback->Load() && fallback->GetState() == AssetState::Loaded)
                    {
                        srcOwner = fallback;
                        srcRig = srcOwner.get();
                        if (!fallbackGuid.IsNull())
                            assetManager->RegisterLoadedAsset(fallbackGuid, srcOwner);
                        Logger::Log::Info(
                            "[AnimationSystem] auto-bootstrap: source rig loaded via "
                            "direct-disk fallback ('{}', guid={})",
                            srcSidecar.string(), fallbackGuid.ToString());
                    }
                }
            }
            if (!srcRig)
            {
                Logger::Log::Warning(
                    "[AnimationSystem] auto-bootstrap: source rig unresolved "
                    "(sidecar='{}', exists={}, resolvedGuid={}, ownerLoaded={})",
                    srcSidecar.string(),
                    srcSidecarExists ? "yes" : "no",
                    srcRigGuid.IsNull() ? "null" : srcRigGuid.ToString(),
                    srcOwner ? (srcOwner->GetState() == AssetState::Loaded ? "yes" : "no") : "null");
                m_BootstrapAttempted.insert(key);
                continue;
            }

            // Auto-create the RetargetMap sidecar (or load it if the user
            // already has one).
            const std::filesystem::path mapSidecar =
                RetargetMapSidecarPath(tgtModelPath, srcModelPath);
            GUID mapGuid;
            if (std::filesystem::exists(mapSidecar, ec) && !ec)
                mapGuid = assetManager->ResolveAssetGuid(mapSidecar);

            // Validate-and-rewrite: a stale retargetmap on disk may embed
            // sourceRigRef/targetRigRef GUIDs that no longer match the live
            // rig assets (project AssetStore was rebuilt, paths normalized
            // differently, or the file was generated against a previous
            // store). When refs are stale, rewrite the file in-place with
            // the current rig GUIDs while preserving the user's bone map /
            // op-stack edits.
            if (!mapGuid.IsNull())
            {
                auto fut = assetManager->LoadAssetAsync(mapGuid, AssetLoadPriority::High);
                auto loaded = std::dynamic_pointer_cast<Animation::RetargetMap>(fut.get());
                if (loaded && loaded->GetState() == AssetState::Loaded)
                {
                    const bool sourceStale = (loaded->SourceRigRef() != srcRig->GetGUID());
                    const bool targetStale = (loaded->TargetRigRef() != tgtRig->GetGUID());
                    if (sourceStale || targetStale)
                    {
                        Logger::Log::Info(
                            "[AnimationSystem] auto-bootstrap: rewriting stale retargetmap '{}' "
                            "(srcRef={} -> {}, tgtRef={} -> {})",
                            mapSidecar.string(),
                            loaded->SourceRigRef().ToString(), srcRig->GetGUID().ToString(),
                            loaded->TargetRigRef().ToString(), tgtRig->GetGUID().ToString());
                        loaded->SetSourceRigRef(srcRig->GetGUID());
                        loaded->SetTargetRigRef(tgtRig->GetGUID());
                        if (!loaded->SaveToPath(mapSidecar))
                        {
                            Logger::Log::Warning(
                                "[AnimationSystem] auto-bootstrap: failed to rewrite '{}'",
                                mapSidecar.string());
                        }
                    }
                }
            }

            if (mapGuid.IsNull())
            {
                auto map = std::make_shared<Animation::RetargetMap>(GUID(), mapSidecar);
                Animation::AutoCreateRetargetMap(*srcRig, *tgtRig, *map);
                map->SetSourceRigRef(srcRig->GetGUID());
                map->SetTargetRigRef(tgtRig->GetGUID());
                if (!map->SaveToPath(mapSidecar))
                {
                    Logger::Log::Error(
                        "[AnimationSystem] auto-bootstrap: failed to write '{}'",
                        mapSidecar.string());
                    m_BootstrapAttempted.insert(key);
                    continue;
                }
                mapGuid = assetManager->ResolveAssetGuid(mapSidecar);
                Logger::Log::Info(
                    "[AnimationSystem] auto-bootstrap: created RetargetMap '{}'",
                    mapSidecar.string());
            }
            if (mapGuid.IsNull())
            {
                m_BootstrapAttempted.insert(key);
                continue;
            }

            // Seed the component's source skeleton and make the source
            // ModelAsset resident, so the retarget system's own non-blocking
            // resolve hits on the entity's first update instead of holding the
            // character at bind pose for a frame. Its SkeletonStore
            // registration carries the bind matrices the clip is sampled
            // against; a clip that names no source model keeps this value as
            // its only source.
            uint32 sourceSkeletonId = 0;
            {
                const GUID srcModelGuid = assetManager->ResolveAssetGuid(srcModelPath);
                if (!srcModelGuid.IsNull())
                {
                    auto srcModelFut = assetManager->LoadAssetAsync(
                        srcModelGuid, AssetLoadPriority::High);
                    auto srcModelAsset = srcModelFut.get();
                    if (auto* m = dynamic_cast<ModelAsset*>(srcModelAsset.get());
                        m && m->IsLoaded())
                    {
                        sourceSkeletonId = m->GetSkeletonId();
                    }
                }
                if (sourceSkeletonId == 0)
                {
                    Logger::Log::Warning(
                        "[AnimationSystem] auto-bootstrap: no source skeleton in "
                        "animation model '{}' — the character holds its pose until "
                        "that model imports with one",
                        srcModelPath.string());
                }
            }

            // Stage the AddComponent<HumanoidRetargeterComponent>. Performed
            // after the work-item dispatch loop so we don't structurally
            // mutate the world while iterating.
            ::GameEngine::Components::HumanoidRetargeterComponent rc;
            rc.Map.Set(mapGuid);
            rc.SourceClipIndex = item.ClipIndex;
            rc.SourceSkeletonId = sourceSkeletonId;
            rc.ClipTimeSeconds = item.Time;
            rc.Speed = 1.0f;
            rc.Loop = true;
            toAdd.push_back({item.Entity, rc});
            dropIndices.push_back(i);

            Logger::Log::Info(
                "[AnimationSystem] auto-bootstrap: cross-rig clip routed via HumanoidRetargetSystem "
                "(src='{}', tgt='{}', map='{}')",
                srcModelPath.string(), tgtModelPath.string(), mapSidecar.string());
        }

        // Drop the bootstrapped items so we don't double-write the pose
        // this frame. dropIndices is in ascending order by construction.
        for (auto it = dropIndices.rbegin(); it != dropIndices.rend(); ++it)
            m_WorkItems.erase(m_WorkItems.begin() + *it);

        // Now structurally mutate.
        for (const auto& b : toAdd)
            world.AddComponent<::GameEngine::Components::HumanoidRetargeterComponent>(
                b.Entity, b.Component);
    }

    if (m_WorkItems.empty())
        return;

    // Phase 2: GPU compute when safe; CPU sample otherwise.
    //
    // The GPU clip upload bakes `channel.boneIndex` (the clip's source-
    // skeleton index) directly into the GPU clip data, so the GPU compute
    // shader can only correctly drive a skeleton whose bone indexing
    // matches the clip's source. The CPU sample path (`SampleAnimationPose`)
    // resolves channels by hashed bone name (`SkeletonData::ResolveBoneIndex`)
    // and drops mismatches, so it works across rigs.
    //
    // Per-work-item routing: pick CPU when the skeleton's joint closure is
    // over the kernel's bone or level limit, or when the clip-skeleton pair
    // would need name resolution (any channel where `ResolveBoneIndex` would
    // remap, or where the name doesn't exist in the skeleton). Otherwise
    // GPU. The decision is cached per (skeletonId, clipIndex) so the
    // O(channels) check is paid once per pair. A skeleton the GPU store
    // refuses to upload samples on the CPU as well.
    //
    // GE_FORCE_CPU_ANIM=1 still forces the CPU path globally for debugging.
    const char* forceCpuEnv = std::getenv("GE_FORCE_CPU_ANIM");
    const bool forceCpu = forceCpuEnv && forceCpuEnv[0] && forceCpuEnv[0] != '0';
    const bool gpuReady = !forceCpu && m_RenderServices->IsComputeSkinningReady();
    auto& gpuStore = m_RenderServices->GetGPUAnimationDataStore();
    auto& atlas = m_RenderServices->GetSkinPaletteAtlas();

    static bool s_LoggedFirst = false;

    for (const auto& item : m_WorkItems)
    {
        auto clipPtr = clipStore.Get(item.ClipIndex);
        if (!clipPtr) continue;

        // Cross-rig humanoid retargeting lives in HumanoidRetargetSystem
        // (Phase 6). Entities with a HumanoidRetargeterComponent are
        // routed there; this loop handles same-rig sampling only.

        const bool blending = item.PrevClipIndex != 0 && item.BlendAlpha < 1.0f;
        const bool itemGpuSafe = !blending && gpuReady
            && IsClipSkeletonGPUSafe(item.SkeletonId, item.ClipIndex,
                                     *item.CachedSkeleton, clipStore);

        if (!s_LoggedFirst) {
            Logger::Log::Info("[AnimationSystem] First animated frame: gpuReady={}, gpuSafe={}, workItems={}",
                              gpuReady ? 1 : 0, itemGpuSafe ? 1 : 0, m_WorkItems.size());
            s_LoggedFirst = true;
        }

        if (blending)
        {
            auto prev = clipStore.Get(item.PrevClipIndex);
            auto* runtime = skStore.GetRuntime(item.RuntimeId);
            if (!prev || !runtime || !item.CachedSkeleton) continue;
            SampleAnimationPose(*item.CachedSkeleton, prev.get(), item.PrevTime,
                                nullptr, nullptr, m_BlendFrom);
            SampleAnimationPose(*item.CachedSkeleton, clipPtr.get(), item.Time,
                                nullptr, nullptr, m_Workspace);
            BlendLocalPoses(m_Workspace, m_BlendFrom, item.BlendAlpha);
            ::GameEngine::Animation::BuildPoseToSkinMatrices(
                *item.CachedSkeleton, nullptr, &runtime->CompactSkinMatrices, m_Workspace);
            continue;
        }

        const uint32 skelGPUIdx = itemGpuSafe ? gpuStore.EnsureSkeletonUploaded(item.SkeletonId)
                                              : GPUAnimationDataStore::kNotUploaded;
        // A route cached before a reload grew the skeleton past the limits:
        // the store refused it, so say why it now samples on the CPU.
        if (itemGpuSafe && skelGPUIdx == GPUAnimationDataStore::kNotUploaded
            && !GPUAnimationDataStore::FitsKernelLimits(*item.CachedSkeleton))
            WarnSkeletonOverGPULimitsOnce(item.SkeletonId, *item.CachedSkeleton);
        if (skelGPUIdx != GPUAnimationDataStore::kNotUploaded)
        {
            const uint32 jc = (item.CachedSkeleton->SkinJointCount > 0)
                ? item.CachedSkeleton->SkinJointCount : item.CachedSkeleton->BoneCount;
            if (jc == 0) continue;

            uint32 clipGPUIdx = gpuStore.EnsureClipUploaded(item.ClipIndex);

            uint32 atlasOffset = atlas.Reserve(jc);
            auto* runtime = skStore.GetRuntime(item.RuntimeId);
            if (atlasOffset == UINT32_MAX)
            {
                // Refused: retire the offset to the identity block so this frame
                // renders bind pose. Keeping the previous value would skin the
                // entity with whichever runtime now owns that slot.
                if (runtime)
                    runtime->SetAtlasPaletteOffset(
                        SkinPaletteAtlas::kIdentityPaletteOffsetBones);
                continue;
            }

            if (runtime) runtime->SetAtlasPaletteOffset(atlasOffset);

            GPUAnimInstance gpuInst{};
            gpuInst.skeletonGPUIndex = skelGPUIdx;
            gpuInst.clipGPUIndex = clipGPUIdx;
            gpuInst.time = item.Time;
            gpuInst.atlasOutputOffset = atlasOffset;
            // Phase 6-iii: stash runtime id so the skinning compute can read
            // the per-runtime visibility flag and early-out when off-screen.
            gpuInst.runtimeId = item.RuntimeId;
            gpuStore.AddInstance(gpuInst);
            gpuStore.MarkGPUHandled(item.RuntimeId);
        }
        else
        {
            // CPU sample: name-resolution-aware, and no bone or level limit.
            // SkinningUploadSystem will upload the resulting
            // CompactSkinMatrices to the atlas SSBO.
            auto clip = clipStore.Get(item.ClipIndex);
            auto* runtime = skStore.GetRuntime(item.RuntimeId);
            if (!clip || !runtime || !item.CachedSkeleton) continue;
            SampleAnimationPose(*item.CachedSkeleton, clip.get(), item.Time,
                                nullptr, &runtime->CompactSkinMatrices, m_Workspace);
        }
    }
}

bool AnimationSystem::IsClipSkeletonGPUSafe(uint32 skeletonId, uint32 clipIndex,
                                             const SkeletonData& skeleton,
                                             ClipStore& clipStore) {
    // Cache per (skeletonId, clipIndex); m_GPUSafeCache states what a model
    // reload leaves stale.
    const uint64_t key = (static_cast<uint64_t>(skeletonId) << 32) | static_cast<uint64_t>(clipIndex);
    if (auto it = m_GPUSafeCache.find(key); it != m_GPUSafeCache.end())
        return it->second;

    if (!GPUAnimationDataStore::FitsKernelLimits(skeleton))
    {
        WarnSkeletonOverGPULimitsOnce(skeletonId, skeleton);
        m_GPUSafeCache.emplace(key, false);
        return false;
    }

    bool safe = true;
    if (auto clip = clipStore.Get(clipIndex); clip && !skeleton.BoneNameIds.empty())
    {
        for (const auto& channel : clip->GetChannels())
        {
            if (!IsTransformAnimPath(channel.path)) continue;
            if (channel.targetNameId == 0) continue; // legacy clip; trust stored boneIndex

            // Self-consistency: the clip's stored boneIndex must point to a
            // bone whose name hashes to the channel's targetNameId. For
            // same-FBX clips this holds by construction (both clip and
            // skeleton are built by linear walks of scene->nodes), so
            // duplicate bone names like leaf "_End" markers don't trip the
            // gate — they would if we used ResolveBoneIndex, which returns
            // only the first lookup match per name.
            //
            // For cross-rig (clip authored against a different skeleton),
            // names don't align positionally → fails → CPU sample handles
            // it via name resolution + drop policy.
            const bool inRange = channel.boneIndex < skeleton.BoneCount
                              && channel.boneIndex < skeleton.BoneNameIds.size();
            const StringId boneName = inRange ? skeleton.BoneNameIds[channel.boneIndex] : 0u;
            if (!inRange || boneName != channel.targetNameId)
            {
                safe = false;
                static const bool s_Diag = []() {
                    const char* v = std::getenv("GE_ANIM_GPUSAFE_DIAG");
                    return v && v[0] && v[0] != '0';
                }();
                if (s_Diag)
                {
                    Logger::Log::Info(
                        "[AnimGPUSafeDiag] skeletonId={} clipIndex={} channelBone={} "
                        "stored={} storedName={} reason={} (boneCount={}, namedBones={})",
                        skeletonId, clipIndex, channel.targetNameId,
                        channel.boneIndex, boneName,
                        !inRange ? "stored-out-of-range" : "name-mismatch",
                        skeleton.BoneCount, skeleton.BoneNameIds.size());
                }
                break;
            }
        }
    }
    m_GPUSafeCache.emplace(key, safe);
    return safe;
}


// ===== Test Hooks Implementations =====
namespace TestHooks {

bool SetClipCacheForTest(const GUID& guid, SharedPtr<AnimationClip> clip)
{
    auto& store = ClipStore::Instance();
    return store.RegisterRuntimeClip(guid, std::move(clip)) != 0;
}

void ClearClipCacheForTest()
{
    ClipStore::Instance().ClearForTest();
}

bool IsClipSkeletonGPUSafeForTest(uint32 skeletonId, uint32 clipIndex)
{
    auto& clipStore = ClipStore::Instance();
    auto& skStore = SkeletonStore::Instance();
    auto* skel = skStore.Get(skeletonId);
    if (!skel) return false;
    AnimationSystem probe(nullptr);
    return probe.IsClipSkeletonGPUSafe(skeletonId, clipIndex, *skel, clipStore);
}

namespace {
    uint32 s_TestRuntimeId = 0;
    uint32 s_TestRuntimeSkeletonId = 0;
}

uint32 GetLastTestRuntimeId()
{
    return s_TestRuntimeId;
}

void SampleByRefsForTest(Components::AnimatorRef& animRef, uint32 skeletonId, float32 deltaTime)
{
    static PoseSampleWorkspace workspace;
    auto& clipStore = ClipStore::Instance();
    auto& skStore = SkeletonStore::Instance();

    if (animRef.ClipIndex == 0 || skeletonId == 0) return;
    auto clip = clipStore.Get(animRef.ClipIndex);
    auto* skel = skStore.Get(skeletonId);
    if (!clip || !skel || skel->BoneCount == 0) return;

    TickAnimatorRef(animRef, clipStore, deltaTime, nullptr);

    if (s_TestRuntimeId == 0 || s_TestRuntimeSkeletonId != skeletonId)
    {
        s_TestRuntimeId = skStore.CreateRuntime(skeletonId);
        s_TestRuntimeSkeletonId = skeletonId;
    }
    auto* runtime = skStore.GetRuntime(s_TestRuntimeId);
    if (!runtime) return;
    if (animRef.IsBlending())
    {
        static PoseSampleWorkspace blendFrom;
        auto prev = clipStore.Get(animRef.PrevClipIndex);
        if (prev)
        {
            SampleAnimationPose(*skel, prev.get(), animRef.PrevTime, nullptr, nullptr, blendFrom);
            SampleAnimationPose(*skel, clip.get(), animRef.Time, nullptr, nullptr, workspace);
            BlendLocalPoses(workspace, blendFrom, animRef.BlendAlpha());
            ::GameEngine::Animation::BuildPoseToSkinMatrices(
                *skel, nullptr, &runtime->CompactSkinMatrices, workspace);
            return;
        }
    }
    SampleAnimationPose(*skel, clip.get(), animRef.Time, nullptr, &runtime->CompactSkinMatrices, workspace);
}

} // namespace TestHooks

} } // namespace GameEngine::Engine::Renderer
