# The complete managed notice tree travels with desktop and SDK output.
if(NOT DEFINED SCRIPT OR NOT DEFINED SOURCE OR NOT DEFINED WORK)
    message(FATAL_ERROR "StageManagedNoticesTest: SCRIPT, SOURCE and WORK are required")
endif()
set(_share "${WORK}/installed/test-triplet/share")
set(_out "${WORK}/out")
# A form feed, as FreeType's copyright file carries, must not reach the aggregate.
string(ASCII 12 _form_feed)
foreach(_port IN ITEMS ez-tree-upstream diharaw-volumetric-fog-upstream
        sanielx-height-fog-upstream mirzabeig-gpu-fog-particles-upstream
        crest-ocean-upstream godot-visual-shader-upstream renderdoc-app-api-upstream)
    file(WRITE "${_share}/${_port}/copyright" "Fixture permission text.${_form_feed}\n")
endforeach()
file(WRITE "${_share}/ez-tree-upstream/EZTREE_UPSTREAM.json" "{}\n")
file(WRITE "${_share}/renderdoc-app-api-upstream/RENDERDOC_APP_API_UPSTREAM.json" "{}\n")
file(GLOB_RECURSE _files LIST_DIRECTORIES false "${SOURCE}/Managed/licenses/*")
list(APPEND _files "${SOURCE}/Managed/THIRD_PARTY_NOTICES.md")
foreach(_file IN LISTS _files)
    file(RELATIVE_PATH _relative "${SOURCE}/Managed" "${_file}")
    file(REMOVE "${_out}/Managed/${_relative}")
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DGE_SOURCE_DIR=${SOURCE}" "-DGE_NOTICES_DEST=${_out}"
    "-DGE_VCPKG_INSTALLED_DIR=${WORK}/installed" "-DGE_VCPKG_TARGET_TRIPLET=test-triplet"
    -P "${SCRIPT}" COMMAND_ERROR_IS_FATAL ANY)
foreach(_file IN LISTS _files)
    file(RELATIVE_PATH _relative "${SOURCE}/Managed" "${_file}")
    if(NOT EXISTS "${_out}/Managed/${_relative}")
        message(FATAL_ERROR "managed notice missing: ${_relative}")
    endif()
    file(SHA256 "${_file}" _source_hash)
    file(SHA256 "${_out}/Managed/${_relative}" _staged_hash)
    if(NOT _source_hash STREQUAL _staged_hash)
        message(FATAL_ERROR "managed notice changed: ${_relative}")
    endif()
endforeach()
# The aggregate reads as text: no byte below 0x20 other than tab, LF and CR, and the
# RTF notice appears as its displayed text.
file(READ "${_out}/THIRD_PARTY_NOTICES.md" _book)
string(REGEX MATCH "^.*" _book_before_nul "${_book}")
string(LENGTH "${_book_before_nul}" _book_before_nul_length)
string(LENGTH "${_book}" _book_length)
if(NOT _book_before_nul_length EQUAL _book_length)
    message(FATAL_ERROR "aggregate notice contains a NUL byte at offset ${_book_before_nul_length}")
endif()
string(ASCII 1 2 3 4 5 6 7 8 11 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 _controls)
if(_book MATCHES "[${_controls}]")
    message(FATAL_ERROR "aggregate notice contains a control byte other than tab, LF or CR")
endif()
if(_book MATCHES "\\\\rtf1|\\\\pard")
    message(FATAL_ERROR "aggregate notice carries RTF markup")
endif()
string(FIND "${_book}" "END OF .NET Compiler Platform NOTICES AND INFORMATION" _rtf_text)
if(_rtf_text EQUAL -1)
    message(FATAL_ERROR "aggregate notice omits the text of the RTF notice")
endif()
message(STATUS "StageManagedNoticesTest: passed")
