using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GameEngine.InteropGenerator;

/// <summary>
/// Roslyn source generator that emits typed interop wrappers and auto-registers managed callbacks
/// for methods annotated with [GameEngine.Interop.GenerateBinding].
/// </summary>

[Generator]
public class Generator : ISourceGenerator
{
    /// <summary>Initialize the source generator. No-op in this minimal example.</summary>
    public void Initialize(GeneratorInitializationContext context) { }


    private static string? MapType(ITypeSymbol t)
    {
        if (t is IPointerTypeSymbol ptr)
        {
            var p = ptr.PointedAtType;
            switch (p.SpecialType)
            {
                case SpecialType.System_Byte: return "byte*";
                case SpecialType.System_Int32: return "int*";
                case SpecialType.System_UInt64: return "ulong*";
                default: return null;
            }
        }
        switch (t.SpecialType)
        {
            case SpecialType.System_UInt64: return "ulong";
            case SpecialType.System_UInt32: return "uint";
            case SpecialType.System_Int32: return "int";
            case SpecialType.System_Void: return "void";
            default: return null;
        }
    }

    private static string? BuildDelegatePointerSignature(IMethodSymbol m)
    {
        var sb = new StringBuilder();
        sb.Append("delegate* unmanaged[Cdecl]<");
        for (int i = 0; i < m.Parameters.Length; i++)
        {
            var map = MapType(m.Parameters[i].Type);
            if (map == null) return null;
            if (i > 0) sb.Append(", ");
            sb.Append(map);
        }
        var ret = MapType(m.ReturnType);
        if (ret == null) return null;
        if (m.Parameters.Length > 0) sb.Append(", ");
        sb.Append(ret);
        sb.Append(">");
        return sb.ToString();
    }

    /// <summary>Emit typed interop wrappers and auto-register managed callbacks for [GenerateBinding] annotated methods.</summary>
    public void Execute(GeneratorExecutionContext context)
    {
        // 1) Existing simple interop wrappers (left as-is for now)
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Typed interop wrappers");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("namespace GameEngine.Scripting.Interop {");
        sb.AppendLine("  internal static class Native {");
        sb.AppendLine("    private const string kLib = \"GameEngine.Native\";");
        sb.AppendLine("    [DllImport(kLib, CallingConvention=CallingConvention.Cdecl)] public static extern unsafe int GE_Log(int level, byte* msg, uint len);");
        sb.AppendLine("    public static unsafe void GE_LogString(int level, string message) {");
        sb.AppendLine("      if (string.IsNullOrEmpty(message)) return;");
        sb.AppendLine("      var utf8 = System.Text.Encoding.UTF8;");
        sb.AppendLine("      int byteLen = utf8.GetByteCount(message);");
        sb.AppendLine("      byte[] buffer = System.Buffers.ArrayPool<byte>.Shared.Rent(byteLen);");
        sb.AppendLine("      try { int written = utf8.GetBytes(message, 0, message.Length, buffer, 0); fixed (byte* p = buffer) { _ = GE_Log(level, p, (uint)written); } } finally { System.Buffers.ArrayPool<byte>.Shared.Return(buffer); }");
        sb.AppendLine("    }");
        sb.AppendLine("    [DllImport(kLib, CallingConvention=CallingConvention.Cdecl)] public static extern int GE_GetAssetCount(out int count);");
        sb.AppendLine("    [DllImport(kLib, CallingConvention=CallingConvention.Cdecl)] public static extern int GE_ECS_GetWorldHandle(out ulong world);");
        sb.AppendLine("    [DllImport(kLib, CallingConvention=CallingConvention.Cdecl)] public static extern int GE_ECS_GetEntityCount(ulong world, out int count);");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        context.AddSource("GameEngine.Scripting.Interop.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

        // 2) Generate HotReloadManager reflection bindings (unchanged)
        var sbHrm = new StringBuilder();
        sbHrm.AppendLine("// <auto-generated/> HotReloadManager binding helpers");
        sbHrm.AppendLine("#nullable enable");
        sbHrm.AppendLine("using System;");
        sbHrm.AppendLine("using System.Reflection;");
        sbHrm.AppendLine("namespace GameEngine.CoreBridge.Generated {");
        sbHrm.AppendLine("  internal static class HrmBindings {");
        sbHrm.AppendLine("    internal sealed class Bound {");
        sbHrm.AppendLine("      public MethodInfo? MiCallInDomain, MiQueryExportInDomain, MiInvokeByToken, MiPreloadAssemblyContext, MiSwapPreloadedContext, MiCleanupOldContext, MiGetUserScriptsAssemblyInfo;");
        sbHrm.AppendLine("    }");
        sbHrm.AppendLine("    private static MethodInfo? GetPublic(Type t, string name, Type[]? types = null) => types == null ? t.GetMethod(name, BindingFlags.Public|BindingFlags.Static) : t.GetMethod(name, BindingFlags.Public|BindingFlags.Static, binder: null, types: types, modifiers: null);");
        sbHrm.AppendLine("    private static MethodInfo? GetNonPublic(Type t, string name, Type[]? types = null) => types == null ? t.GetMethod(name, BindingFlags.NonPublic|BindingFlags.Static) : t.GetMethod(name, BindingFlags.NonPublic|BindingFlags.Static, binder: null, types: types, modifiers: null);");
        sbHrm.AppendLine("    internal static Bound Bind(Type hrmType) {");
        sbHrm.AppendLine("      var b = new Bound();");
        sbHrm.AppendLine("      var tUL = typeof(ulong); var tStr = typeof(string);");
        sbHrm.AppendLine("      b.MiCallInDomain = GetPublic(hrmType, \"CallMethodInDomain\", new[]{ tUL, tStr });");
        sbHrm.AppendLine("      b.MiQueryExportInDomain = GetPublic(hrmType, \"QueryExportInDomain\", new[]{ tUL, tStr, typeof(ulong).MakeByRefType() });");
        sbHrm.AppendLine("      b.MiInvokeByToken = GetPublic(hrmType, \"InvokeByToken\", new[]{ tUL, tUL });");
        sbHrm.AppendLine("      b.MiPreloadAssemblyContext = GetPublic(hrmType, \"PreloadAssemblyContext\", new[]{ tStr });");
        sbHrm.AppendLine("      b.MiSwapPreloadedContext = GetPublic(hrmType, \"SwapPreloadedContext\");");
        sbHrm.AppendLine("      b.MiCleanupOldContext = GetNonPublic(hrmType, \"HandleCleanupOldContext\", new[]{ tStr });");
        sbHrm.AppendLine("      b.MiGetUserScriptsAssemblyInfo = GetPublic(hrmType, \"GetUserScriptsAssemblyInfo\");");
        sbHrm.AppendLine("      return b;");
        sbHrm.AppendLine("    }");
        sbHrm.AppendLine("  }");
        sbHrm.AppendLine("}");
        context.AddSource("GameEngine.CoreBridge.HrmBindings.g.cs", SourceText.From(sbHrm.ToString(), Encoding.UTF8));

        // 3) Generate CoreBridge managed-callback registration for [GenerateBinding]
        // Minimal AST scan: find symbols named 'CoreBridge' in GameEngine.CoreBridge and methods marked with GenerateBinding
        var compilation = context.Compilation;
        var coreBridgeType = compilation.GetTypeByMetadataName("GameEngine.CoreBridge.CoreBridge");
        var attrType = compilation.GetTypeByMetadataName("GameEngine.Interop.GenerateBindingAttribute");
        var sbAuto = new StringBuilder();
        sbAuto.AppendLine("// <auto-generated/> Managed-callback auto-registration");
        sbAuto.AppendLine("using System.Runtime.CompilerServices;");
        sbAuto.AppendLine("namespace GameEngine.CoreBridge { public static unsafe partial class CoreBridge { ");
        sbAuto.AppendLine("  private static unsafe void AutoRegisterGeneratedBindings(GameEngine.Interop.EngineNativeBinding binding) {");
        if (coreBridgeType == null || attrType == null)
        {
            // Nothing to generate
            return;
        }

        if (coreBridgeType != null && attrType != null)
        {
            foreach (var member in coreBridgeType.GetMembers().OfType<IMethodSymbol>())
            {
                var attr = member.GetAttributes().FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrType));
                if (attr == null) continue;
                // Expect attribute ctor (uint id)
                if (attr.ConstructorArguments.Length != 1) continue;
                var idVal = attr.ConstructorArguments[0].Value;
                if (idVal is not uint id) continue;
                // Build delegate* unmanaged signature based on parameter types
                string? sig = BuildDelegatePointerSignature(member);
                if (string.IsNullOrEmpty(sig)) continue;
                sbAuto.AppendLine($"    var cb_{member.Name} = (nint)({sig})&{member.Name};");
                sbAuto.AppendLine($"    binding.TryRegisterManagedCallback({id}, cb_{member.Name});");
            }
        }
        sbAuto.AppendLine("  }");
        sbAuto.AppendLine("}} ");
        context.AddSource("GameEngine.CoreBridge.AutoRegisterBindings.g.cs", SourceText.From(sbAuto.ToString(), Encoding.UTF8));
    }
}

