// Generated by Tools/ShaderGen/gen_aces2_tables.py - DO NOT EDIT.
// The Aces2Tables device buffer: OpenColorIO 2.5.2 ACES 2.0 Rec.709
// output-transform tables at peak luminances 100*2^k nits, k = 0..5, plus
// the per-tier peak-baked scalars that are not closed-form in peak. The
// data is generated into TonemapAces2Tables.h and uploaded once per device
// (TonemapPass); tonemap_aces2.glsl blends adjacent tiers at runtime. The
// aces2_tier_scalars slot layout is defined by EMITTED_SLOTS in the
// generator and mirrored by Aces2SelectTier. Member order is vec4-first so
// std430 packs with zero padding (offsets asserted in the C++ header).
// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the OpenColorIO Project.
// See ThirdParty/OpenColorIO/LICENSE.txt and UPSTREAM.md.

#ifndef GE_TONEMAP_ACES2_TABLES_GLSL
#define GE_TONEMAP_ACES2_TABLES_GLSL

const int kAces2TierCount = 6;

// [tier][slot] slots: 0=tsFScale, 1=tsSDiv, 2=limitJMax, 3=midJ, 4=gammaBottomInv, 5=mnormCosW.x, 6=mnormCosW.y, 7=mnormCosW.z, 8=mnormSinW.x, 9=mnormSinW.y, 10=mnormSinW.z, 11=mnormOffset
layout(set = 0, binding = 2, std430) readonly buffer Aces2Tables
{
    vec4  aces2_gamut_cusp_tables[6][363]; // xyz = cusp J / cusp M / upper-hull gamma; w unused
    float aces2_reach_m_tables[6][363];
    float aces2_hues_tables[6][363];
    float aces2_tier_scalars[6][12];
};

#endif
