#include "Animation/HumanoidRig.h"

#include "AssetCore/SharedFileRead.h"
#include "Logger/Logger.h"

#include <fstream>
#include <iterator>
#include <nlohmann/json.hpp>
#include <string>

namespace GameEngine
{
namespace Animation
{

namespace
{

using json = nlohmann::json;

constexpr const char* kChainKindNames[] = {
    "LeftArm",
    "RightArm",
    "LeftLeg",
    "RightLeg",
    "Spine",
    "Head",
    "LeftFingers",
    "RightFingers",
    "Tail",
    "Other"
};
static_assert(sizeof(kChainKindNames) / sizeof(kChainKindNames[0]) ==
                  static_cast<size_t>(ChainKind::Other) + 1,
              "kChainKindNames must enumerate every ChainKind");

constexpr const char* kAttachmentPassthroughModeNames[] = {
    "CopyLocal",
    "Procedural",
    "Static"
};
static_assert(sizeof(kAttachmentPassthroughModeNames) / sizeof(kAttachmentPassthroughModeNames[0]) ==
                  static_cast<size_t>(AttachmentPassthroughMode::Static) + 1,
              "kAttachmentPassthroughModeNames must enumerate every AttachmentPassthroughMode");

json Vec3ToJson(const Mathematics::Vector3& v) { return json::array({v.x, v.y, v.z}); }

Mathematics::Vector3 JsonToVec3(const json& j, const Mathematics::Vector3& fallback)
{
    if (!j.is_array() || j.size() < 3)
        return fallback;
    return Mathematics::Vector3(j[0].get<float>(), j[1].get<float>(), j[2].get<float>());
}

json QuatToJson(const Mathematics::Quaternion& q)
{
    const glm::quat& g = q.GetGLM();
    return json::array({g.w, g.x, g.y, g.z});
}

Mathematics::Quaternion JsonToQuat(const json& j, const Mathematics::Quaternion& fallback)
{
    if (!j.is_array() || j.size() < 4)
        return fallback;
    return Mathematics::Quaternion(
        j[0].get<float>(), j[1].get<float>(), j[2].get<float>(), j[3].get<float>());
}

} // namespace

const char* ChainKindToString(ChainKind kind)
{
    const auto idx = static_cast<size_t>(kind);
    if (idx >= sizeof(kChainKindNames) / sizeof(kChainKindNames[0]))
        return "Other";
    return kChainKindNames[idx];
}

ChainKind ChainKindFromString(std::string_view name)
{
    for (size_t i = 0; i < sizeof(kChainKindNames) / sizeof(kChainKindNames[0]); ++i)
    {
        if (name == kChainKindNames[i])
            return static_cast<ChainKind>(i);
    }
    return ChainKind::Other;
}

const char* AttachmentPassthroughModeToString(AttachmentPassthroughMode mode)
{
    const auto idx = static_cast<size_t>(mode);
    if (idx >= sizeof(kAttachmentPassthroughModeNames) / sizeof(kAttachmentPassthroughModeNames[0]))
        return "CopyLocal";
    return kAttachmentPassthroughModeNames[idx];
}

AttachmentPassthroughMode AttachmentPassthroughModeFromString(std::string_view name)
{
    for (size_t i = 0; i < sizeof(kAttachmentPassthroughModeNames) / sizeof(kAttachmentPassthroughModeNames[0]); ++i)
    {
        if (name == kAttachmentPassthroughModeNames[i])
            return static_cast<AttachmentPassthroughMode>(i);
    }
    return AttachmentPassthroughMode::CopyLocal;
}

bool HumanoidRig::Load()
{
    SetState(AssetState::Loading);

    String text;
    if (!ReadFileTextShared(GetPath(), text))
    {
        Logger::Log::Error("HumanoidRig: cannot open '{}'", GetPath().string());
        SetState(AssetState::Failed);
        return false;
    }
    return ParseJson(text);
}

bool HumanoidRig::LoadFromData(const Vector<uint8>& data)
{
    SetState(AssetState::Loading);
    const std::string text(reinterpret_cast<const char*>(data.data()), data.size());
    return ParseJson(text);
}

void HumanoidRig::Unload()
{
    m_Version = 0;
    m_ProfileRef = ::GameEngine::GUID();
    m_BoneMap.clear();
    m_Chains.clear();
    m_TranslationBones.clear();
    m_TranslationBones.push_back(HumanBone::Hips);
    m_Proportions = BodyProportions{};
    m_Attachments.clear();
    m_AutoGenerated = false;
    SetState(AssetState::Unloaded);
}

bool HumanoidRig::SaveToData(Vector<uint8>& outData) const
{
    const std::string serialized = SerializeJson();
    outData.assign(serialized.begin(), serialized.end());
    return true;
}

bool HumanoidRig::SaveToPath(const std::filesystem::path& path) const
{
    std::ofstream file(path, std::ios::binary | std::ios::trunc);
    if (!file.is_open())
    {
        Logger::Log::Error("HumanoidRig: cannot open '{}' for write", path.string());
        return false;
    }
    const std::string serialized = SerializeJson();
    file.write(serialized.data(), static_cast<std::streamsize>(serialized.size()));
    return file.good();
}

bool HumanoidRig::ParseJson(const std::string& text)
{
    try
    {
        const auto doc = json::parse(text);

        m_Version = doc.value("version", 0);
        if (m_Version > kSchemaVersion)
        {
            Logger::Log::Warning(
                "HumanoidRig '{}' has version {} but engine supports up to {}; reading anyway",
                GetPath().string(), m_Version, kSchemaVersion);
        }

        m_AutoGenerated = doc.value("auto", false);

        if (doc.contains("profileRef") && doc["profileRef"].is_string())
        {
            m_ProfileRef = ::GameEngine::GUID(doc["profileRef"].get<std::string>());
        }
        else
        {
            m_ProfileRef = ::GameEngine::GUID();
        }

        m_BoneMap.clear();
        if (doc.contains("boneMap") && doc["boneMap"].is_array())
        {
            m_BoneMap.reserve(doc["boneMap"].size());
            for (const auto& m : doc["boneMap"])
            {
                HumanoidBoneMapping mapping;
                mapping.Canonical = HumanBoneFromString(m.value("canonical", std::string("None")));
                mapping.SourceBoneName = m.value("sourceBoneName", std::string());
                mapping.CachedSourceIndex = ~0u; // intentionally not persisted
                mapping.RetargetPoseRotation = JsonToQuat(m.value("retargetPoseRotation", json::array()),
                                                         Mathematics::Quaternion::Identity());
                m_BoneMap.push_back(std::move(mapping));
            }
        }

        m_Chains.clear();
        if (doc.contains("chains") && doc["chains"].is_array())
        {
            m_Chains.reserve(doc["chains"].size());
            for (const auto& c : doc["chains"])
            {
                HumanoidChain chain;
                chain.Kind = ChainKindFromString(c.value("kind", std::string("Other")));
                chain.Start = HumanBoneFromString(c.value("start", std::string("None")));
                chain.End = HumanBoneFromString(c.value("end", std::string("None")));
                if (c.contains("includeBones") && c["includeBones"].is_array())
                {
                    chain.IncludeBones.reserve(c["includeBones"].size());
                    for (const auto& bn : c["includeBones"])
                        chain.IncludeBones.push_back(HumanBoneFromString(bn.get<std::string>()));
                }
                m_Chains.push_back(std::move(chain));
            }
        }

        m_TranslationBones.clear();
        if (doc.contains("translationBones") && doc["translationBones"].is_array())
        {
            m_TranslationBones.reserve(doc["translationBones"].size());
            for (const auto& tb : doc["translationBones"])
                m_TranslationBones.push_back(HumanBoneFromString(tb.get<std::string>()));
        }
        else
        {
            m_TranslationBones.push_back(HumanBone::Hips);
        }

        m_Proportions = BodyProportions{};
        if (doc.contains("proportions") && doc["proportions"].is_object())
        {
            const auto& p = doc["proportions"];
            m_Proportions.HipHeight = p.value("hipHeight", 0.0f);
            m_Proportions.ShoulderWidth = p.value("shoulderWidth", 0.0f);
            m_Proportions.LegLength = p.value("legLength", 0.0f);
            m_Proportions.ArmLength = p.value("armLength", 0.0f);
            if (p.contains("perChainLengths") && p["perChainLengths"].is_array())
            {
                const auto& a = p["perChainLengths"];
                const size_t n = std::min(a.size(), m_Proportions.PerChainLengths.size());
                for (size_t i = 0; i < n; ++i)
                    m_Proportions.PerChainLengths[i] = a[i].get<float>();
            }
        }

        m_Attachments.clear();
        if (doc.contains("attachments") && doc["attachments"].is_array())
        {
            m_Attachments.reserve(doc["attachments"].size());
            for (const auto& a : doc["attachments"])
            {
                AttachmentBone att;
                att.Name = a.value("name", std::string());
                att.ParentBone = HumanBoneFromString(a.value("parentBone", std::string("None")));
                att.LocalOffset = JsonToVec3(a.value("localOffset", json::array()),
                                             Mathematics::Vector3(0.0f, 0.0f, 0.0f));
                att.Mode = AttachmentPassthroughModeFromString(a.value("mode", std::string("CopyLocal")));
                m_Attachments.push_back(std::move(att));
            }
        }

        SetState(AssetState::Loaded);
        return true;
    }
    catch (const std::exception& e)
    {
        Logger::Log::Error("HumanoidRig: failed to parse '{}': {}", GetPath().string(), e.what());
        SetState(AssetState::Failed);
        return false;
    }
}

std::string HumanoidRig::SerializeJson() const
{
    json doc;
    doc["version"] = kSchemaVersion;
    doc["auto"] = m_AutoGenerated;
    doc["profileRef"] = m_ProfileRef.ToString();

    json bm = json::array();
    for (const auto& m : m_BoneMap)
    {
        json e;
        e["canonical"] = HumanBoneToString(m.Canonical);
        e["sourceBoneName"] = m.SourceBoneName;
        // CachedSourceIndex intentionally omitted: it's runtime acceleration.
        e["retargetPoseRotation"] = QuatToJson(m.RetargetPoseRotation);
        bm.push_back(std::move(e));
    }
    doc["boneMap"] = std::move(bm);

    json cs = json::array();
    for (const auto& c : m_Chains)
    {
        json e;
        e["kind"] = ChainKindToString(c.Kind);
        e["start"] = HumanBoneToString(c.Start);
        e["end"] = HumanBoneToString(c.End);
        json incl = json::array();
        for (auto b : c.IncludeBones)
            incl.push_back(HumanBoneToString(b));
        e["includeBones"] = std::move(incl);
        cs.push_back(std::move(e));
    }
    doc["chains"] = std::move(cs);

    json tb = json::array();
    for (auto b : m_TranslationBones)
        tb.push_back(HumanBoneToString(b));
    doc["translationBones"] = std::move(tb);

    json p;
    p["hipHeight"] = m_Proportions.HipHeight;
    p["shoulderWidth"] = m_Proportions.ShoulderWidth;
    p["legLength"] = m_Proportions.LegLength;
    p["armLength"] = m_Proportions.ArmLength;
    json perChain = json::array();
    for (float v : m_Proportions.PerChainLengths)
        perChain.push_back(v);
    p["perChainLengths"] = std::move(perChain);
    doc["proportions"] = std::move(p);

    json atts = json::array();
    for (const auto& att : m_Attachments)
    {
        json e;
        e["name"] = att.Name;
        e["parentBone"] = HumanBoneToString(att.ParentBone);
        e["localOffset"] = Vec3ToJson(att.LocalOffset);
        e["mode"] = AttachmentPassthroughModeToString(att.Mode);
        atts.push_back(std::move(e));
    }
    doc["attachments"] = std::move(atts);

    return doc.dump(2);
}

} // namespace Animation
} // namespace GameEngine
