#include "Inspectors/GeneratedEntityNotice.h"

#include "Components/Hierarchy.h"
#include "Components/RuntimeOnlyEntity.h"
#include "ECS/World.h"
#include "Editor/Entities/EntityDisplayName.h"
#include "UI/Controls/InspectorNotice.h"

#include <memory>
#include <string>

namespace GameEngine::Editor
{

void AddGeneratedEntityNotice(UIElement* parent, ECS::World& world, ECS::EntityHandle entity,
                              const std::function<void(ECS::EntityHandle)>& selectEntity)
{
    if (!parent || !world.HasComponent<Components::RuntimeOnlyEntity>(entity))
        return;

    std::string text;
    std::string owner;
    const auto* parentLink = world.GetComponent<Components::Parent>(entity);
    if (parentLink && parentLink->parent.IsValid() && world.IsValid(parentLink->parent))
    {
        owner = EntityDisplayName(world, parentLink->parent);
        text = "Generated by " + owner +
               ". This piece is rebuilt from its spline and recipe, and is not saved with the "
               "scene - edits made here are overwritten on the next rebuild. Edit " + owner +
               " instead.";
    }
    else
    {
        text = "Generated at runtime. This entity is rebuilt from its source and is not saved "
               "with the scene - edits made here are overwritten on the next rebuild.";
    }

    auto notice = std::make_unique<EditorUI::InspectorNotice>(text);
    if (!owner.empty() && selectEntity)
    {
        const ECS::EntityHandle ownerEntity = parentLink->parent;
        notice->SetAction("Select owner", "Select " + owner + ", which generates this entity",
                          [selectEntity, ownerEntity]() { selectEntity(ownerEntity); });
    }
    parent->AddChild(std::move(notice));
}

} // namespace GameEngine::Editor
