#include "Inspectors/SplineInspector.h"

#include "InspectorRegistry.h"

#include "Components/Transform.h"
#include "Components/Spline/SplineComponent.h"
#include "Editor/Entities/EditorECSHelpers.h"
#include "Mathematics/Matrix4x4.h"
#include "Placement/CenterlineSampling.h"
#include "SplineECS/SplineService.h"
#include "Spline/SplineData.h"
#include "Spline/SplineEvaluator.h"
#include "Spline/SplineTypes.h"
#include "Spline/SplineUtility.h"
#include "SceneView/SplineOwnerQuery.h"
#include "SceneView/SplineTool.h"
#include "Inspectors/InspectorComponentRowHelpers.h"
#include "Inspectors/InspectorDragHelpers.h"
#include "Inspectors/InspectorUIHelpers.h"
#include "UndoRedo/SplinePointEdits.h"
#include "UndoRedo/SplineUndoHelpers.h"
#include "UndoRedo/UndoRedoService.h"
#include "UI/Controls/Button.h"
#include "UI/Controls/CollapsibleInfoCard.h"
#include "UI/InfoCard.h"
#include "UI/Controls/Foldout.h"
#include "UI/Controls/FloatField.h"
#include "UI/Controls/InspectorNotice.h"
#include "UI/Controls/Label.h"
#include "UI/Controls/Vector3Field.h"
#include "UI/StyleProperties.h"

#include <algorithm>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace GameEngine
{
namespace
{

using Editor::EditorChangeNotifications;
using Editor::SplineUndo::CommitSplineDataOneShot;
using Editor::SplineUndo::MakeSplineEditableSnapshotTarget;
using Editor::UndoRedoService;

struct SplinePointFieldRefs
{
    Vector3Field* Location = nullptr;
    Vector3Field* Rotation = nullptr;
    Vector3Field* Scale = nullptr;
    Vector3Field* TangentIn = nullptr;
    Vector3Field* TangentOut = nullptr;
    FloatField* Radius = nullptr;
    FloatField* Roll = nullptr;
};

static void AddSplineInfoCard(UIElement* parent, uint32 pointCount, uint32 segmentCount,
                              const std::optional<float32>& worldLength)
{
    UIElement* row = InspectorUI::AddRow(parent);
    row->AddClass("inspector-guide-row");
    InspectorUI::AddLabel(row, "Spline Info",
        "Summary of the spline geometry generated by its control points.");
    UIElement* fieldContainer = InspectorUI::AddFieldContainer(row);
    fieldContainer->AddClass("inspector-guide-field");

    std::string summary = "Points: " + std::to_string(pointCount) + "\n" +
                          "Segments: " + std::to_string(segmentCount);
    if (worldLength)
    {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "\nLength: %.1f m", *worldLength);
        summary += buf;
    }

    fieldContainer->AddChild(std::make_unique<EditorUI::CollapsibleInfoCard>(summary));
}

class SplineInspectorLiveRefresh final : public UIElement
{
public:
    SplineInspectorLiveRefresh(EditorChangeNotifications* notifications,
                               ECS::World* world,
                               ECS::EntityHandle entity,
                               SplineECS::SplineService* splineService,
                               SplineECS::SplineHandle handle,
                               std::shared_ptr<std::vector<SplinePointFieldRefs>> pointFields)
        : m_Notifications(notifications),
          m_World(world),
          m_Entity(entity),
          m_SplineService(splineService),
          m_Handle(handle),
          m_PointFields(std::move(pointFields))
    {
        InlineOverrides().Set(Style::Display, DisplayMode::None);
        if (!m_Notifications || !m_World || !m_Entity.IsValid())
            return;

        const ECS::ComponentTypeId splineType = ECS::GetComponentTypeId<Components::SplineComponent>();
        m_Subscription = m_Notifications->SubscribeComponentChanged(
            [this, splineType](const EditorChangeNotifications::ComponentChangedEvent& ev)
            {
                if (ev.world != m_World || ev.entity != m_Entity || ev.componentType != splineType)
                    return;
                if (ev.kind != EditorChangeNotifications::ChangeKind::Preview &&
                    ev.kind != EditorChangeNotifications::ChangeKind::Commit &&
                    ev.kind != EditorChangeNotifications::ChangeKind::UndoRedo)
                {
                    return;
                }

                RefreshPointFields();
            });
    }

    ~SplineInspectorLiveRefresh() override
    {
        if (m_Notifications && m_Subscription)
            m_Notifications->Unsubscribe(m_Subscription);
    }

private:
    static Rendering::Vector3 ToUiVector(const Mathematics::Vector3& v)
    {
        return Rendering::Vector3(v.x, v.y, v.z);
    }

    void RefreshPointFields()
    {
        if (!m_PointFields || !m_SplineService)
            return;

        const auto* data = m_SplineService->GetSplineData(m_Handle);
        if (!data)
            return;

        const size_t count = std::min(m_PointFields->size(), data->Points.size());
        for (size_t i = 0; i < count; ++i)
        {
            const auto& point = data->Points[i];
            const SplinePointFieldRefs& fields = (*m_PointFields)[i];
            if (fields.Location)
                fields.Location->SetValue(ToUiVector(point.Position));
            if (fields.Rotation)
                fields.Rotation->SetValue(ToUiVector(point.Rotation));
            if (fields.Scale)
                fields.Scale->SetValue(ToUiVector(point.Scale));
            if (fields.TangentIn)
                fields.TangentIn->SetValue(ToUiVector(point.TangentIn));
            if (fields.TangentOut)
                fields.TangentOut->SetValue(ToUiVector(point.TangentOut));
            if (fields.Radius)
                fields.Radius->SetValue(point.Radius);
            if (fields.Roll)
                fields.Roll->SetValue(point.Roll);
        }
    }

    EditorChangeNotifications* m_Notifications = nullptr;
    ECS::World* m_World = nullptr;
    ECS::EntityHandle m_Entity{};
    SplineECS::SplineService* m_SplineService = nullptr;
    SplineECS::SplineHandle m_Handle{};
    std::shared_ptr<std::vector<SplinePointFieldRefs>> m_PointFields;
    EditorChangeNotifications::SubscriptionToken m_Subscription{};
};

static FloatField* AddSplineFloatRowWithUndo(UIElement* parent,
                                             const std::string& rowLabel,
                                             float initialValue,
                                             SplineECS::SplineService* splineService,
                                             SplineECS::SplineHandle splineHandle,
                                             ECS::World* world,
                                             ECS::EntityHandle entity,
                                             EditorChangeNotifications* notifications,
                                             UndoRedoService* undo,
                                             const std::string& undoEditName,
                                             const std::function<void(GameEngine::Spline::SplineData*, float v)>& mutate,
                                             float defaultResetValue,
                                             const char* tooltip)
{
    using namespace InspectorDrag;
    using OptEdit = std::optional<UndoRedoService::InteractiveEdit>;
    auto editPtr = std::make_shared<OptEdit>();

    return AddFloatRowWithDrag(
        parent,
        rowLabel,
        initialValue,
        [splineService, splineHandle, world, entity, notifications, undo, mutate, editPtr,
         undoEditName](float v)
        {
            if (!splineService)
                return;

            if (!editPtr->has_value() && undo)
            {
                UndoRedoService::InteractiveEdit ie =
                    undo->BeginInteractiveEdit(undoEditName,
                        MakeSplineEditableSnapshotTarget(splineService, splineHandle, world, entity, notifications,
                                                         undoEditName));
                if (!ie)
                    return;
                editPtr->emplace(std::move(ie));
            }

            auto* data = splineService->GetSplineData(splineHandle);
            if (!data)
                return;

            mutate(data, v);
            data->MarkDirty();
            splineService->RebuildCache(splineHandle);

            if (editPtr->has_value() && static_cast<bool>(editPtr->value()))
            {
                editPtr->value().Preview([splineService, splineHandle]() {
                    splineService->RebuildCache(splineHandle);
                });
            }
            else if (notifications)
            {
                notifications->NotifyComponentChange<Components::SplineComponent>(
                    world, entity, EditorChangeNotifications::ChangeKind::Preview);
            }
        },
        [splineService, splineHandle, world, entity, notifications, undo, mutate, editPtr,
         undoEditName](float v)
        {
            if (!splineService)
                return;

            auto* data = splineService->GetSplineData(splineHandle);
            if (!data)
                return;

            if (editPtr->has_value() && static_cast<bool>(editPtr->value()))
            {
                mutate(data, v);
                data->MarkDirty();
                splineService->RebuildCache(splineHandle);
                editPtr->value().Commit();
                editPtr->reset();
            }
            else
            {
                CommitSplineDataOneShot(splineService, splineHandle, world, entity, notifications, undo, undoEditName,
                                    [&](GameEngine::Spline::SplineData* d) {
                                        mutate(d, v);
                                    });
            }
        },
        defaultResetValue,
        tooltip);
}

static Vector3Field* AddSplineVector3RowWithUndo(
    UIElement* parent,
    const std::string& rowLabel,
    const Mathematics::Vector3& initialValue,
    SplineECS::SplineService* splineService,
    SplineECS::SplineHandle splineHandle,
    ECS::World* world,
    ECS::EntityHandle entity,
    EditorChangeNotifications* notifications,
    UndoRedoService* undo,
    const std::string& undoEditName,
    const std::function<void(GameEngine::Spline::SplineData*, const Mathematics::Vector3&)>& mutate,
    const Mathematics::Vector3& defaultResetValue,
    const char* tooltip)
{
    using OptEdit = std::optional<UndoRedoService::InteractiveEdit>;
    auto editPtr = std::make_shared<OptEdit>();

    UIElement* row = InspectorUI::AddRow(parent);
    InspectorUI::AddLabel(row, rowLabel, tooltip);
    UIElement* fieldContainer = InspectorUI::AddFieldContainer(row);

    auto field = std::make_unique<Vector3Field>();
    field->AddClass("inspector-vector3");
    field->SetDefaultValue(Rendering::Vector3(defaultResetValue.x, defaultResetValue.y, defaultResetValue.z));
    field->SetValue(Rendering::Vector3(initialValue.x, initialValue.y, initialValue.z));
    Vector3Field* raw = field.get();

    raw->SetOnValueChanging(
        [splineService, splineHandle, world, entity, notifications, undo, mutate, editPtr,
         undoEditName](const Rendering::Vector3& v)
        {
            if (!splineService)
                return;

            if (!editPtr->has_value() && undo)
            {
                UndoRedoService::InteractiveEdit ie =
                    undo->BeginInteractiveEdit(undoEditName,
                        MakeSplineEditableSnapshotTarget(splineService, splineHandle, world, entity, notifications,
                                                         undoEditName));
                if (!ie)
                    return;
                editPtr->emplace(std::move(ie));
            }

            auto* data = splineService->GetSplineData(splineHandle);
            if (!data)
                return;

            mutate(data, Mathematics::Vector3(v.x, v.y, v.z));
            data->MarkDirty();
            splineService->RebuildCache(splineHandle);

            if (editPtr->has_value() && static_cast<bool>(editPtr->value()))
            {
                editPtr->value().Preview([splineService, splineHandle]() {
                    splineService->RebuildCache(splineHandle);
                });
            }
            else if (notifications)
            {
                notifications->NotifyComponentChange<Components::SplineComponent>(
                    world, entity, EditorChangeNotifications::ChangeKind::Preview);
            }
        });

    raw->SetOnValueChanged(
        [splineService, splineHandle, world, entity, notifications, undo, mutate, editPtr,
         undoEditName](const Rendering::Vector3& v)
        {
            if (!splineService)
                return;

            auto* data = splineService->GetSplineData(splineHandle);
            if (!data)
                return;

            const Mathematics::Vector3 value(v.x, v.y, v.z);
            if (editPtr->has_value() && static_cast<bool>(editPtr->value()))
            {
                mutate(data, value);
                data->MarkDirty();
                splineService->RebuildCache(splineHandle);
                editPtr->value().Commit();
                editPtr->reset();
            }
            else
            {
                CommitSplineDataOneShot(splineService, splineHandle, world, entity, notifications, undo, undoEditName,
                                    [&](GameEngine::Spline::SplineData* d) {
                                        mutate(d, value);
                                    });
            }
        });

    fieldContainer->AddChild(std::move(field));
    return raw;
}

void SelectSplineKnot(ECS::World& world, ECS::EntityHandle entity, uint32 pointIndex)
{
    const auto state = Editor::SceneTools::AcquireSplineInteractionState(world);
    auto& selection = state->Selection();
    const int32 index = static_cast<int32>(pointIndex);
    selection.Entity = entity;
    selection.PointIndex = index;
    selection.Kind = 1;
    selection.KnotIndices = {index};
    selection.Controls = {{entity, index, 1}};
}

int32 GetSelectedSplineKnot(ECS::World& world, ECS::EntityHandle entity, uint32 pointCount)
{
    const auto state = Editor::SceneTools::AcquireSplineInteractionState(world);
    auto& selection = state->Selection();
    int32 index = -1;
    if (!selection.Controls.empty())
    {
        const auto& active = selection.Controls.back();
        if (active.Entity == entity && active.Kind != 0)
            index = active.PointIndex;
    }
    else if (selection.Entity == entity && selection.Kind != 0)
    {
        index = selection.PointIndex;
    }

    if (index < 0 || static_cast<uint32>(index) >= pointCount)
        return -1;
    return index;
}

std::string FormatSelectedSplineKnotLabel(int32 selected, uint32 pointCount)
{
    if (selected < 0)
        return "None";
    return "Point " + std::to_string(selected) + " / " + std::to_string(pointCount - 1u);
}

struct ResamplePreviewState
{
    std::optional<UndoRedoService::InteractiveEdit> Edit;
    // Entity-local frames from SampleUniform — the authoritative resample
    // source, carrying every interpolated per-point channel.
    std::vector<Spline::SplineFrame> SourceFrames;
    // The same positions in world space when the entity has a WorldTransform:
    // simplification tolerance is measured in world units.
    std::vector<Mathematics::Vector3> MeasurePositions;
    // The control points before the resample, entity-local: what the recipes
    // addressed by point are re-addressed from when it commits.
    std::vector<Mathematics::Vector3> SourcePoints;
};

bool CaptureResampleSource(const Spline::SplineData& data,
                           ECS::World* world,
                           ECS::EntityHandle entity,
                           ResamplePreviewState& state)
{
    if (!data.IsValid())
        return false;

    const uint32 pointCount = static_cast<uint32>(data.Points.size());
    const uint32 sampleCount = std::max(256u, pointCount * 16u);

    state.SourcePoints.clear();
    for (const Spline::SplineControlPoint& point : data.Points)
        state.SourcePoints.push_back(point.Position);

    Spline::SampleUniform(data, sampleCount, state.SourceFrames);
    if (state.SourceFrames.empty())
        return false;

    state.MeasurePositions.clear();
    state.MeasurePositions.reserve(state.SourceFrames.size());

    const Components::WorldTransform* xf =
        (world && entity.IsValid()) ? world->GetComponent<Components::WorldTransform>(entity)
                                    : nullptr;
    if (xf)
    {
        const Mathematics::Matrix4x4 localToWorld = Mathematics::Matrix4x4::FromColumnMajor(xf->matrix);
        for (const auto& frame : state.SourceFrames)
            state.MeasurePositions.push_back(localToWorld.TransformPoint(frame.Position));
    }
    else
    {
        for (const auto& frame : state.SourceFrames)
            state.MeasurePositions.push_back(frame.Position);
    }
    return true;
}

// Deletes one control point as one undo step, with whatever the recipes on
// this spline re-address because the points after it moved down.
void DeleteSplinePoint(SplineECS::SplineService* splineService, SplineECS::SplineHandle handle,
                       ECS::World* w, ECS::EntityHandle e, Editor::EditorChangeNotifications* n,
                       Editor::UndoRedoService* undo, uint32 index)
{
    const auto* before = splineService->GetSplineData(handle);
    if (!before)
        return;
    const uint32 countBefore = static_cast<uint32>(before->Points.size());
    if (undo)
        undo->BeginCompound("Delete Spline Point");
    Editor::SplineUndo::CommitSplineDataOneShot(
        splineService, handle, w, e, n, undo, "Delete Spline Point",
        [index](GameEngine::Spline::SplineData* target) { (void)target->RemovePoint(index); });
    const auto* after = splineService->GetSplineData(handle);
    const uint32 removed[1] = {index};
    const Editor::SplinePointRenumbering renumbering = Editor::SplinePointRenumbering::Removed(
        countBefore, removed, after && after->IsEffectivelyClosed());
    Editor::SplinePointEdited().Invoke({w, e, undo, n, &renumbering});
    if (undo)
        undo->EndCompound();
}

bool ApplyResampleFromSource(Spline::SplineData& data, const ResamplePreviewState& state, float tolerance)
{
    if (state.SourceFrames.size() < 2)
        return false;

    std::vector<uint32> kept;
    Spline::SimplifyPolylineIndices(state.MeasurePositions, tolerance, kept);
    if (kept.size() < 2)
        return false;

    // Kept indices map 1:1 onto the captured frames, so the rebuilt points
    // take their positions AND channels from the same interpolated sample.
    std::vector<Spline::SplineFrame> keptFrames;
    keptFrames.reserve(kept.size());
    for (uint32 index : kept)
        keptFrames.push_back(state.SourceFrames[index]);

    data.ReplacePointsFromFrames(keptFrames);
    return true;
}

} // namespace

void RegisterSplineInspectors()
{
    using namespace Components;
    using namespace InspectorDrag;

    InspectorRegistry::Get().RegisterComponentInspector<SplineComponent>(
        [](const InspectorContext& ctx)
        {
            auto* comp = ctx.World->GetComponent<SplineComponent>(ctx.Entity);
            if (!comp)
                return;

            ECS::World* w = ctx.World;
            ECS::EntityHandle e = ctx.Entity;
            Editor::EditorChangeNotifications* n = ctx.ChangeNotifications;
            Editor::UndoRedoService* undo = ctx.Undo;

            auto* splineService = SplineECS::SplineService::TryGet();
            if (splineService)
            {
                SplineECS::SplineHandle handle(comp->SplineDataIndex, comp->SplineDataGeneration);
                auto* data = splineService->GetSplineData(handle);
                if (data)
                {
                    std::optional<float32> computedWorldLength;
                    // A spline another feature owns as its shape (a mark-up's outline or line)
                    // shows no Spline Info: its owner's section gives its points and the length
                    // it measures.
                    const bool claimed = Editor::QuerySplineOwner(*ctx.World, ctx.Entity).Claimed;
                    if (data->TotalArcLength > 0.0f && !claimed)
                    {
                        // Arc lengths are entity-local; the author reads world
                        // metres — the units tile spacing and drape density use.
                        float32 worldLength = data->TotalArcLength;
                        if (const auto* xf =
                                ctx.World->GetComponent<Components::WorldTransform>(ctx.Entity))
                        {
                            const Mathematics::Matrix4x4 localToWorld =
                                Mathematics::Matrix4x4::FromColumnMajor(xf->matrix);
                            worldLength =
                                Editor::WorldCenterlineLength(data->TotalArcLength, localToWorld);
                        }
                        computedWorldLength = worldLength;
                    }

                    if (ctx.ShowInfoCards && !claimed)
                        AddSplineInfoCard(ctx.Parent, static_cast<uint32>(data->Points.size()),
                                          data->GetSegmentCount(), computedWorldLength);

                    // Spline type dropdown.
                    {
                        static const std::vector<Dropdown::Option> kTypeOptions = {
                            {"0", "Catmull-Rom"},
                            {"1", "Cubic Bezier"},
                            {"2", "Linear"},
                        };
                        int selectedIdx = static_cast<int>(data->Type);
                        auto* dd = InspectorUI::AddDropdownRow(ctx.Parent, "Type", kTypeOptions, selectedIdx,
                                                   "Spline interpolation method");
                        dd->SetOnValueChanged(
                            [splineService, handle, w, e, n, undo](const std::string& value)
                            {
                                int typeInt = 0;
                                try { typeInt = std::stoi(value); }
                                catch (...) { return; }

                                Editor::SplineUndo::CommitSplineDataOneShot(
                                    splineService, handle, w, e, n, undo, "Change Spline Type",
                                    [typeInt](GameEngine::Spline::SplineData* d) {
                                        d->Type = static_cast<GameEngine::Spline::SplineType>(typeInt);
                                    });

                                if (n)
                                {
                                    Editor::EditorChangeNotifications::ComponentChangedEvent rebuild{};
                                    rebuild.world = w;
                                    rebuild.entity = e;
                                    rebuild.componentType = ECS::GetComponentTypeId<Components::SplineComponent>();
                                    rebuild.kind = Editor::EditorChangeNotifications::ChangeKind::InspectorRebuild;
                                    n->NotifyComponentChanged(rebuild);
                                }
                            });
                    }

                    Toggle* closedToggle = AddToggleRow(
                        ctx.Parent, "Closed", data->Closed,
                        [splineService, handle, w, e, n, undo](bool v)
                        {
                            Editor::SplineUndo::CommitSplineDataOneShot(
                                splineService, handle, w, e, n, undo, "Change Spline Closed",
                                [v](GameEngine::Spline::SplineData* d) { d->Closed = v; });

                            // The hint below appears and disappears with the
                            // flag, so the section has to be rebuilt for it.
                            if (n)
                            {
                                Editor::EditorChangeNotifications::ComponentChangedEvent rebuild{};
                                rebuild.world = w;
                                rebuild.entity = e;
                                rebuild.componentType =
                                    ECS::GetComponentTypeId<Components::SplineComponent>();
                                rebuild.kind =
                                    Editor::EditorChangeNotifications::ChangeKind::InspectorRebuild;
                                n->NotifyComponentChanged(rebuild);
                            }
                        },
                        "Loop the spline back to the first point");
                    // A spline another feature owns as its shape (a mark-up's outline or line)
                    // stays as its owner made it, and the row says why in the owner's words.
                    if (const Editor::SplineOwnerClaim claim = Editor::QuerySplineOwner(*w, e); claim.Claimed)
                        InspectorUI::DisableRowOfControl(closedToggle, claim.ClosedRowTooltip);

                    // The flag is authored truth and stays exactly as ticked;
                    // geometry follows IsEffectivelyClosed(). Say which one is
                    // in force, so a loop that draws as a line reads as a
                    // stated rule rather than a lost setting.
                    if (data->Closed && !data->IsEffectivelyClosed())
                    {
                        ctx.Parent->AddChild(std::make_unique<EditorUI::InspectorNotice>(
                            "A loop needs 3+ points - generating as an open line until then. "
                            "The Closed setting is kept and the loop returns when you add a point."));
                    }

                    // ---- Resample section ----
                    {
                        auto previewState = std::make_shared<ResamplePreviewState>();
                        auto applyRealtimeResample =
                            [splineService, handle, w, e, n, undo, previewState](float v, bool commit)
                            {
                                if (!splineService)
                                    return;

                                auto* d = splineService->GetSplineData(handle);
                                if (!d || !d->IsValid())
                                    return;

                                if (previewState->SourceFrames.empty() &&
                                    !CaptureResampleSource(*d, w, e, *previewState))
                                {
                                    return;
                                }

                                const float tolerance = std::max(0.01f, v);

                                if (!previewState->Edit.has_value() && undo)
                                {
                                    UndoRedoService::InteractiveEdit edit =
                                        undo->BeginInteractiveEdit(
                                            "Resample Spline",
                                            MakeSplineEditableSnapshotTarget(
                                                splineService, handle, w, e, n, "Resample Spline"));
                                    if (edit)
                                        previewState->Edit.emplace(std::move(edit));
                                }

                                if (!ApplyResampleFromSource(*d, *previewState, tolerance))
                                    return;

                                splineService->RebuildCache(handle);

                                bool compoundOpen = false;
                                if (previewState->Edit.has_value() && static_cast<bool>(previewState->Edit.value()))
                                {
                                    if (commit)
                                    {
                                        undo->BeginCompound("Resample Spline");
                                        compoundOpen = true;
                                        previewState->Edit.value().Commit();
                                        previewState->Edit.reset();

                                        if (n)
                                        {
                                            using CCE = Editor::EditorChangeNotifications::ComponentChangedEvent;
                                            CCE rebuildEvent{};
                                            rebuildEvent.world = w;
                                            rebuildEvent.entity = e;
                                            rebuildEvent.componentType = ECS::GetComponentTypeId<Components::SplineComponent>();
                                            rebuildEvent.kind = Editor::EditorChangeNotifications::ChangeKind::InspectorRebuild;
                                            n->NotifyComponentChanged(rebuildEvent);
                                        }
                                    }
                                    else
                                    {
                                        previewState->Edit.value().Preview([splineService, handle]() {
                                            splineService->RebuildCache(handle);
                                        });
                                    }
                                }
                                else if (n)
                                {
                                    n->NotifyComponentChange<Components::SplineComponent>(
                                        w, e, commit ? EditorChangeNotifications::ChangeKind::Commit
                                                     : EditorChangeNotifications::ChangeKind::Preview);
                                }

                                if (commit)
                                {
                                    // The points moved to new indices; the recipes addressed by
                                    // point follow them, in the resample's own undo step.
                                    std::vector<Mathematics::Vector3> after;
                                    after.reserve(d->Points.size());
                                    for (const Spline::SplineControlPoint& point : d->Points)
                                        after.push_back(point.Position);
                                    const Editor::SplinePointRenumbering renumbering =
                                        Editor::SplinePointRenumbering::Nearest(
                                            previewState->SourcePoints, after, d->IsEffectivelyClosed());
                                    Editor::SplinePointEdited().Invoke(
                                        {w, e, compoundOpen ? undo : nullptr, n, &renumbering});
                                    if (compoundOpen)
                                        undo->EndCompound();
                                    previewState->SourceFrames.clear();
                                    previewState->MeasurePositions.clear();
                                    previewState->SourcePoints.clear();
                                }
                            };

                        AddFloatRowWithDrag(
                            ctx.Parent, "Resample Tolerance", 0.25f,
                            [applyRealtimeResample](float v) { applyRealtimeResample(v, false); },
                            [applyRealtimeResample](float v) { applyRealtimeResample(v, true); },
                            0.25f,
                            "Douglas-Peucker simplification tolerance (world units). "
                            "Changing this resamples the spline immediately.",
                            0.01f, 8.0f);
                    }

                    const uint32 pointCount = static_cast<uint32>(data->Points.size());
                    if (pointCount > 0)
                    {
                        auto pointFoldouts = std::make_shared<std::vector<Foldout*>>();
                        pointFoldouts->reserve(pointCount);
                        auto pointFields = std::make_shared<std::vector<SplinePointFieldRefs>>();
                        pointFields->resize(pointCount);
                        const int32 selectedPointOnBuild = GetSelectedSplineKnot(*w, e, pointCount);

                        {
                            UIElement* row = InspectorUI::AddRow(ctx.Parent);
                            InspectorUI::AddLabel(row, "Selected Point", "Step the active spline knot selection");
                            UIElement* fieldContainer = InspectorUI::AddFieldContainer(row);
                            fieldContainer->AddClass("spline-point-nav-field");

                            auto selectedLabel = std::make_unique<Label>();
                            selectedLabel->AddClass("inspector-label");
                            selectedLabel->AddClass("spline-point-nav-label");
                            selectedLabel->SetText(FormatSelectedSplineKnotLabel(selectedPointOnBuild, pointCount));
                            Label* selectedLabelRaw = selectedLabel.get();

                            auto prevButton = std::make_unique<Button>();
                            prevButton->SetText("<");
                            prevButton->AddClass("inspector-button");
                            prevButton->AddClass("small");
                            prevButton->AddClass("icon-button");
                            prevButton->AddClass("spline-point-nav-button");
                            prevButton->SetTooltip("Select previous spline point");
                            Button* prevButtonRaw = prevButton.get();

                            auto nextButton = std::make_unique<Button>();
                            nextButton->SetText(">");
                            nextButton->AddClass("inspector-button");
                            nextButton->AddClass("small");
                            nextButton->AddClass("icon-button");
                            nextButton->AddClass("spline-point-nav-button");
                            nextButton->SetTooltip("Select next spline point");
                            Button* nextButtonRaw = nextButton.get();

                            auto applySelection = [w, e, pointCount, selectedLabelRaw, pointFoldouts](int direction)
                            {
                                if (pointCount == 0)
                                    return;

                                int32 current = GetSelectedSplineKnot(*w, e, pointCount);
                                if (current < 0)
                                    current = direction < 0 ? 0 : -1;

                                int32 next = current + direction;
                                if (next < 0)
                                    next = static_cast<int32>(pointCount) - 1;
                                else if (next >= static_cast<int32>(pointCount))
                                    next = 0;

                                SelectSplineKnot(*w, e, static_cast<uint32>(next));
                                if (selectedLabelRaw)
                                    selectedLabelRaw->SetText(FormatSelectedSplineKnotLabel(next, pointCount));

                                for (uint32 i = 0; i < pointFoldouts->size(); ++i)
                                {
                                    if ((*pointFoldouts)[i])
                                        (*pointFoldouts)[i]->SetExpanded(i == static_cast<uint32>(next));
                                }
                            };

                            prevButtonRaw->RegisterEventHandler(kEventButtonClick, [applySelection](UIEvent&) { applySelection(-1); });
                            nextButtonRaw->RegisterEventHandler(kEventButtonClick, [applySelection](UIEvent&) { applySelection(1); });

                            fieldContainer->AddChild(std::move(prevButton));
                            fieldContainer->AddChild(std::move(nextButton));
                            fieldContainer->AddChild(std::move(selectedLabel));
                        }

                        auto foldout = std::make_unique<Foldout>();
                        foldout->SetTitle("Control Points (" + std::to_string(pointCount) + ")");
                        foldout->AddClass("rp-foldout");
                        foldout->AddClass("spline-control-points-foldout");
                        foldout->SetExpanded(selectedPointOnBuild >= 0);

                        auto* foldoutPtr = foldout.get();

                        for (uint32 i = 0; i < pointCount; ++i)
                        {
                            const auto& pt = data->Points[i];

                            auto ptFoldout = std::make_unique<Foldout>();
                            ptFoldout->SetTitle("Point " + std::to_string(i));
                            ptFoldout->AddClass("rp-foldout");
                            ptFoldout->AddClass("spline-control-point-foldout");
                            ptFoldout->SetExpanded(static_cast<int32>(i) == selectedPointOnBuild);
                            auto* ptFoldoutPtr = ptFoldout.get();
                            pointFoldouts->push_back(ptFoldoutPtr);

                            (*pointFields)[i].Location = AddSplineVector3RowWithUndo(
                                ptFoldoutPtr, "Location", pt.Position, splineService, handle,
                                w, e, n, undo,
                                std::string("Change Spline Point Location [") + std::to_string(i) + "]",
                                [i](GameEngine::Spline::SplineData* d, const Mathematics::Vector3& v)
                                {
                                    if (i >= d->Points.size())
                                        return;
                                    d->Points[i].Position = v;
                                },
                                pt.Position,
                                "Spline point location");

                            (*pointFields)[i].Rotation = AddSplineVector3RowWithUndo(
                                ptFoldoutPtr, "Rotation", pt.Rotation, splineService, handle,
                                w, e, n, undo,
                                std::string("Change Spline Point Rotation [") + std::to_string(i) + "]",
                                [i](GameEngine::Spline::SplineData* d, const Mathematics::Vector3& v)
                                {
                                    if (i >= d->Points.size())
                                        return;
                                    d->Points[i].Rotation = v;
                                },
                                Mathematics::Vector3(0.0f, 0.0f, 0.0f),
                                "Spline point authored Euler rotation in degrees");

                            (*pointFields)[i].Scale = AddSplineVector3RowWithUndo(
                                ptFoldoutPtr, "Scale", pt.Scale, splineService, handle,
                                w, e, n, undo,
                                std::string("Change Spline Point Scale [") + std::to_string(i) + "]",
                                [i](GameEngine::Spline::SplineData* d, const Mathematics::Vector3& v)
                                {
                                    if (i >= d->Points.size())
                                        return;
                                    d->Points[i].Scale = v;
                                },
                                Mathematics::Vector3(1.0f, 1.0f, 1.0f),
                                "Spline point authored XYZ scale");

                            if (data->Type == Spline::SplineType::CubicBezier)
                            {
                                (*pointFields)[i].TangentIn = AddSplineVector3RowWithUndo(
                                    ptFoldoutPtr, "Arrive Tangent", pt.TangentIn, splineService, handle,
                                    w, e, n, undo,
                                    std::string("Change Spline Point Arrive Tangent [") + std::to_string(i) + "]",
                                    [i](GameEngine::Spline::SplineData* d, const Mathematics::Vector3& v)
                                    {
                                        if (i >= d->Points.size())
                                            return;
                                        d->Points[i].TangentIn = v;
                                    },
                                    Mathematics::Vector3(0.0f, 0.0f, 0.0f),
                                    "Incoming Bezier tangent offset");

                                (*pointFields)[i].TangentOut = AddSplineVector3RowWithUndo(
                                    ptFoldoutPtr, "Leave Tangent", pt.TangentOut, splineService, handle,
                                    w, e, n, undo,
                                    std::string("Change Spline Point Leave Tangent [") + std::to_string(i) + "]",
                                    [i](GameEngine::Spline::SplineData* d, const Mathematics::Vector3& v)
                                    {
                                        if (i >= d->Points.size())
                                            return;
                                        d->Points[i].TangentOut = v;
                                    },
                                    Mathematics::Vector3(0.0f, 0.0f, 0.0f),
                                    "Outgoing Bezier tangent offset");
                            }

                            (*pointFields)[i].Radius =
                                AddSplineFloatRowWithUndo(ptFoldoutPtr, "Radius", pt.Radius, splineService, handle,
                                                          w, e, n, undo,
                                                          std::string("Change Spline Point Radius [") + std::to_string(i) + "]",
                                                          [i](GameEngine::Spline::SplineData* d, float v)
                                                          {
                                                              if (i >= d->Points.size())
                                                                  return;
                                                              d->Points[i].Radius = std::max(0.1f, v);
                                                          },
                                                          pt.Radius, nullptr);

                            (*pointFields)[i].Roll =
                                AddSplineFloatRowWithUndo(ptFoldoutPtr, "Roll", pt.Roll, splineService, handle,
                                                          w, e, n, undo,
                                                          std::string("Change Spline Point Roll [") + std::to_string(i) + "]",
                                                          [i](GameEngine::Spline::SplineData* d, float v)
                                                          {
                                                              if (i >= d->Points.size())
                                                                  return;
                                                              d->Points[i].Roll = v;
                                                          },
                                                          0.0f,
                                                          "Bank angle in radians around the spline forward axis");

                            {
                                UIElement* deleteRow = InspectorUI::AddRow(ptFoldoutPtr);
                                InspectorUI::AddLabel(deleteRow, "Remove", "Erase this control point from the spline");
                                UIElement* deleteField = InspectorUI::AddFieldContainer(deleteRow);

                                auto deleteButton = std::make_unique<Button>();
                                deleteButton->SetText("Delete Point");
                                deleteButton->AddClass("inspector-button");
                                deleteButton->AddClass("small");
                                deleteButton->AddClass("spline-point-delete-button");

                                // At the floor there is nothing to delete down to:
                                // say so on the button rather than failing on click.
                                const bool atFloor =
                                    data->Points.size() <= Spline::SplineData::kMinPointCount;
                                deleteButton->SetDisabled(atFloor);
                                deleteButton->SetTooltip(
                                    atFloor ? "A spline keeps at least two points - delete the entity instead"
                                            : "Delete this control point");

                                if (!atFloor)
                                {
                                    deleteButton->RegisterEventHandler(kEventButtonClick, [splineService, handle, w, e, n, undo, i](UIEvent&)
                                        {
                                            auto* d = splineService ? splineService->GetSplineData(handle) : nullptr;
                                            if (!d || i >= d->Points.size() ||
                                                d->Points.size() <= Spline::SplineData::kMinPointCount)
                                            {
                                                return;
                                            }

                                            DeleteSplinePoint(splineService, handle, w, e, n, undo, i);

                                            // Keep the author on a real point: the one that
                                            // took this index, or the new last point.
                                            const auto* updated = splineService->GetSplineData(handle);
                                            const uint32 remaining =
                                                updated ? static_cast<uint32>(updated->Points.size()) : 0u;
                                            if (remaining > 0u)
                                                SelectSplineKnot(*w, e, std::min(i, remaining - 1u));

                                            // The row count changed, so the section is rebuilt
                                            // rather than refreshed in place.
                                            if (n)
                                            {
                                                Editor::EditorChangeNotifications::ComponentChangedEvent rebuild{};
                                                rebuild.world = w;
                                                rebuild.entity = e;
                                                rebuild.componentType =
                                                    ECS::GetComponentTypeId<Components::SplineComponent>();
                                                rebuild.kind =
                                                    Editor::EditorChangeNotifications::ChangeKind::InspectorRebuild;
                                                n->NotifyComponentChanged(rebuild);
                                            }
                                        });
                                }

                                deleteField->AddChild(std::move(deleteButton));
                            }

                            foldoutPtr->AddChild(std::move(ptFoldout));
                        }

                        foldoutPtr->SetOnExpandedChanged(
                            [pointFoldouts](Foldout&, bool expanded)
                            {
                                if (!expanded)
                                    return;

                                for (Foldout* ptFoldout : *pointFoldouts)
                                {
                                    if (ptFoldout)
                                        ptFoldout->SetExpanded(true);
                                }
                            });

                        ctx.Parent->AddChild(std::move(foldout));
                        ctx.Parent->AddChild(std::make_unique<SplineInspectorLiveRefresh>(
                            n, w, e, splineService, handle, pointFields));
                    }
                }
                else
                {
                    InspectorUI::AddLine(ctx.Parent, "(No spline data)");
                }
            }

            AddComponentFloatRowWithDrag<SplineComponent>(
                ctx.Parent,
                "Default Radius",
                comp->DefaultRadius,
                w,
                e,
                n,
                undo,
                "Change Spline Default Radius",
                [](SplineComponent& u, float v)
                {
                    u.DefaultRadius = std::max(0.1f, v);
                },
                comp->DefaultRadius,
                "Width/radius for newly added control points");
        });
}

} // namespace GameEngine
