#include "NativeScripting/UserProjectGenerator.h"

#include "AssetCore/AssetIgnoreRules.h"
#include "Logger/Logger.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace GameEngine
{
namespace NativeScripting
{

namespace
{
// CMake list entries are quoted; backslashes in Windows paths must be forward
// slashes (or escaped) for CMake. generic_string() already yields forward slashes.
std::string CMakePath(const std::filesystem::path& p)
{
    return p.generic_string();
}

// A CMake list literal ("a;b;c"); the caller quotes it.
std::string CMakeList(const std::vector<std::string>& values)
{
    std::string joined;
    for (const std::string& value : values)
    {
        if (!joined.empty())
            joined += ';';
        joined += value;
    }
    return joined;
}

// Sorted so the generated file depends on the rules and not on the iteration
// order of the set they live in — an unstable list would reconfigure CMake on
// every generate.
std::vector<std::string> SortedIgnoredDirectoryNames(const AssetIgnoreRules& rules)
{
    std::vector<std::string> names(rules.ignoredDirNamesLower.begin(),
                                   rules.ignoredDirNamesLower.end());
    std::sort(names.begin(), names.end());
    return names;
}

// First line of every file this generator writes. Stray cleanup keys on this
// prefix so it can prove a CMakeLists.txt is ours before deleting it — a
// user-authored file never matches.
constexpr std::string_view kGeneratedByMarker =
    "# AUTO-GENERATED by NativeScripting UserProjectGenerator";

// Lexical "is `p` under `base`": the forward-slash remainder, or empty when it is
// not. Case-insensitive on Windows. Lexical on purpose — both paths are built by
// appending to the same configured roots, and Generate may run before they exist.
std::string RelativeUnder(const std::filesystem::path& p, const std::filesystem::path& base)
{
    if (base.empty())
        return {};
    const std::string pStr = p.lexically_normal().generic_string();
    std::string baseStr = base.lexically_normal().generic_string();
    if (baseStr.empty())
        return {};
    if (baseStr.back() != '/')
        baseStr += '/';
    if (pStr.size() <= baseStr.size())
        return {};
#if defined(_WIN32)
    const auto sameChar = [](char a, char b) {
        return std::tolower(static_cast<unsigned char>(a)) == std::tolower(static_cast<unsigned char>(b));
    };
    if (!std::equal(baseStr.begin(), baseStr.end(), pStr.begin(), sameChar))
        return {};
#else
    if (pStr.compare(0, baseStr.size(), baseStr) != 0)
        return {};
#endif
    return pStr.substr(baseStr.size());
}

// The baked last-known-good SDK root in a previously generated file (the
// `set(GAMEENGINE_SDK_DIR "...")` default), or empty when the file has none.
std::string ExtractBakedSdkDefault(const std::string& content)
{
    constexpr std::string_view kKey = "set(GAMEENGINE_SDK_DIR \"";
    const std::size_t start = content.find(kKey);
    if (start == std::string::npos)
        return {};
    const std::size_t valueStart = start + kKey.size();
    const std::size_t valueEnd = content.find('"', valueStart);
    if (valueEnd == std::string::npos)
        return {};
    return content.substr(valueStart, valueEnd - valueStart);
}
} // namespace

std::string UserProjectGenerator::BuildCMakeListsContent(const NativeBuildConfig& config)
{
    // Engine paths are emitted through the GAMEENGINE_SDK_DIR variable whenever they
    // live under the SDK root, so the persisted file follows the live SDK instead of
    // baking this machine's install location (#370). Out-of-SDK paths (e.g. the
    // integration test's engine-build-tree interface) stay absolute.
    const auto sdkPath = [&config](const std::filesystem::path& p) -> std::string {
        const std::string rel = RelativeUnder(p, config.SdkRoot);
        return rel.empty() ? CMakePath(p) : ("${GAMEENGINE_SDK_DIR}/" + rel);
    };

    const std::filesystem::path projectDir = EffectiveProjectDir(config);
    const bool projectContainsSources =
        projectDir.lexically_normal() == config.SourceDir.lexically_normal();
    const std::string sourceDirRef =
        projectContainsSources ? "${CMAKE_CURRENT_SOURCE_DIR}" : CMakePath(config.SourceDir);

    // Scanner outputs (<BuildDir>/*.gen.cpp) are referenced relative to the generated
    // CMake project when the build dir sits beside it, so the cache can move as a unit.
    std::string genDirRef = CMakePath(config.BuildDir);
    if (const std::string relFromProject = RelativeUnder(config.BuildDir, projectDir.parent_path());
        !relFromProject.empty())
        genDirRef = "${CMAKE_CURRENT_SOURCE_DIR}/../" + relFromProject;

    std::ostringstream out;
    out << kGeneratedByMarker << " — do not edit.\n";
    out << "# Standalone build of a native user-script module DLL against the engine.\n";
    out << "cmake_minimum_required(VERSION 3.20)\n";

    if (!config.SdkRoot.empty())
    {
        out << "\n";
        out << "# Engine SDK root. Engine-driven builds pass -DGAMEENGINE_SDK_DIR=<live SDK> on\n";
        out << "# every configure; the baked default below is only a last-known-good for IDE /\n";
        out << "# manual configures, refreshed whenever the engine regenerates this file.\n";
        out << "if(NOT DEFINED GAMEENGINE_SDK_DIR)\n";
        out << "    set(GAMEENGINE_SDK_DIR \"" << CMakePath(config.SdkRoot) << "\")\n";
        out << "endif()\n";
        out << "if(NOT IS_DIRECTORY \"${GAMEENGINE_SDK_DIR}\")\n";
        out << "    message(FATAL_ERROR \"GameEngine SDK not found at '${GAMEENGINE_SDK_DIR}'. "
               "The Editor/SDK moved or was deleted since this file was generated. "
               "Reopen the project in the Open Engine Editor to refresh it, or configure with "
               "-DGAMEENGINE_SDK_DIR=<Editor dir>/SDK.\")\n";
        out << "endif()\n";
    }

    out << "\n";
    out << "project(" << config.ModuleName << " LANGUAGES CXX C)\n\n";
    out << "set(CMAKE_CXX_STANDARD 20)\n";
    out << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n";

    // A user module MUST build in the host engine's configuration, and DebugFast is a
    // config the engine adds that CMake does not know. Multi-config generators (Visual
    // Studio, Xcode) fix their configuration list at project() time and reject
    // `cmake --build --config DebugFast` outright (MSB8013) before compiling anything,
    // so the generated project has to declare it exactly as the engine's root
    // CMakeLists does. Single-config generators (Ninja) leave CMAKE_CONFIGURATION_TYPES
    // empty and take CMAKE_BUILD_TYPE instead; the guard below skips them, while the
    // flag seeding applies to both.
    out << "# DebugFast: the engine's daily-driver config. Declared here so an engine-driven\n";
    out << "# build in that config is accepted by multi-config generators, and so an IDE that\n";
    out << "# opens this project offers the same configuration the engine ships.\n";
    out << "if(CMAKE_CONFIGURATION_TYPES AND NOT \"DebugFast\" IN_LIST CMAKE_CONFIGURATION_TYPES)\n";
    out << "    list(APPEND CMAKE_CONFIGURATION_TYPES DebugFast)\n";
    out << "    set(CMAKE_CONFIGURATION_TYPES \"${CMAKE_CONFIGURATION_TYPES}\"\n";
    out << "        CACHE STRING \"Configurations\" FORCE)\n";
    out << "endif()\n";
    // Declaring the config is not enough: an undeclared config compiles with NO per-config
    // flags at all. Seed them from Debug minus /RTC1 — the engine's own DebugFast recipe.
    // The release CRT comes from CMAKE_MSVC_RUNTIME_LIBRARY's default $<CONFIG:Debug> test
    // (CMP0091 NEW via cmake_minimum_required above), which resolves DebugFast to /MD and
    // therefore matches the engine DLL this module links against.
    //
    // FORCE, guarded on emptiness: with a single-config generator CMake pre-creates an EMPTY
    // cache entry for the active build type, so a plain set(... CACHE ...) is silently a
    // no-op there and the flags never arrive. The emptiness guard keeps an explicitly
    // supplied -DCMAKE_<LANG>_FLAGS_DEBUGFAST intact.
    out << "foreach(_ge_flag CMAKE_C_FLAGS_DEBUGFAST CMAKE_CXX_FLAGS_DEBUGFAST\n";
    out << "                 CMAKE_EXE_LINKER_FLAGS_DEBUGFAST CMAKE_SHARED_LINKER_FLAGS_DEBUGFAST\n";
    out << "                 CMAKE_STATIC_LINKER_FLAGS_DEBUGFAST CMAKE_MODULE_LINKER_FLAGS_DEBUGFAST)\n";
    out << "    if(NOT ${_ge_flag})\n";
    out << "        string(REPLACE \"_DEBUGFAST\" \"_DEBUG\" _ge_seed_var \"${_ge_flag}\")\n";
    // /RTC1 is the runtime-check overhead DebugFast drops; a no-op where it is absent.
    out << "        string(REPLACE \"/RTC1\" \"\" _ge_seed \"${${_ge_seed_var}}\")\n";
    out << "        set(${_ge_flag} \"${_ge_seed}\" CACHE STRING \"DebugFast build flags\" FORCE)\n";
    out << "    endif()\n";
    out << "endforeach()\n\n";

    out << "set(GAMEENGINE_USER_SOURCE_DIR \"" << sourceDirRef << "\")\n\n";

    // All user sources under the project dir, plus the SDK entry source (the four
    // ABI exports) compiled in from outside the project tree.
    // C/C++ translation units: .cpp/.cc/.cxx compile as C++, .c as C (the project enables both
    // languages above), so users can mix a C source in with their C++ scripts.
    out << "file(GLOB_RECURSE _user_sources CONFIGURE_DEPENDS"
           " \"${GAMEENGINE_USER_SOURCE_DIR}/*.cpp\" \"${GAMEENGINE_USER_SOURCE_DIR}/*.cc\""
           " \"${GAMEENGINE_USER_SOURCE_DIR}/*.cxx\" \"${GAMEENGINE_USER_SOURCE_DIR}/*.c\")\n";
    // Drop the build output and tool trees that can sit under the source dir. Opening the project
    // folder in an IDE (e.g. Visual Studio's CMake "Open Folder") writes a build tree into out/ and
    // .vs/, and globbing its generated CMakeFiles/CMakeCXXCompilerId.cpp (which defines main +
    // info_*) would multiply-define symbols and break the link; a package whose sources sit at its
    // root builds into a .Cache inside that root, so its own generated TUs are in the glob too.
    // The directory rules are the asset ignore rules for this source root — names, name prefixes
    // and root-relative path prefixes, including the root's own .assetignore — the same rules the
    // staleness digest walks with, so what compiles and what invalidates the build cache cannot
    // disagree on a directory. File-level rules (ignored file names and extensions) are not
    // mirrored: the glob above is the compile's own statement of which files are sources. A
    // package module also skips its package's top-level Tests folder.
    AssetIgnoreRules ignoreRules = AssetIgnoreRules::LoadForAssetRoot(config.SourceDir);
    ignoreRules.IgnorePackageTestsFolder(config.SourceDir, config.PackageRootDir);
    out << "set(_ge_ignored_dirs \"" << CMakeList(SortedIgnoredDirectoryNames(ignoreRules)) << "\")\n";
    out << "set(_ge_ignored_dir_prefixes \"" << CMakeList(ignoreRules.ignoredDirNamePrefixesLower)
        << "\")\n";
    out << "set(_ge_ignored_path_prefixes \"" << CMakeList(ignoreRules.ignoredPrefixesLower) << "\")\n";
    // Matched on the lower-cased path relative to the source dir: case-insensitively, so ".Cache"
    // and ".cache" both drop out, and blind to the directories above the source dir, whose names
    // are not this project's business.
    out << "set(_ge_kept_sources \"\")\n";
    out << "foreach(_ge_source IN LISTS _user_sources)\n";
    out << "    file(RELATIVE_PATH _ge_relative \"${GAMEENGINE_USER_SOURCE_DIR}\" \"${_ge_source}\")\n";
    out << "    string(TOLOWER \"/${_ge_relative}\" _ge_relative_lower)\n";
    out << "    set(_ge_keep TRUE)\n";
    out << "    foreach(_ge_ignored_dir IN LISTS _ge_ignored_dirs)\n";
    out << "        string(FIND \"${_ge_relative_lower}\" \"/${_ge_ignored_dir}/\" _ge_match)\n";
    out << "        if(NOT _ge_match EQUAL -1)\n";
    out << "            set(_ge_keep FALSE)\n";
    out << "            break()\n";
    out << "        endif()\n";
    out << "    endforeach()\n";
    out << "    foreach(_ge_ignored_prefix IN LISTS _ge_ignored_dir_prefixes)\n";
    out << "        if(_ge_relative_lower MATCHES \"/${_ge_ignored_prefix}[^/]*/\")\n";
    out << "            set(_ge_keep FALSE)\n";
    out << "            break()\n";
    out << "        endif()\n";
    out << "    endforeach()\n";
    // Path prefixes are stored root-relative with a trailing '/', so a match is exact at offset 0.
    out << "    foreach(_ge_ignored_path_prefix IN LISTS _ge_ignored_path_prefixes)\n";
    out << "        string(FIND \"${_ge_relative_lower}\" \"/${_ge_ignored_path_prefix}\" _ge_match)\n";
    out << "        if(_ge_match EQUAL 0)\n";
    out << "            set(_ge_keep FALSE)\n";
    out << "            break()\n";
    out << "        endif()\n";
    out << "    endforeach()\n";
    out << "    if(_ge_keep)\n";
    out << "        list(APPEND _ge_kept_sources \"${_ge_source}\")\n";
    out << "    endif()\n";
    out << "endforeach()\n";
    out << "set(_user_sources ${_ge_kept_sources})\n";
    // Some projects carry standalone app/player sources under Assets/Source for
    // packaging or experiments. Those are not hot-reload scripts and often
    // define main() or depend on private app APIs, so keep them out of the user DLL.
    out << "list(FILTER _user_sources EXCLUDE REGEX \"/Source/(main|PlayerApplication)\\\\.(cpp|cc|cxx|c)$\")\n";
    // .c sources compile as C, so they must skip the C++/STL precompiled header set up below.
    out << "set(_c_sources ${_user_sources})\n";
    out << "list(FILTER _c_sources INCLUDE REGEX \"\\.c$\")\n";
    out << "if(_c_sources)\n";
    out << "    set_source_files_properties(${_c_sources} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)\n";
    out << "endif()\n";
    // Scanner-generated registration TUs (auto-detected ECS components/systems) land in
    // the user project's build dir as *.gen.cpp. Globbed rather than listed so the
    // content here does not vary with scanner availability, and CONFIGURE_DEPENDS
    // re-runs the configure when a generated TU appears or disappears.
    out << "file(GLOB _generated_sources CONFIGURE_DEPENDS \"" << genDirRef << "/*.gen.cpp\")\n";
    out << "add_library(" << config.ModuleName << " SHARED ${_user_sources} ${_generated_sources}\n";
    out << "    \"" << sdkPath(config.SdkEntrySource) << "\")\n\n";

    // Land the DLL in a predictable per-config-independent location so the loader
    // can find it without guessing the generator's config-subdir layout.
    out << "set_target_properties(" << config.ModuleName << " PROPERTIES\n";
    out << "    RUNTIME_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/out\")\n";
    out << "foreach(_cfg DEBUG DEBUGFAST RELEASE RELWITHDEBINFO MINSIZEREL)\n";
    out << "    set_target_properties(" << config.ModuleName << " PROPERTIES\n";
    out << "        RUNTIME_OUTPUT_DIRECTORY_${_cfg} \"${CMAKE_BINARY_DIR}/out\")\n";
    out << "endforeach()\n\n";

    // User scripts stay debuggable on every engine config: the daily-driver engine
    // presets (DebugFast/Release) map to a "Release" user build, whose CMake defaults
    // emit no debug info — crashes in user code would resolve to name-only frames.
    // Add RelWithDebInfo-style symbols to every non-Debug config (Debug already has
    // them); the PDB lands next to the DLL in out/, where the loaded (shadow-copied)
    // module's embedded absolute PDB path keeps pointing.
    out << "if(MSVC)\n";
    out << "    target_compile_options(" << config.ModuleName
        << " PRIVATE $<$<NOT:$<CONFIG:Debug>>:/Zi> $<$<NOT:$<CONFIG:Debug>>:/Zo>)\n";
    out << "    target_link_options(" << config.ModuleName
        << " PRIVATE $<$<NOT:$<CONFIG:Debug>>:/DEBUG>)\n";
    // /bigobj on every user TU. COFF caps an object file at 65,279 sections and emits one
    // per COMDAT -- every inline function, template instantiation and selectany datum in
    // every header the TU pulls in. The generated project force-includes the GameSDK
    // umbrella PCH into every user TU, which a user cannot opt out of, so the exposure is
    // partly engine-imposed. Measured on the worst TU in the package class: 86% of the cap
    // in Debug, 82% in Release -- Release above DebugFast, so no config is safe and scoping
    // by config would only leave a config where it still fails. Emitted as its own
    // unconditional statement rather than folded above, which would inherit that scope.
    // The flag widens a field in the object format: the linked DLL is byte-identical
    // (verified with fc /b) and the object grows 2.59%, exactly the symbol-record widening.
    // MSVC arm only, deliberately -- MinGW would want -Wa,-mbig-obj and adding that to the
    // else() arm would break Linux and macOS clang, where it is not a valid option.
    out << "    target_compile_options(" << config.ModuleName << " PRIVATE /bigobj)\n";
    out << "else()\n";
    out << "    target_compile_options(" << config.ModuleName
        << " PRIVATE $<$<NOT:$<CONFIG:Debug>>:-g>)\n";
    out << "endif()\n\n";

    out << "target_include_directories(" << config.ModuleName << " PRIVATE\n";
    // The user source dir itself, so user .cpp and the generated reflection TU can
    // include sibling user headers (e.g. #include \"Health.h\").
    out << "    \"${GAMEENGINE_USER_SOURCE_DIR}\"\n";
    for (const auto& dir : config.IncludeDirs)
        out << "    \"" << sdkPath(dir) << "\"\n";
    // Editor-kind modules additionally see the staged editor headers.
    for (const auto& dir : config.EditorIncludeDirs)
        out << "    \"" << sdkPath(dir) << "\"\n";
    out << ")\n\n";

    out << "target_link_libraries(" << config.ModuleName << " PRIVATE\n";
    out << "    \"" << sdkPath(config.EngineImportLib) << "\"";
    if (!config.EditorImportLib.empty())
        out << "\n    \"" << sdkPath(config.EditorImportLib) << "\"";
    out << ")\n\n";

    if (!config.CompileDefinitions.empty())
    {
        out << "target_compile_definitions(" << config.ModuleName << " PRIVATE\n";
        for (const auto& def : config.CompileDefinitions)
            out << "    " << def << "\n";
        out << ")\n\n";
    }

    // Precompile the SDK umbrella: the user TUs (the generated registration TU + the SDK
    // entry) #include the engine's heavy header surface (ECS / reflection / JobSystem /
    // vcpkg) to register a few small components. The PCH parses that surface ONCE and is
    // reused across rebuilds — the engine headers don't change between user-script edits —
    // so warm hot-reload rebuilds recompile only the small user code against the cached PCH.
    // The C++ TUs precompile the SDK umbrella; .c sources are excluded above (SKIP_PRECOMPILE_HEADERS).
    out << "target_precompile_headers(" << config.ModuleName << " PRIVATE \"<GameSDK/GameSDK.h>\")\n";

    return out.str();
}

std::filesystem::path UserProjectGenerator::Generate(const NativeBuildConfig& config,
                                                     bool& outChanged,
                                                     std::string& outError)
{
    outChanged = false;
    std::error_code ec;
    const std::filesystem::path projectDir = EffectiveProjectDir(config);
    std::filesystem::create_directories(projectDir, ec);
    if (ec)
    {
        outError = "cannot create generated project dir " + projectDir.string() + ": " + ec.message();
        return {};
    }

    // Engines before ProjectDir existed generated into the source root itself. For
    // package sources that root can be a signed macOS bundle (the leftover keeps the
    // code signature broken until it is removed — deleting it restores the signed
    // state) or a package working tree (commit noise). Only a marker-bearing stray
    // is ours to delete; a user-authored CMakeLists.txt never matches.
    if (!config.ProjectDir.empty() &&
        projectDir.lexically_normal() != config.SourceDir.lexically_normal())
    {
        const std::filesystem::path stray = config.SourceDir / "CMakeLists.txt";
        if (std::filesystem::exists(stray, ec))
        {
            std::string firstLine;
            {
                std::ifstream in(stray);
                std::getline(in, firstLine);
            }
            if (firstLine.compare(0, kGeneratedByMarker.size(), kGeneratedByMarker) == 0)
            {
                std::error_code removeEc;
                std::filesystem::remove(stray, removeEc);
                if (!removeEc)
                    Logger::Log::Info(
                        "[NativeScripting] removed stale generated CMakeLists.txt from package sources: {}",
                        stray.string());
            }
        }
        ec.clear();
    }

    const std::filesystem::path cmakeListsPath = projectDir / "CMakeLists.txt";
    const std::string newContent = BuildCMakeListsContent(config);

    // Non-throwing exists(): this can run on a JobSystem worker, where a thrown
    // filesystem_error would be swallowed by the pool and wedge the build pipeline.
    std::string existing;
    const bool cmakeListsExists = std::filesystem::exists(cmakeListsPath, ec);
    if (cmakeListsExists)
    {
        std::ifstream in(cmakeListsPath, std::ios::binary);
        existing.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    }

    if (existing == newContent && cmakeListsExists)
    {
        Logger::Log::Debug("[NativeScripting] user CMakeLists up to date: {}", cmakeListsPath.string());
        return cmakeListsPath; // outChanged stays false
    }

    // The previous file's baked last-known-good SDK root is what an IDE / manual
    // configure would have used; if that directory is gone, say so loudly — the
    // rewrite below is the fix, and the log names the cause.
    if (cmakeListsExists)
    {
        const std::string previousSdk = ExtractBakedSdkDefault(existing);
        std::error_code sdkEc;
        if (!previousSdk.empty() &&
            !std::filesystem::is_directory(std::filesystem::path(previousSdk), sdkEc))
        {
            Logger::Log::Error("[NativeScripting] stale SDK reference in {}: baked SDK dir '{}' no longer "
                               "exists (the Editor/SDK moved since generation). Regenerating against the "
                               "live engine interface at '{}'.",
                               cmakeListsPath.string(), previousSdk, config.SdkRoot.string());
        }
    }

    std::ofstream of(cmakeListsPath, std::ios::binary | std::ios::trunc);
    if (!of)
    {
        outError = "cannot write " + cmakeListsPath.string();
        return {};
    }
    of << newContent;
    of.close();
    outChanged = true;
    Logger::Log::Info("[NativeScripting] generated user CMakeLists: {}", cmakeListsPath.string());
    return cmakeListsPath;
}

} // namespace NativeScripting
} // namespace GameEngine
