#pragma once

#include <cstdint>
#include <functional>
#include <memory>
#include <string>

namespace GameEngine
{
namespace Platform
{
class Window;
}

// Cross-platform native menu/toolbar interface
class INativeToolbar
{
  public:
    using CommandCallback = std::function<void(uint32_t)>;
    virtual ~INativeToolbar() = default;

    // Attach to a platform window and create/show a native menu/toolbar
    virtual bool Install(Platform::Window* window) = 0;
    // Remove the menu and restore any hooks/resources
    virtual void Uninstall() = 0;

    // Remove all menus and rebuild the empty menu bar
    virtual void Clear() = 0;

    // Register a handler for command IDs generated by AddItem(...)
    virtual void SetCommandHandler(CommandCallback cb) = 0;

    // Menu building API (UTF-8 titles)
    // Returns menu IDs that can be used as parents for submenus/items
    virtual uint32_t AddMenu(const std::string& title) = 0;
    virtual uint32_t AddSubMenu(uint32_t parentMenuId, const std::string& title) = 0;
    virtual void AddItem(uint32_t parentMenuId, const std::string& title, uint32_t commandId) = 0;

    // Optional: assign an image to an existing command item. Paths use the
    // same asset aliases as native context-menu icons (for example editor:Icons/foo.png).
    virtual void SetItemIcon(uint32_t /*commandId*/, const std::string& /*imagePath*/) {}

    // Optional: update the title for an existing item identified by commandId.
    // Default implementation is a no-op so platforms that do not support
    // in-place relabeling can ignore this while still compiling.
    virtual void UpdateItemTitle(uint32_t /*commandId*/, const std::string& /*title*/) {}
};

// Factory: returns a platform-specific implementation (Win32, Cocoa, stub, ...)
std::unique_ptr<INativeToolbar> CreateNativeToolbar();

} // namespace GameEngine
