#pragma once

#include "Animation/HumanBone.h"
#include "AssetCore/Asset.h"
#include "AssetCore/GUID.h"
#include "Mathematics/Quaternion.h"
#include "Mathematics/Vector3.h"
#include "Types/Types.h"

#include <array>
#include <filesystem>
#include <string>
#include <vector>

namespace GameEngine
{
namespace Animation
{

// One source-rig bone -> canonical bone binding. CachedSourceIndex is a
// runtime acceleration; the source-of-truth is SourceBoneName. The cached
// index is rebuilt by the resolver when the rig is bound to a SkeletonData
// (or after a skeleton-data hot-reload). It is intentionally not required
// to round-trip through JSON.
struct HumanoidBoneMapping
{
    HumanBone Canonical = HumanBone::None;
    std::string SourceBoneName;
    uint32 CachedSourceIndex = ~0u;
    Mathematics::Quaternion RetargetPoseRotation; // identity by default
};

// Chain category. Drives chain solver selection and op-stack defaults.
enum class ChainKind : uint8
{
    LeftArm,
    RightArm,
    LeftLeg,
    RightLeg,
    Spine,
    Head,
    LeftFingers,
    RightFingers,
    Tail,
    Other
};

const char* ChainKindToString(ChainKind kind);
ChainKind ChainKindFromString(std::string_view name);

// One bone chain (Start -> End in canonical hierarchy). IncludeBones lists
// the bones traversed; FK transport and IK solvers iterate this list.
struct HumanoidChain
{
    ChainKind Kind = ChainKind::Other;
    HumanBone Start = HumanBone::None;
    HumanBone End = HumanBone::None;
    std::vector<HumanBone> IncludeBones;
};

// Body proportion summary, in the rig's local units. PerChainLengths is
// a parallel array sized to ChainKind::Other + 1; entries are zero for
// chains the rig does not have (e.g. tail).
struct BodyProportions
{
    float HipHeight = 0.0f;
    float ShoulderWidth = 0.0f;
    float LegLength = 0.0f;
    float ArmLength = 0.0f;
    std::array<float, 10> PerChainLengths = {};
};

// How an attachment bone is driven during retargeting.
enum class AttachmentPassthroughMode : uint8
{
    CopyLocal,   // Copy source local rotation; default for cosmetic bones.
    Procedural,  // Driven by a runtime op (cloak, hair, etc.).
    Static       // Hold local pose unchanged.
};

const char* AttachmentPassthroughModeToString(AttachmentPassthroughMode mode);
AttachmentPassthroughMode AttachmentPassthroughModeFromString(std::string_view name);

// Cosmetic / accessory bone that is not part of the canonical humanoid.
// LocalOffset is in the parent's local space.
struct AttachmentBone
{
    std::string Name;
    HumanBone ParentBone = HumanBone::None;
    Mathematics::Vector3 LocalOffset;
    AttachmentPassthroughMode Mode = AttachmentPassthroughMode::CopyLocal;
};

// HumanoidRig binds a specific source skeleton to a SkeletonProfile. It
// owns the canonical bone map, retarget pose deltas, chain definitions,
// body proportions, and attachment bones.
class HumanoidRig : public ::GameEngine::Asset
{
  public:
    static constexpr int32 kSchemaVersion = 1;

    HumanoidRig(const ::GameEngine::GUID& guid, const std::filesystem::path& path)
        : ::GameEngine::Asset(guid, ::GameEngine::AssetType::HumanoidRig, path) {}

    bool Load() override;
    bool LoadFromData(const Vector<uint8>& data) override;
    void Unload() override;

    bool SaveToData(Vector<uint8>& outData) const;
    bool SaveToPath(const std::filesystem::path& path) const;

    int32 Version() const { return m_Version; }

    const ::GameEngine::GUID& ProfileRef() const { return m_ProfileRef; }
    void SetProfileRef(const ::GameEngine::GUID& guid) { m_ProfileRef = guid; }

    const std::vector<HumanoidBoneMapping>& BoneMap() const { return m_BoneMap; }
    std::vector<HumanoidBoneMapping>& BoneMapMutable() { return m_BoneMap; }

    const std::vector<HumanoidChain>& Chains() const { return m_Chains; }
    std::vector<HumanoidChain>& ChainsMutable() { return m_Chains; }

    const std::vector<HumanBone>& TranslationBones() const { return m_TranslationBones; }
    std::vector<HumanBone>& TranslationBonesMutable() { return m_TranslationBones; }

    const BodyProportions& Proportions() const { return m_Proportions; }
    BodyProportions& ProportionsMutable() { return m_Proportions; }

    const std::vector<AttachmentBone>& Attachments() const { return m_Attachments; }
    std::vector<AttachmentBone>& AttachmentsMutable() { return m_Attachments; }

    // True when the rig was synthesized by AutoImportHumanoidRig and saved
    // as a sidecar by ModelAsset::PostLoad. ModelAsset uses this to decide
    // whether it can safely overwrite the sidecar on subsequent loads:
    // auto = true means the sidecar was machine-generated and can be
    // refreshed; auto = false means the user (or editor inspector) saved
    // their own edits and the sidecar must not be clobbered.
    bool AutoGenerated() const { return m_AutoGenerated; }
    void SetAutoGenerated(bool value) { m_AutoGenerated = value; }

  private:
    bool ParseJson(const std::string& text);
    std::string SerializeJson() const;

    int32 m_Version = 0;
    ::GameEngine::GUID m_ProfileRef; // null by default
    std::vector<HumanoidBoneMapping> m_BoneMap;
    std::vector<HumanoidChain> m_Chains;
    std::vector<HumanBone> m_TranslationBones { HumanBone::Hips };
    BodyProportions m_Proportions;
    std::vector<AttachmentBone> m_Attachments;
    bool m_AutoGenerated = false;
};

} // namespace Animation
} // namespace GameEngine
