"""Add WGSL chunks to the engine's built-in .shaderpkg set for a web export.

The engine's built-in passes (tonemap, the depth compute chain, clustered light
culling, the shadow and sky packages) ship as .shaderpkg files holding SPIR-V
plus reflection metadata. A browser ingests no SPIR-V, so for each package this
cooks the same GLSL stage sources through Tools/ShaderCook
(glslc vulkan1.1 -> spirv-opt split -> naga -> tint) and writes a copy with a
"<stage>-wgsl" chunk appended. Reflection metadata is generated by the engine's host ShaderReflect tool from
the same compatibility-profile GLSL, before push-constant lowering, and the same
tool writes and reads every package: nothing here parses the container. Native and
compatibility shaders can declare different storage formats and binding sets;
their packages must carry the matching metadata.

Not every built-in ships as a package. The UI SDF renderer and the editor's
overlays load bare stage bytecode through Utils::LoadShaderFile, building their
descriptor layouts in C++ rather than from reflection metadata; those cook to
plain .wgsl files beside the packages, and the emscripten arm of
LoadShaderFile prefers the .wgsl sibling of the .spv name it was asked for.

Material variants are a different path again: those come from
MaterialVariantCook, which composes per-material source. This module owns only
the fixed built-in set, whose stage sources are listed below because nothing at
runtime knows the mapping from package name back to .vert/.frag/.comp.

    python3 Tools/Web/builtin_shader_cook.py --editor \\
        --shaderpkg-dir build/macos-arm64-ninja/Shaders --out /tmp/webeditor-shaders
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path

kRepoRoot = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(kRepoRoot / "Tools" / "ShaderCook"))
import shadercook  # noqa: E402

# Package -> {pkg stage key: GLSL source}. Mirrors the _ge_add_shaderpkg_*
# calls in Engine/Modules/Rendering/CMakeLists.txt for the packages a web
# Player's frame requests. A package outside this set has no WGSL, and the
# runtime names it as missing rather than drawing without it.
kPackages: dict[str, dict[str, str]] = {
    "encode_srgb": {"vs": "fullscreen_noinput.vert", "fs": "encode_srgb.frag"},
    "tonemap": {"vs": "fullscreen_noinput.vert", "fs": "tonemap.frag"},
    "copy": {"vs": "fullscreen_noinput.vert", "fs": "copy.frag"},
    "solidcolor": {"vs": "fullscreen_noinput.vert", "fs": "solidcolor.frag"},
    "forwardplus_lighting": {"vs": "fullscreen_noinput.vert", "fs": "forwardplus_lighting.frag"},
    "clustered_light_cull": {"cs": "clustered_light_cull.comp"},
    "cluster_depth_minmax": {"cs": "cluster_depth_minmax.comp"},
    "sky_render": {"vs": "fullscreen_noinput.vert", "fs": "sky_render.frag"},
    "sky_stars_billboard": {"vs": "sky_stars_billboard.vert", "fs": "sky_stars_billboard.frag"},
    "sky_transmittance_lut": {"cs": "sky_transmittance_lut.comp"},
    "sky_multiscatter_lut": {"cs": "sky_multiscatter_lut.comp"},
    "sky_view_lut": {"cs": "sky_view_lut.comp"},
    "depth_resolve": {"cs": "depth_resolve.comp"},
    "depth_copy": {"cs": "depth_copy.comp"},
    # The late transparents' single-sample depth under MSAA (WebGPU runs 4x): sample 0 of the view depth.
    "depth_copy_sample0": {"vs": "fullscreen_noinput.vert", "fs": "depth_copy_sample0.frag"},
    "depth_reduce": {"cs": "depth_reduce.comp"},
    "depth_reduce_ms": {"cs": "depth_reduce_ms.comp"},
    # Web.rendergraph's SSSR path (HZBBuild + ScreenSpaceReflections). These
    # used to live only in the Editor cook set, so a player dist that ran that
    # graph loaded no packages, left HDRSSSR unwritten, and tonemapped black.
    "hzb_build": {"cs": "hzb_build.comp"},
    "sssr_classify": {"cs": "ScreenSpaceReflections/sssr_classify.comp"},
    "sssr_composite": {"cs": "ScreenSpaceReflections/sssr_composite.comp"},
    "sssr_intersect": {"cs": "ScreenSpaceReflections/sssr_intersect.comp"},
    "sssr_prefilter": {"cs": "ScreenSpaceReflections/sssr_prefilter.comp"},
    "sssr_prepare_args": {"cs": "ScreenSpaceReflections/sssr_prepare_args.comp"},
    "sssr_reproject": {"cs": "ScreenSpaceReflections/sssr_reproject.comp"},
    "sssr_temporal": {"cs": "ScreenSpaceReflections/sssr_temporal.comp"},
    "msm_write": {"vs": "fullscreen_noinput.vert", "fs": "msm_write.frag"},
    # Contact shadows are selected by the view's Shadow Settings at runtime,
    # so both Player and Editor exports need the complete compute chain.
    "screen_space_shadow_prepare": {"cs": "ScreenSpaceShadows/screen_space_shadow_prepare.comp"},
    "screen_space_shadow": {"cs": "ScreenSpaceShadows/screen_space_shadow.comp"},
    "screen_space_shadow_resolve": {"cs": "ScreenSpaceShadows/screen_space_shadow_resolve.comp"},
    "screen_space_shadow_match": {"cs": "ScreenSpaceShadows/screen_space_shadow_match.comp"},
    "shadow_debug_overlay": {"vs": "fullscreen_noinput.vert", "fs": "shadow_debug_overlay.frag"},
    "world_debug": {"vs": "world_debug.vert", "fs": "world_debug.frag"},
    "world_depthonly": {"vs": "world_debug.vert", "fs": "world_depthonly.frag"},
    "world_debug_forwardplus": {"vs": "world_debug_forwardplus.vert",
                                "fs": "world_debug_forwardplus.frag"},
    # Volumetric clouds (Engine/Modules/VolumetricClouds owns these sources):
    # six passes the default ForwardPlus graph carries. Unlike the DOF node
    # below these are graph passes, so a package the runtime cannot load is an
    # Error against the whole pipeline — the editor keeps the previous pipeline
    # and the scene viewport draws nothing. They cook regardless of whether the
    # effect is switched on, because validation runs on the graph, not the
    # effect's state.
    "volumetric_clouds_shape_noise": {"cs": "volumetric_clouds_shape_noise.comp"},
    "volumetric_clouds_detail_noise": {"cs": "volumetric_clouds_detail_noise.comp"},
    "volumetric_clouds_march": {"vs": "fullscreen_noinput.vert",
                                "fs": "volumetric_clouds_march.frag"},
    "volumetric_clouds_resolve": {"vs": "fullscreen_noinput.vert",
                                  "fs": "volumetric_clouds_resolve.frag"},
    "volumetric_clouds_composite": {"vs": "fullscreen_noinput.vert",
                                    "fs": "volumetric_clouds_composite.frag"},
    # FidelityFX depth of field (Packages/fidelityfx-dof): requested by
    # FidelityFXDofNode, active only when the package is mounted. The node
    # degrades to passthrough with one warning per missing stage, so a cook
    # failure here costs the effect, not the graph.
    "ffx_dof_prepare": {"cs": "ffx_dof_prepare.comp"},
    "ffx_dof_tile": {"cs": "ffx_dof_tile.comp"},
    "ffx_dof_dilate": {"cs": "ffx_dof_dilate.comp"},
    "ffx_dof_blur": {"cs": "ffx_dof_blur.comp"},
    "ffx_dof_composite": {"cs": "ffx_dof_composite.comp"},
    # Anti-aliasing (SMAA + two-frame FXAA), added to the render pipeline by the
    # AA stack. SmaaNode/TemporalFxaaNode hard-require these packages: a missing
    # stage errors the whole graph and the viewport draws nothing (see above).
    "smaa_edges": {"cs": "smaa_edges.comp"},
    "smaa_weights": {"cs": "smaa_weights.comp"},
    "smaa_blend": {"cs": "smaa_blend.comp"},
    "fxaa": {"cs": "fxaa.comp"},
    "fxaa_quality": {"cs": "fxaa_quality.comp"},
    "fxaa_resolve": {"cs": "fxaa_resolve.comp"},
}

# Built-in packages only the Editor's own render path binds, on top of
# kPackages. Determined from what the wasm Editor asks for at runtime (the
# "failed to load shaderpkg" lines in its first frame), not from filenames.
kEditorPackages: dict[str, dict[str, str]] = {
    # The frustum-culling half of the GPU-culling set. hzb_culling and
    # runtime_visibility_aggregate are NOT here: tint rejects them (the
    # GPU-driven path's constructs), and the compat profile never dispatches
    # them anyway — their absence costs a startup warning, not a pass.
    "frustum_culling": {"cs": "frustum_culling.comp"},
    "visibility_union": {"cs": "visibility_union.comp"},
    # Requested at runtime by pipeline NODES rather than declared in the graph
    # JSON (AutoExposure, TAA, SSSR, GTAO, HZB build, lens flare), so the graph
    # compiles without them and the frame then reports them missing.
    "auto_exposure_histogram": {"cs": "auto_exposure_histogram.comp"},
    "auto_exposure_resolve": {"cs": "auto_exposure_resolve.comp"},
    # DDGI probe update + resolve, software-trace lane only. The hardware
    # classify/trace/refit-HW use ray queries, which WebGPU has no equivalent
    # for — their absence is what routes the feature to this lane.
    "ddgi_clear": {"cs": "ddgi_clear.comp"},
    "ddgi_upload": {"cs": "ddgi_upload.comp"},
    "ddgi_classify_sw": {"cs": "ddgi_classify_sw.comp"},
    "ddgi_bvh_refit": {"cs": "ddgi_bvh_refit.comp"},
    "ddgi_trace_sw": {"cs": "ddgi_trace_sw.comp"},
    "ddgi_blend": {"cs": "ddgi_blend.comp"},
    "ddgi_rough_upload": {"cs": "ddgi_rough_upload.comp"},
    "ddgi_rough_blend": {"cs": "ddgi_rough_blend.comp"},
    "ddgi_glossy_upload": {"cs": "ddgi_glossy_upload.comp"},
    "ddgi_glossy_blend": {"cs": "ddgi_glossy_blend.comp"},
    "ddgi_map_atlas_blit": {"cs": "ddgi_map_atlas_blit.comp"},
    "ddgi_glossy_resolve": {"cs": "ddgi_glossy_resolve.comp"},
    "ddgi_glossy_resolve_blur": {"cs": "ddgi_glossy_resolve_blur.comp"},
    "ddgi_skin_positions": {"cs": "ddgi_skin_positions.comp"},
    "gtao_prepare": {"cs": "AmbientOcclusion/gtao_prepare.comp"},
    "gtao_depth_mip": {"cs": "AmbientOcclusion/gtao_depth_mip.comp"},
    "gtao": {"cs": "AmbientOcclusion/gtao.comp"},
    "gtao_blur": {"cs": "AmbientOcclusion/gtao_blur.comp"},
    "gtao_upsample": {"cs": "AmbientOcclusion/gtao_upsample.comp"},
    "gtao_temporal": {"cs": "AmbientOcclusion/gtao_temporal.comp"},
    "hzb_build": {"cs": "hzb_build.comp"},
    "lens_flare": {"vs": "lens_flare.vert", "fs": "lens_flare.frag"},
    "sun_glare": {"vs": "sun_glare.vert", "fs": "sun_glare.frag"},
    "sun_glare_ms": {"vs": "sun_glare_ms.vert", "fs": "sun_glare.frag"},
    "msm_blur_h": {"vs": "fullscreen_noinput.vert", "fs": "msm_blur_h.frag"},
    "sssr_classify": {"cs": "ScreenSpaceReflections/sssr_classify.comp"},
    "sssr_composite": {"cs": "ScreenSpaceReflections/sssr_composite.comp"},
    "sssr_intersect": {"cs": "ScreenSpaceReflections/sssr_intersect.comp"},
    "sssr_prefilter": {"cs": "ScreenSpaceReflections/sssr_prefilter.comp"},
    "sssr_prepare_args": {"cs": "ScreenSpaceReflections/sssr_prepare_args.comp"},
    "sssr_reproject": {"cs": "ScreenSpaceReflections/sssr_reproject.comp"},
    "sssr_temporal": {"cs": "ScreenSpaceReflections/sssr_temporal.comp"},
    # Volumetric fog: five compute stages + the fullscreen composite. Sources
    # live in Engine/Modules/VolumetricFog/Shaders (an extra-root glob).
    "volumetric_fog_media": {"cs": "volumetric_fog_media.comp"},
    "volumetric_fog_cull": {"cs": "volumetric_fog_cull.comp"},
    "volumetric_fog_light": {"cs": "volumetric_fog_light.comp"},
    "volumetric_fog_filter": {"cs": "volumetric_fog_filter.comp"},
    "volumetric_fog_integrate": {"cs": "volumetric_fog_integrate.comp"},
    "volumetric_fog_temporal": {"cs": "volumetric_fog_temporal.comp"},
    "volumetric_fog_composite": {"vs": "fullscreen_noinput.vert", "fs": "volumetric_fog_composite.frag"},
    # Ocean. Every one of these was missing, so the module reported six compile
    # failures at boot and the water never simulated: the FFT cascades, the
    # sim passes that feed them, and the underwater/caustics fullscreen work.
    # Sources live in Engine/Modules/Rendering/Shaders/Ocean; the programs are
    # requested by debugName from Engine/Modules/Ocean.
    "ocean_fft_init": {"cs": "ocean_fft_spectrum_init.comp"},
    "ocean_fft_update": {"cs": "ocean_fft_spectrum_update.comp"},
    "ocean_fft_h": {"cs": "ocean_fft_horizontal.comp"},
    "ocean_fft_v": {"cs": "ocean_fft_vertical.comp"},
    "ocean_combine": {"cs": "ocean_combine.comp"},
    "ocean_albedo_sim": {"cs": "ocean_albedo_sim.comp"},
    "ocean_wavemask_sim": {"cs": "ocean_wavemask_sim.comp"},
    "ocean_clip_sim": {"cs": "ocean_clip_sim.comp"},
    "ocean_flow_sim": {"cs": "ocean_flow_sim.comp"},
    "ocean_foam_sim": {"cs": "ocean_foam_sim.comp"},
    "ocean_dynwaves_sim": {"cs": "ocean_dynwaves_sim.comp"},
    "ocean_dynwaves_query": {"cs": "ocean_dynwaves_query.comp"},
    "ocean_gpu_query": {"cs": "ocean_gpu_query.comp"},
    "ocean_height_query": {"cs": "ocean_height_query.comp"},
    "ocean_raster_depth_convert": {"cs": "ocean_raster_depth_convert.comp"},
    "ocean_seafloor_depth": {"cs": "ocean_seafloor_depth.comp"},
    "ocean_shadow_sim": {"cs": "ocean_shadow_sim.comp"},
    "ocean_spline_raster_depth": {"cs": "ocean_spline_raster_depth.comp"},
    "ocean_spline_raster_flow": {"cs": "ocean_spline_raster_flow.comp"},
    "ocean_spline_raster_clip": {"cs": "ocean_spline_raster_clip.comp"},
    "ocean_spline_raster_albedo": {"cs": "ocean_spline_raster_albedo.comp"},
    "ocean_spray_sim": {"cs": "ocean_spray_gpu_sim.comp"},
    "ocean_spray_cull": {"cs": "ocean_spray_gpu_cull.comp"},
    "ocean_spray_draw": {"vs": "ocean_spray_gpu.vert", "fs": "ocean_spray_gpu.frag"},
    "ocean_underwater": {"vs": "ocean_fullscreen.vert", "fs": "ocean_underwater.frag"},
    "ocean_underwater_shadowed": {"vs": "ocean_fullscreen.vert", "fs": "ocean_underwater.frag"},
    "ocean_underwater_resolve": {"vs": "ocean_fullscreen.vert", "fs": "ocean_resolve.frag"},
    "ocean_scenegrab_resolve": {"vs": "ocean_fullscreen.vert", "fs": "ocean_scene_resolve.frag"},
    "ocean_reflected_caustics": {"vs": "ocean_fullscreen.vert", "fs": "ocean_lightshafts.frag"},
    "ocean_reflected_caustics_resolve": {"vs": "ocean_fullscreen.vert", "fs": "ocean_resolve.frag"},
    "taa_motion_vectors": {"vs": "taa_motion_vectors.vert", "fs": "taa_motion_vectors.frag"},
    "taa_motion_vectors_skinned": {"vs": "taa_motion_vectors_skinned.vert", "fs": "taa_motion_vectors.frag"},
    "taa_resolve": {"cs": "taa_resolve.comp"},
    # Render scale != 1.0 resolves through the upscale variant; without it web
    # degrades to the warned bilinear passthrough.
    "taa_resolve_upscale": {"cs": "taa_resolve_upscale.comp"},
    "taau_depth_upsample": {"vs": "fullscreen_noinput.vert", "fs": "taau_depth_upsample.frag"},
    # The ForwardPlus graph's remaining passes. Generated from the
    # _ge_add_shaderpkg_* declarations in Engine/Modules/Rendering/CMakeLists.txt,
    # which is the source of truth for what each package's stages are; a package
    # missing here is not a pass that degrades, it is a graph that refuses to
    # compile, and with the engine's own pipeline refused nothing draws.
    "atmospheric_cloud_layer": {"vs": "fullscreen_noinput.vert", "fs": "atmospheric_cloud_layer.frag"},
    "bloom_combine": {"vs": "fullscreen_noinput.vert", "fs": "bloom_combine.frag"},
    "bloom_downsample": {"vs": "fullscreen_noinput.vert", "fs": "bloom_downsample.frag"},
    "bloom_lens_dirt": {"vs": "fullscreen_noinput.vert", "fs": "bloom_lens_dirt.frag"},
    "bloom_lens_dirt_gather": {"vs": "fullscreen_noinput.vert", "fs": "bloom_lens_dirt_gather.frag"},
    "halation_prefilter": {"vs": "fullscreen_noinput.vert", "fs": "halation_prefilter.frag"},
    "halation_blur_h": {"vs": "fullscreen_noinput.vert", "fs": "halation_blur_h.frag"},
    "halation_composite": {"vs": "fullscreen_noinput.vert", "fs": "halation_composite.frag"},
    "bloom_octave_gather": {"vs": "fullscreen_noinput.vert", "fs": "bloom_octave_gather.frag"},
    "bloom_threshold": {"vs": "fullscreen_noinput.vert", "fs": "bloom_threshold.frag"},
    "chromatic_aberration": {"vs": "fullscreen_noinput.vert", "fs": "chromatic_aberration.frag"},
    "cluster_debug_overlay": {"vs": "fullscreen_noinput.vert", "fs": "cluster_debug_overlay.frag"},
    "crt": {"vs": "fullscreen_noinput.vert", "fs": "crt.frag"},
    "fast_blur_dof": {"vs": "fullscreen_noinput.vert", "fs": "fast_blur_dof.frag"},
    "film_simulation_artifacts": {"vs": "fullscreen_noinput.vert", "fs": "film_simulation_artifacts.frag"},
    "film_simulation_grain": {"vs": "fullscreen_noinput.vert", "fs": "film_simulation_grain.frag"},
    "fog_glow_composite": {"vs": "fullscreen_noinput.vert", "fs": "fog_glow_composite.frag"},
    "fog_glow_downsample": {"vs": "fullscreen_noinput.vert", "fs": "fog_glow_downsample.frag"},
    "fog_glow_fast": {"vs": "fullscreen_noinput.vert", "fs": "fog_glow_fast.frag"},
    "fog_glow_gather": {"vs": "fullscreen_noinput.vert", "fs": "fog_glow_gather.frag"},
    "fog_glow_prefilter": {"vs": "fullscreen_noinput.vert", "fs": "fog_glow_prefilter.frag"},
    "hdr_color_fx": {"vs": "fullscreen_noinput.vert", "fs": "hdr_color_fx.frag"},
    "heat_distortion": {"vs": "fullscreen_noinput.vert", "fs": "heat_distortion.frag"},
    "height_fog": {"vs": "fullscreen_noinput.vert", "fs": "height_fog.frag"},
    "post_fx_ldr_stack": {"vs": "fullscreen_noinput.vert", "fs": "post_fx_ldr_stack.frag"},
    "vhs": {"vs": "fullscreen_noinput.vert", "fs": "vhs.frag"},
    "vhs_chroma_bands": {"vs": "fullscreen_noinput.vert", "fs": "vhs_chroma_bands.frag"},
    "vhs_composite_signal": {"vs": "fullscreen_noinput.vert", "fs": "vhs_composite_signal.frag"},
    "vhs_date_burn": {"vs": "fullscreen_noinput.vert", "fs": "vhs_date_burn.frag"},
    "vhs_frame_feedback": {"vs": "fullscreen_noinput.vert", "fs": "vhs_frame_feedback.frag"},
    "vhs_interference": {"vs": "fullscreen_noinput.vert", "fs": "vhs_interference.frag"},
    "vhs_rf_dropouts": {"vs": "fullscreen_noinput.vert", "fs": "vhs_rf_dropouts.frag"},
    "vhs_signal_glitches": {"vs": "fullscreen_noinput.vert", "fs": "vhs_signal_glitches.frag"},
    "editor_lines": {"vs": "lines.vert", "fs": "lines.frag"},
}

# Built-in packages the web library's engine pack (engine_pack.py) cooks on top of
# kPackages: those the library's own pipeline (Apps/WebLibrary/Assets/RenderPipelines/
# Web.rendergraph) adds to the web export's graph (auto exposure, sun glare and bloom),
# the shadow map's moment blur and cascade passes, which ShadowMapNode loads by name
# whenever the graph has a shadow map (its moment write, msm_write, is in kPackages), and
# the DDGI software lane with its screen-space resolve, which the graph's DDGIGen pass and
# the compat forward pass (GE_DDGI_RESOLVE_ONLY, Includes/ibl.glsl) run once a page adds a
# DDGIVolume: without them the volume lights nothing.
kLibraryPackages: dict[str, dict[str, str]] = {
    name: kEditorPackages[name] for name in (
        "auto_exposure_histogram", "auto_exposure_resolve", "sun_glare", "sun_glare_ms",
        "bloom_threshold", "bloom_downsample", "bloom_octave_gather", "bloom_lens_dirt_gather",
        "bloom_combine", "bloom_lens_dirt", "msm_blur_h",
        *(name for name in kEditorPackages if name.startswith("ddgi_")))
}
# The moment rows belong in kPackages, where the web Player needs them too (#3138); these two
# literals and msm_blur_h above are duplicates to delete once they are there.
kLibraryPackages["msm_blur_v"] = {"vs": "fullscreen_noinput.vert", "fs": "msm_blur_v.frag"}
kLibraryPackages["msm_cascade"] = {"cs": "msm_cascade.comp"}

# Stage shaders with no package: name as the runtime asks for it (minus the
# .spv), then the GLSL source and any defines beyond kWebDefines. Same runtime
# set as kEditorPackages above, determined from what the wasm Editor asks for at
# runtime, not from filenames.
#
# The ui_sdf family carries the _compat suffix UIManager::SdfShaderPath appends
# under the compatibility profile — the only profile a browser device resolves,
# and the only one whose shaders have fixed texture slots instead of the binding
# arrays no WebGPU implementation exposes (Shaders/UI/ui_sdf_textures.glsl). The
# subpixel twins are cooked because the set has to be complete, not because a
# browser can run them: dual-source blending is an optional WebGPU feature and
# the runtime gate resolves subpixel off without it.
kEditorStageShaders: dict[str, tuple[str, list[str]]] = {
    "ui_sdf_compat.vert": ("ui_sdf.vert", []),
    "ui_sdf_compat.frag": ("ui_sdf.frag", []),
    "ui_sdf_subpixel_compat.vert": ("ui_sdf.vert", ["UI_SUBPIXEL_DUAL_SRC"]),
    "ui_sdf_subpixel_compat.frag": ("ui_sdf.frag", ["UI_SUBPIXEL_DUAL_SRC"]),
    "ui_sdf_encoded_compat.frag": ("ui_sdf.frag", ["UI_BLEND_SPACE_ENCODED"]),
    "ui_sdf_subpixel_encoded_compat.frag": ("ui_sdf.frag",
                                            ["UI_SUBPIXEL_DUAL_SRC", "UI_BLEND_SPACE_ENCODED"]),
    "fullscreen_noinput.vert": ("fullscreen_noinput.vert", []),
    # The sky-environment capture chain and the BRDF LUT bake: loaded by bare
    # stage name through LoadShaderFile, and the source of the IBL env cubes —
    # without them the cubes stay at their seed and metals reflect nothing.
    "brdf_lut.comp": ("brdf_lut.comp", []),
    "sky_capture_cube.frag": ("sky_capture_cube.frag", []),
    "sky_diffuse_convolve.comp": ("sky_diffuse_convolve.comp", []),
    "sky_env_mip_downsample.comp": ("sky_env_mip_downsample.comp", []),
    "sky_specular_prefilter.comp": ("sky_specular_prefilter.comp", []),
    "copy.frag": ("copy.frag", []),
    "lines.vert": ("lines.vert", []),
    "lines.frag": ("lines.frag", []),
    "selection_mask.vert": ("selection_mask.vert", []),
    "selection_mask.frag": ("selection_mask.frag", []),
    "selection_mask_skinned.vert": ("selection_mask_skinned.vert", []),
    "selection_mask_alpha.vert": ("selection_mask_alpha.vert", []),
    "selection_mask_alpha.frag": ("selection_mask_alpha.frag", []),
    "selection_outline.frag": ("selection_outline.frag", []),
    # Grass plan + placement. The desktop build compiles these at runtime through
    # ShaderCompileService; a browser ships no compiler, so they have to be cooked here and
    # loaded by name (EnsureComputePipeline dispatches both stages on web). The placement's
    # terrain/atlas taps resolve against named set-0 maps (see grassMapTap) rather than the
    # bindless array WebGPU does not expose; the plan samples no texture at all.
    "TerrainGrass/terrain_grass_classify.comp": ("TerrainGrass/terrain_grass_classify.comp", []),
    "TerrainGrass/terrain_grass_plan.comp": ("TerrainGrass/terrain_grass_plan.comp", []),
    "TerrainGrass/terrain_grass_place.comp": ("TerrainGrass/terrain_grass_place.comp", []),
}

# CBT terrain's compute kernels. Two things make these unlike every other entry above.
#
# GE_CBT_HEAP32 selects the narrow-heap arm of cbt_layout.glsl: the shipped kernels put the
# bisector heap ID in a uint64_t and walk the barycentric decode in i64vec3, and WGSL has no
# 64-bit integer at all. The narrow arm is the same algorithm at u32 width, which costs
# subdivision RANGE (kHeap32DecodeSubdiv, mirrored by the host clamp) and nothing else.
#
# KERNEL=i picks one kernel out of the file's switch. The desktop build compiles ONE blob
# and specializes constant_id=0 kCBTKernelCount ways; WebGPU has no specialization
# constants, so each kernel is its own cooked program instead. The names mirror
# CBTKernelSet::KernelProgramFileName, which is what the loader opens.
#
# The count is READ from CBTKernelSet.h rather than repeated here. A hand-copied count that
# falls behind the enum cooks a short set, and the failure surfaces at terrain bring-up as
# one pipeline that will not load — far from the edit that caused it. Parsing turns that
# into a cook-time error naming the file.
def CBTKernelCount() -> int:
    header = kRepoRoot / "Engine" / "Modules" / "CBTTerrain" / "Include" / "CBTTerrain" / \
        "CBTKernelSet.h"
    match = re.search(r"Count\s*=\s*(\d+)\s*[,}]", header.read_text())
    if match is None:
        raise RuntimeError(f"cannot read CBTKernel::Count from {header}")
    return int(match.group(1))


kEditorStageShaders.update({
    f"CBT/cbt_kernels_{i}.comp": ("CBT/cbt_kernels.comp", ["GE_CBT_HEAP32", f"KERNEL={i}u"])
    for i in range(CBTKernelCount())
})

kStageNames = {"vs": "vertex", "fs": "fragment", "cs": "compute"}
kStageByExtension = {".vert": "vertex", ".frag": "fragment", ".comp": "compute"}

# The built-in packages compile under the same profile as the cooked material
# variants (MaterialVariantCook --web): explicit-LOD taps, flat derivatives and
# the WebGPU-legal shadow bindings. Without it these sources reach tint with
# non-uniform derivative and comparison-sampling calls it rejects.
kWebDefines = ["GE_COMPAT_PROFILE"]

class CookFailure(Exception):
    """One package failed; the caller decides whether that is fatal."""


# The .shaderpkg container is read and written only by the engine's
# ShaderReflect tool (ShaderPackageContainer), never here: one reader and one
# writer of the format. These wrap the tool's package modes.
def RunShaderReflect(reflector: Path, args: list[str | Path]) -> str:
    result = shadercook.Run([reflector, *args])
    if result.returncode != 0:
        raise CookFailure(f"ShaderReflect {' '.join(str(a) for a in args)} failed: "
                          f"{(result.stderr or result.stdout).strip()}")
    return result.stdout


def ListShaderPkgChunks(reflector: Path, path: Path) -> list[dict]:
    """The package's chunk table: [{"name", "type", "size"}, ...] in file order."""
    return json.loads(RunShaderReflect(reflector, ["--list-chunks", path]))


def ReadShaderPkgChunk(reflector: Path, path: Path, name: str) -> bytes:
    with tempfile.TemporaryDirectory() as tempDir:
        out = Path(tempDir) / "chunk.bin"
        RunShaderReflect(reflector, ["--read-chunk", path, "--chunk", f"{name}={out}"])
        return out.read_bytes()


def ReadShaderPkgMeta(reflector: Path, path: Path) -> dict:
    """The package's reflection metadata, as the tool prints it."""
    return json.loads(RunShaderReflect(reflector, ["--inspect", path]))


def AppendShaderPkgChunks(reflector: Path, path: Path, chunks: list[tuple[str, Path]]) -> None:
    args: list[str | Path] = ["--append-chunk", path]
    for name, source in chunks:
        args += ["--chunk", f"{name}={source}"]
    RunShaderReflect(reflector, args)


def StripShaderPkgSpirv(reflector: Path, paths: list[Path], batch: int = 64) -> None:
    """Rewrite each package without the SPIR-V of every stage that also carries WGSL."""
    for start in range(0, len(paths), batch):
        RunShaderReflect(reflector, ["--strip-spirv-with-wgsl", *paths[start:start + batch]])


def FindToolchain() -> tuple[Path, Path, Path | None]:
    glslc = shadercook.FindTool("glslc", None)
    naga = shadercook.FindTool("naga", None)
    tint = shadercook.FindTool("tint", None)
    if glslc is None:
        raise RuntimeError("glslc not found — install the Vulkan SDK")
    if naga is None:
        raise RuntimeError("naga not found — run Tools/ShaderCook/toolchain/setup.py to fetch it")
    return glslc, naga, tint


def FindShaderReflect(shaderPkgDir: Path, explicit: Path | None = None) -> Path:
    """Find the host packager beside the desktop shader build or staged editor."""
    configured = explicit or os.environ.get("GE_SHADERREFLECT_EXECUTABLE")
    if configured:
        path = Path(configured)
        if not path.is_file():
            raise RuntimeError(f"ShaderReflect does not exist: {path}")
        return path
    name = "ShaderReflect.exe" if sys.platform == "win32" else "ShaderReflect"
    for parent in (shaderPkgDir, *shaderPkgDir.parents):
        candidates = [parent / "Tools" / name, parent / "bin" / "Tools" / name]
        candidates += sorted((parent / "bin").glob(f"*/Tools/{name}"))
        found = [path for path in candidates if path.is_file()]
        if found:
            return max(found, key=lambda path: path.stat().st_mtime_ns)
    found = shadercook.FindTool("ShaderReflect", None)
    if found is not None:
        return found
    raise RuntimeError("ShaderReflect not found — build the desktop ShaderReflect target "
                       "or pass --shader-reflect / set GE_SHADERREFLECT_EXECUTABLE")


# Not every built-in package's source sits in Rendering/Shaders. Modules own
# their own (HeightFog), and engine packages own theirs under Assets/Shaders
# (film-simulation, chromatic-aberration), so a package name alone does not say
# where its stages live. The search is ordered: the engine shader dir first, so
# nothing here can shadow a core shader, then the module and package roots.
kExtraShaderRoots = [
    kRepoRoot / "Engine" / "Modules",
    kRepoRoot / "Packages",
]

# Include roots for includes that cross a module boundary. The runtime passes the same set
# (TerrainGrassRenderFeature::EnsureComputePipeline hands the placement shader CBT's dir for
# the bare-name cbt_atlas.glsl, plus the grass module's Shaders root so its own
# "TerrainGrass/…" includes resolve), so the cook resolves what the engine resolves.
kSharedShaderRoots = [
    kRepoRoot / "Engine" / "Modules" / "CBTTerrain" / "Shaders" / "CBT",
    kRepoRoot / "Engine" / "Modules" / "TerrainGrass" / "Shaders",
]


def ResolveShaderSource(sourceName: str, shaderSourceDir: Path) -> Path:
    direct = shaderSourceDir / sourceName
    if direct.is_file():
        return direct
    # A subdirectory of the engine shader dir, which is where the ocean keeps
    # its stages (Shaders/Ocean). Searched after the root so a subdirectory
    # cannot shadow a core shader of the same name, and before the module roots
    # for the same reason.
    nested = sorted(shaderSourceDir.glob(f"*/{sourceName}"))
    if nested:
        return nested[0]
    for root in kExtraShaderRoots:
        found = sorted(root.glob(f"*/Shaders/{sourceName}")) + \
                sorted(root.glob(f"*/Assets/Shaders/{sourceName}"))
        if found:
            return found[0]
    # Report the path the caller asked for: the error then names the shader the
    # package declared rather than the last directory that happened to be tried.
    return direct


def CookBuiltinPackages(shaderPkgDir: Path, shaderSourceDir: Path, outDir: Path,
                        validate: bool = True,
                        packages: dict[str, dict[str, str]] | None = None,
                        shaderReflect: Path | None = None
                        ) -> list[tuple[str, str]]:
    """Write WGSL-carrying copies of every built-in package into `outDir`.

    Returns the list of (package, error) failures; an empty list means the
    whole set cooked. Raises RuntimeError only when the toolchain is missing,
    which is an environment fault rather than a content one.
    """
    glslc, naga, tint = FindToolchain()
    reflector = FindShaderReflect(shaderPkgDir, shaderReflect)

    failures: list[tuple[str, str]] = []
    for packageName, stages in (packages if packages is not None else kPackages).items():
        sourcePkg = shaderPkgDir / f"{packageName}.shaderpkg"
        if not sourcePkg.exists():
            failures.append((packageName, f"missing desktop package {sourcePkg}"))
            continue
        try:
            with tempfile.TemporaryDirectory() as tempDir:
                scratch = Path(tempDir)
                wgslChunks = []
                reflectionArgs = [reflector]
                for stageKey, sourceName in stages.items():
                    outWgsl = scratch / f"{packageName}.{stageKey}.wgsl"
                    source = ResolveShaderSource(sourceName, shaderSourceDir)
                    shadercook.CookFile(source, kStageNames[stageKey],
                                        glslc, naga, tint, validate, kWebDefines,
                                        [shaderSourceDir, source.parent], outWgsl, scratch)
                    wgslChunks.append((f"{stageKey}-wgsl", outWgsl))
                    # Reflect the preprocessed GLSL before the cook lowers push
                    # constants into the backend's emulation buffer. Runtime
                    # metadata keeps the engine abstraction for those constants.
                    flattened = scratch / (source.stem + ".pp" + source.suffix)
                    reflectedSpv = scratch / f"{packageName}.{stageKey}.reflect.spv"
                    result = shadercook.Run([glslc, "--target-env=vulkan1.1",
                        f"-fshader-stage={kStageNames[stageKey]}", flattened, "-o", reflectedSpv])
                    if result.returncode != 0:
                        raise CookFailure(f"reflection compile failed for {source}: {result.stderr}")
                    reflectionArgs += [f"--{stageKey}", reflectedSpv]
                reflectedPkg = scratch / f"{packageName}.shaderpkg"
                result = shadercook.Run(reflectionArgs + ["--out", reflectedPkg])
                if result.returncode != 0:
                    raise CookFailure(f"ShaderReflect failed for {packageName}: {result.stderr or result.stdout}")
                AppendShaderPkgChunks(reflector, reflectedPkg, wgslChunks)
                outDir.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(reflectedPkg, outDir / f"{packageName}.shaderpkg")
        except (shadercook.CookError, CookFailure) as error:
            failures.append((packageName, str(error)))
    return failures


def CookStageShaders(shaderSourceDir: Path, outDir: Path, validate: bool = True,
                     stages: dict[str, tuple[str, list[str]]] | None = None
                     ) -> list[tuple[str, str]]:
    """Cook the package-less stage shaders into `<name>.wgsl` under `outDir`."""
    glslc, naga, tint = FindToolchain()
    outDir.mkdir(parents=True, exist_ok=True)

    failures: list[tuple[str, str]] = []
    for name, (sourceName, extraDefines) in (
            stages if stages is not None else kEditorStageShaders).items():
        # Same resolution the packages use: a module that owns its own shaders (CBT) is
        # not under the engine shader root, and a name alone does not say where it lives.
        source = ResolveShaderSource(sourceName, shaderSourceDir)
        stage = kStageByExtension.get(source.suffix)
        if stage is None:
            failures.append((name, f"cannot infer a stage from '{source.name}'"))
            continue
        try:
            # Cooked in scratch so the sampler-remap sidecar CookFile drops
            # beside its output stays out of the shipped tree.
            with tempfile.TemporaryDirectory() as tempDir:
                scratch = Path(tempDir)
                cooked = scratch / f"{Path(name).name}.wgsl"
                # source.parent so a module's shader resolves its siblings by bare name;
                # kSharedShaderRoots for the cross-module bare-name includes the runtime
                # passes explicitly (grass placement includes CBT's cbt_atlas.glsl so the
                # blades resolve the atlas exactly as the surface does).
                shadercook.CookFile(source, stage, glslc, naga, tint, validate,
                                    kWebDefines + extraDefines,
                                    [shaderSourceDir, source.parent] + kSharedShaderRoots,
                                    cooked, scratch)
                # A name may carry a subdirectory (CBT/…), mirroring the staged layout the
                # runtime probes.
                target = outDir / f"{name}.wgsl"
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(cooked.read_bytes())
        except shadercook.CookError as error:
            failures.append((name, str(error)))
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--shaderpkg-dir", type=Path, required=True,
                        help="desktop build's Shaders/ dir (SPIR-V .shaderpkg + reflection)")
    parser.add_argument("--shader-reflect", type=Path,
                        help="host ShaderReflect executable (default: desktop build or PATH)")
    parser.add_argument("--out", type=Path, required=True,
                        help="directory to write the cooked packages and stage shaders into")
    parser.add_argument("--engine-shaders", type=Path,
                        default=kRepoRoot / "Engine" / "Modules" / "Rendering" / "Shaders",
                        help="engine GLSL shader source root")
    parser.add_argument("--editor", action="store_true",
                        help="also cook the Editor-only packages and stage shaders")
    args = parser.parse_args()

    packages = dict(kPackages)
    if args.editor:
        packages.update(kEditorPackages)

    try:
        failures = CookBuiltinPackages(args.shaderpkg_dir, args.engine_shaders,
                                       args.out, packages=packages,
                                       shaderReflect=args.shader_reflect)
        if args.editor:
            failures += CookStageShaders(args.engine_shaders, args.out)
    except RuntimeError as error:
        print(f"builtin_shader_cook: {error}", file=sys.stderr)
        return 2

    for name, error in failures:
        print(f"  FAILED {name}: {error.splitlines()[0] if error else ''}", file=sys.stderr)
    if failures:
        print(f"builtin_shader_cook: {len(failures)} shader(s) failed to cook", file=sys.stderr)
        return 1

    cooked = len(packages) + (len(kEditorStageShaders) if args.editor else 0)
    print(f"builtin_shader_cook: {cooked} artifacts -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
