if(NOT DEFINED PLAYER_CONTENT_DIR)
    message(FATAL_ERROR "PLAYER_CONTENT_DIR must identify the Player's staged content directory")
endif()

foreach(shader IN ITEMS Particles/particle_vertex.glsl Surfaces/particle_surface.glsl)
    set(path "${PLAYER_CONTENT_DIR}/Assets/Shaders/${shader}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing runtime particle shader: ${path}")
    endif()
    file(SIZE "${path}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Empty runtime particle shader: ${path}")
    endif()
endforeach()
