// Auto-generated. The @sg-* tag block is authoritative.
// The body below is regenerated by the graph editor on save.
//
// @sg-graph     GraphSampleRed
// @sg-version   1
// @sg-stage     surface
// @sg-lighting  StandardPBR
//
// @sg-node      node_color       type=ColorConstant    pos=(120,140)   r=0.08 g=0.28 b=1.0
// @sg-node      ein              type=EngineInput      pos=(80,80)
// @sg-node      node_fresnel     type=Fresnel          pos=(360,80)    power=4.0
// @sg-node      node_rim_color   type=ColorConstant    pos=(360,300)   r=1.45 g=0.48 b=0.04
// @sg-node      node_fresnel_vec type=VectorCompose    pos=(620,280)
// @sg-node      node_rim_emissive type=VectorMultiply  pos=(860,260)
// @sg-node      node_output      type=SurfaceOutput    pos=(1120,160)
//
// @sg-edge      node_color.value        -> node_output.BaseColor
// @sg-edge      ein.WorldNormal         -> node_fresnel.normal
// @sg-edge      ein.ViewDirection       -> node_fresnel.view
// @sg-edge      node_fresnel.out        -> node_fresnel_vec.x
// @sg-edge      node_fresnel.out        -> node_fresnel_vec.y
// @sg-edge      node_fresnel.out        -> node_fresnel_vec.z
// @sg-edge      node_fresnel_vec.out    -> node_rim_emissive.a
// @sg-edge      node_rim_color.value    -> node_rim_emissive.b
// @sg-edge      node_rim_emissive.out   -> node_output.Emissive

SurfaceOutput EvaluateSurface(SurfaceInput sIn)
{
    SurfaceOutput o = DefaultSurfaceOutput();
    vec3 _node_color_value = SG_ColorConstant(0.08, 0.28, 1.0);
    float _node_fresnel_out = SG_Fresnel(sIn.normalWS, sIn.viewDirWS, 4.0);
    vec3 _node_rim_color_value = SG_ColorConstant(1.45, 0.48, 0.04);
    vec3 _node_fresnel_vec_out = SG_VectorCompose(_node_fresnel_out, _node_fresnel_out, _node_fresnel_out);
    vec3 _node_rim_emissive_out = SG_VectorMultiply(_node_fresnel_vec_out, _node_rim_color_value);
    o.baseColor = _node_color_value;
    o.emissive = _node_rim_emissive_out;
    return o;
}
