// Auto-generated. The @sg-* tag block is authoritative.
// The body below is regenerated by the graph editor on save.
//
// @sg-graph     PreviewSphereTest
// @sg-version   1
// @sg-stage     surface
// @sg-property  uBaseColor vec3 default=0.08, 0.28, 1.0 public=true
// @sg-property  uMetallic float default=0.05 public=true
// @sg-property  uRoughness float default=0.28 public=true
// @sg-property  uRimColor vec3 default=1.45, 0.48, 0.04 public=true
// @sg-viewport  panX=293.13 panY=260.241 zoom=0.873269
//
// @sg-node      node_base_color type=ColorParameter pos=(80,140) variableName=uBaseColor slot=0 swizzle=xyz
// @sg-node      node_metallic type=FloatParameter pos=(80,260) variableName=uMetallic component=x slot=1
// @sg-node      node_roughness type=FloatParameter pos=(80,360) variableName=uRoughness component=y slot=1
// @sg-node      node_fresnel type=Fresnel pos=(350,540) power=2.6
// @sg-node      node_fresnel_vec type=VectorCompose pos=(600,500)
// @sg-node      node_rim_color type=ColorParameter pos=(600,700) variableName=uRimColor slot=2 swizzle=xyz
// @sg-node      node_rim_emissive type=VectorMultiply pos=(860,580)
// @sg-node      node_output type=SurfaceOutput pos=(1160,300)
// @sg-node      ein type=EngineInput pos=(80,500)
// @sg-edge      node_base_color.value -> node_output.BaseColor
// @sg-edge      node_metallic.value -> node_output.Metallic
// @sg-edge      node_roughness.value -> node_output.Roughness
// @sg-edge      ein.WorldNormal -> node_fresnel.normal
// @sg-edge      ein.ViewDirection -> node_fresnel.view
// @sg-edge      node_fresnel.out -> node_fresnel_vec.x
// @sg-edge      node_fresnel.out -> node_fresnel_vec.y
// @sg-edge      node_fresnel.out -> node_fresnel_vec.z
// @sg-edge      node_fresnel_vec.out -> node_rim_emissive.a
// @sg-edge      node_rim_color.value -> node_rim_emissive.b
// @sg-edge      node_rim_emissive.out -> node_output.Emissive
// @sg-edge      ein.WorldNormal -> node_output.Normal

SurfaceOutput EvaluateSurface(SurfaceInput sIn)
{
    SurfaceOutput o = DefaultSurfaceOutput();
float _node_fresnel_result = SG_Fresnel(sIn.normalWS, sIn.viewDirWS, 2.6);
vec3 _node_fresnel_vec_result = SG_VectorCompose(_node_fresnel_result, _node_fresnel_result, _node_fresnel_result);
vec3 _node_rim_emissive_result = SG_VectorMultiply(_node_fresnel_vec_result, Mat.uParams2.xyz);
    o.baseColor = Mat.uBaseColor.xyz;
    o.metallic = Mat.uParams0.x;
    o.roughness = Mat.uParams0.y;
    o.normalWS = normalize(sIn.normalWS);
    o.emissive = _node_rim_emissive_result;
    return o;
}
