// The inspector's notice control: a statement on a plate, and optionally the one action that
// resolves it. What every consumer rests on is that the text and the action are in the element tree
// from construction (the layout is instantiated by the constructor, not on attach), so the first
// test reads them from a notice no UIManager has seen, and another builds one inside an event
// dispatch, where an inspector rebuild can build it. An action that rebuilds its own notice runs to
// its end on the real input path. The layout tests lay the real notice out over the real editor
// stylesheets: the action at the end of the text's row on its first line, no space for an action
// the notice does not have, a long text wrapping beside its action at a narrow inspector, the action
// under the text only where the row has no room for both, and a notice keeping its height in a
// crowded column.

#include <gtest/gtest.h>

#include "InspectorLayoutFixture.h"
#include "Input/KeyCodes.h"
#include "UI/Controls/Button.h"
#include "UI/Controls/InspectorNotice.h"
#include "UI/Controls/Label.h"
#include "UI/UIElement.h"
#include "UI/UIEvents.h"

#include <memory>
#include <string>
#include <vector>

using GameEngine::Button;
using GameEngine::kEventButtonClick;
using GameEngine::Label;
using GameEngine::UIElement;
using GameEngine::UIEvent;
using GameEngine::EditorUI::InspectorNotice;
using InspectorLayoutTesting::FindByClass;
using InspectorLayoutTesting::InspectorLayoutFixture;

namespace
{

// The notice's own sheet and the shared button and visibility rules it relies on, in the order the
// editor attaches them after the theme.
const std::vector<std::string> kNoticeSheets{"Assets/UI/theme/core.css", "Assets/UI/controls/Button.css",
                                             "Assets/UI/controls/InspectorNotice/InspectorNotice.css"};

// Layout rounds to a fraction of a pixel; containment is checked to this tolerance.
constexpr float kLayoutTolerance = 0.5f;

// A long notice: several lines at any inspector width.
const std::string kLongText =
    "Generated by Garden Path. This piece is rebuilt from its spline and recipe, and is not saved with "
    "the scene - edits made here are overwritten on the next rebuild. Edit Garden Path instead.";

Label* TextOf(UIElement& notice)
{
    return dynamic_cast<Label*>(FindByClass(&notice, "inspector-notice-text"));
}

Button* ActionOf(UIElement& notice)
{
    return dynamic_cast<Button*>(FindByClass(&notice, "inspector-notice-action"));
}

void Click(Button& button)
{
    UIEvent e{};
    e.Id = kEventButtonClick;
    e.Target = &button;
    e.CurrentTarget = &button;
    button.DispatchEvent(e);
}

float Right(const UIElement& element)
{
    return element.GetLayoutX() + element.GetLayoutWidth();
}

float Bottom(const UIElement& element)
{
    return element.GetLayoutY() + element.GetLayoutHeight();
}

// True when `action` spans the vertical middle of `text`'s first line, `lineHeight` tall: the two
// read as one line.
bool OnFirstLine(const UIElement& action, const UIElement& text, float lineHeight)
{
    const float firstLineMiddle = text.GetLayoutY() + 0.5f * lineHeight;
    return action.GetLayoutY() <= firstLineMiddle && firstLineMiddle <= Bottom(action);
}

bool Contains(const UIElement& outer, const UIElement& inner)
{
    return inner.GetLayoutX() >= outer.GetLayoutX() - kLayoutTolerance &&
           inner.GetLayoutY() >= outer.GetLayoutY() - kLayoutTolerance &&
           Right(inner) <= Right(outer) + kLayoutTolerance && Bottom(inner) <= Bottom(outer) + kLayoutTolerance;
}

} // namespace

TEST(InspectorNotice, ShowsItsTextAndFiresItsAction)
{
    InspectorNotice notice("Generated by Garden Path.");

    Label* text = TextOf(notice);
    Button* action = ActionOf(notice);
    ASSERT_NE(text, nullptr) << "the notice's text is not in the tree; InspectorNotice.uxml is staged beside "
                                "the test executable under Assets/UI/controls/InspectorNotice/";
    ASSERT_NE(action, nullptr);
    EXPECT_EQ(text->GetText(), "Generated by Garden Path.");
    EXPECT_TRUE(action->HasClass("hidden")) << "a notice with nothing to do shows no button";

    int invoked = 0;
    notice.SetAction("Select owner", "Select Garden Path", [&invoked]() { ++invoked; });

    EXPECT_FALSE(action->HasClass("hidden"));
    EXPECT_EQ(action->GetText(), "Select owner");
    EXPECT_EQ(action->GetTooltip(), "Select Garden Path");
    Click(*action);
    EXPECT_EQ(invoked, 1) << "the button has to reach the action it was given";
}

// Focus is tracked by element id, so two notices whose actions shared one would hand the keyboard
// to the first whichever was focused: Tab to the second notice's Discard and Enter discards the
// first field.
// A notice is a warning unless it is built to inform; each kind carries its own class, which the
// stylesheet paints.
TEST(InspectorNotice, TheKindIsOneClassOnTheControl)
{
    InspectorNotice warning("Authored value could not be read.");
    InspectorNotice information("The sky sets this light's direction.", InspectorNotice::Kind::Information);
    EXPECT_TRUE(warning.HasClass("inspector-notice-warning"));
    EXPECT_FALSE(warning.HasClass("inspector-notice-information"));
    EXPECT_TRUE(information.HasClass("inspector-notice-information"));
    EXPECT_FALSE(information.HasClass("inspector-notice-warning"));
}

TEST(InspectorNotice, EachActionIsAFocusTargetOfItsOwn)
{
    auto root = std::make_unique<UIElement>();
    auto first = std::make_unique<InspectorNotice>("Authored value \"Cantilevered\" for SpanGrade could not be read.");
    auto second = std::make_unique<InspectorNotice>("Authored value \"0xdecaf\" for Seed could not be read.");
    first->SetAction("Discard preserved value", "", []() {});
    second->SetAction("Discard preserved value", "", []() {});
    Button* secondAction = ActionOf(*second);
    ASSERT_NE(secondAction, nullptr);
    root->AddChild(std::move(first));
    root->AddChild(std::move(second));

    InspectorLayoutFixture fixture;
    if (!fixture.Build(std::move(root)))
        GTEST_SKIP() << fixture.Diagnostic;

    fixture.Ui->FocusElement(secondAction);
    const std::string& focusedId = fixture.Ui->GetFocusedElementId();
    ASSERT_FALSE(focusedId.empty());
    EXPECT_EQ(fixture.Ui->GetRootElement()->FindById(focusedId), secondAction)
        << "the focus resolves to another notice's action (id '" << focusedId << "')";
}

// With an action, the button is inside the plate, at the end of the text's row and as wide as its
// label; without one, the plate is the text and its padding, with no gap left for a button that is not
// there.
TEST(InspectorNoticeLayout, TheActionSitsAtTheEndOfTheTextsRowAndTakesNoSpaceWithoutOne)
{
    auto root = std::make_unique<UIElement>();
    auto withAction = std::make_unique<InspectorNotice>("Authored value \"Cantilevered\" could not be read.");
    auto withoutAction = std::make_unique<InspectorNotice>("Authored value \"Cantilevered\" could not be read.");
    withAction->SetAction("Discard preserved value", "", []() {});
    InspectorNotice* withRaw = withAction.get();
    InspectorNotice* withoutRaw = withoutAction.get();
    root->AddChild(std::move(withAction));
    root->AddChild(std::move(withoutAction));

    InspectorLayoutFixture fixture;
    fixture.ViewportW = 600;
    fixture.ExtraSheets = kNoticeSheets;
    if (!fixture.Build(std::move(root)))
        GTEST_SKIP() << fixture.Diagnostic;

    UIElement* plate = FindByClass(withRaw, "inspector-notice-plate");
    UIElement* barePlate = FindByClass(withoutRaw, "inspector-notice-plate");
    ASSERT_NE(plate, nullptr);
    ASSERT_NE(barePlate, nullptr);
    Label* text = TextOf(*withRaw);
    Button* action = ActionOf(*withRaw);
    ASSERT_NE(text, nullptr);
    ASSERT_NE(action, nullptr);
    ASSERT_GT(text->GetLayoutHeight(), 0.0f) << "no text measured, so nothing below can be judged";

    EXPECT_TRUE(Contains(*plate, *text));
    EXPECT_TRUE(Contains(*plate, *action)) << "the action has to sit on the plate it belongs to";
    EXPECT_GE(action->GetLayoutX(), Right(*text)) << "the action follows the text on its row";
    EXPECT_TRUE(OnFirstLine(*action, *text, text->GetLayoutHeight())) << "the action sits on the text's line";
    EXPECT_NEAR(Right(*plate) - Right(*action), text->GetLayoutX() - plate->GetLayoutX(), kLayoutTolerance)
        << "the action ends the row, as far from the plate's right edge as the text is from its left";
    EXPECT_LT(action->GetLayoutWidth(), plate->GetLayoutWidth() / 2.0f)
        << "the action is as wide as its label, not stretched across the plate";

    Label* bareText = TextOf(*withoutRaw);
    ASSERT_NE(bareText, nullptr);
    EXPECT_EQ(ActionOf(*withoutRaw)->GetLayoutHeight(), 0.0f);
    EXPECT_NEAR(Bottom(*barePlate) - Bottom(*bareText), bareText->GetLayoutY() - barePlate->GetLayoutY(),
                kLayoutTolerance)
        << "a notice without an action still makes room for one";
}

// A narrow inspector wraps the text onto several lines inside the plate, beside its action, which
// stays on the first line; nothing runs past the plate's edge or out of the panel.
TEST(InspectorNoticeLayout, ALongTextWrapsInsideThePlateBesideItsAction)
{
    auto root = std::make_unique<UIElement>();
    auto oneLine = std::make_unique<InspectorNotice>("Generated.");
    auto wrapped = std::make_unique<InspectorNotice>(kLongText);
    wrapped->SetAction("Select owner", "", []() {});
    InspectorNotice* oneLineRaw = oneLine.get();
    InspectorNotice* wrappedRaw = wrapped.get();
    root->AddChild(std::move(oneLine));
    root->AddChild(std::move(wrapped));

    InspectorLayoutFixture fixture;
    fixture.ViewportW = 360;
    fixture.ExtraSheets = kNoticeSheets;
    if (!fixture.Build(std::move(root)))
        GTEST_SKIP() << fixture.Diagnostic;

    Label* lineText = TextOf(*oneLineRaw);
    Label* text = TextOf(*wrappedRaw);
    UIElement* plate = FindByClass(wrappedRaw, "inspector-notice-plate");
    ASSERT_NE(lineText, nullptr);
    ASSERT_NE(text, nullptr);
    ASSERT_NE(plate, nullptr);
    const float lineHeight = lineText->GetLayoutHeight();
    ASSERT_GT(lineHeight, 0.0f) << "no text measured, so a wrap cannot be told from a fixture without a font";

    EXPECT_GE(text->GetLayoutHeight(), 2.0f * lineHeight) << "the long text did not wrap";
    EXPECT_TRUE(Contains(*plate, *text)) << "the text runs past its plate";
    EXPECT_TRUE(Contains(*plate, *ActionOf(*wrappedRaw)));
    EXPECT_GE(ActionOf(*wrappedRaw)->GetLayoutX(), Right(*text)) << "the action sits beside the text";
    EXPECT_TRUE(OnFirstLine(*ActionOf(*wrappedRaw), *text, lineHeight)) << "the action sits on the first line";
    EXPECT_LE(Right(*plate), static_cast<float>(fixture.ViewportW) + kLayoutTolerance)
        << "the plate runs out of the panel";
}

// Where the row cannot give the text its basis beside the action, the action takes a line of its own
// under the text, still at the row's end, rather than squeezing the text into a column of fragments;
// in a panel narrower than that basis the text shrinks to the panel and nothing runs past its edge.
TEST(InspectorNoticeLayout, WithNoRoomBesideTheTextTheActionWrapsUnderIt)
{
    for (const int viewportWidth : {150, 300})
    {
        auto root = std::make_unique<UIElement>();
        auto notice = std::make_unique<InspectorNotice>(kLongText);
        notice->SetAction("Select owner", "", []() {});
        InspectorNotice* noticeRaw = notice.get();
        root->AddChild(std::move(notice));

        InspectorLayoutFixture fixture;
        fixture.ViewportW = viewportWidth;
        fixture.ExtraSheets = kNoticeSheets;
        if (!fixture.Build(std::move(root)))
            GTEST_SKIP() << fixture.Diagnostic;

        Label* text = TextOf(*noticeRaw);
        Button* action = ActionOf(*noticeRaw);
        UIElement* plate = FindByClass(noticeRaw, "inspector-notice-plate");
        ASSERT_NE(text, nullptr);
        ASSERT_NE(action, nullptr);
        ASSERT_NE(plate, nullptr);
        ASSERT_GT(text->GetLayoutHeight(), 0.0f) << "no text measured, so nothing below can be judged";

        EXPECT_GE(action->GetLayoutY(), Bottom(*text) - kLayoutTolerance)
            << "the action goes under the text at " << viewportWidth << " px";
        EXPECT_NEAR(Right(*plate) - Right(*action), text->GetLayoutX() - plate->GetLayoutX(), kLayoutTolerance)
            << "the wrapped action stays at the row's end at " << viewportWidth << " px";
        EXPECT_TRUE(Contains(*plate, *text)) << "the text runs past its plate at " << viewportWidth << " px";
        EXPECT_TRUE(Contains(*plate, *action));
        EXPECT_LE(Right(*plate), static_cast<float>(viewportWidth) + kLayoutTolerance)
            << "the plate runs out of the panel at " << viewportWidth << " px";
    }
}

// An inspector can be rebuilt inside an event dispatch, where moving an element between parents is
// refused; a notice built there still carries its text and its action.
TEST(InspectorNotice, ANoticeBuiltInsideADispatchHasItsTextAndAction)
{
    UIElement::SetInEventDispatch(true);
    auto notice = std::make_unique<InspectorNotice>("Built inside a dispatch.");
    UIElement::SetInEventDispatch(false);

    Label* text = TextOf(*notice);
    ASSERT_NE(text, nullptr) << "a notice built inside a dispatch has no text";
    EXPECT_EQ(text->GetText(), "Built inside a dispatch.");
    EXPECT_NE(ActionOf(*notice), nullptr);
}

namespace
{

// A notice whose action rebuilds the notice's parent, as Discard and Select owner rebuild the
// inspector, and which records when it is destroyed.
class RecordedNotice : public InspectorNotice
{
public:
    RecordedNotice(const std::string& text, bool& destroyed)
        : InspectorNotice(text)
        , m_Destroyed(destroyed)
    {
    }
    ~RecordedNotice() override { m_Destroyed = true; }

private:
    bool& m_Destroyed;
};

struct RebuildingAction
{
    bool Destroyed = false;
    bool DestroyedInsideAction = true;
    int Invoked = 0;
    UIElement* Root = nullptr;
    Button* Action = nullptr;
    InspectorLayoutFixture Fixture;

    bool Build()
    {
        auto root = std::make_unique<UIElement>();
        Root = root.get();
        auto notice = std::make_unique<RecordedNotice>("Generated by Garden Path.", Destroyed);
        notice->SetAction("Select owner", "", [this]() { Rebuild(); });
        Action = ActionOf(*notice);
        root->AddChild(std::move(notice));
        Fixture.ExtraSheets = kNoticeSheets;
        return Fixture.Build(std::move(root));
    }

    void Rebuild()
    {
        ++Invoked;
        Root->RemoveAllChildren();
        Root->AddChild(std::make_unique<InspectorNotice>("Rebuilt."));
        DestroyedInsideAction = Destroyed;
    }

    void Settle()
    {
        constexpr int kFrames = 3;
        for (int i = 0; i < kFrames; ++i)
            Fixture.Ui->Update(1.0f / 60.0f, /*interactive=*/true);
    }

    std::string RebuiltText() const
    {
        if (Root->GetChildren().size() != 1u)
            return "<" + std::to_string(Root->GetChildren().size()) + " children>";
        Label* text = TextOf(*Root->GetChildren()[0]);
        return text ? text->GetText() : std::string("<no text>");
    }
};

} // namespace

// The action's own press and the Enter on its focused button both run inside a UI dispatch, which
// defers the rebuild's removal: the notice outlives the action it is running, and the notice the
// rebuild makes carries its text.
TEST(InspectorNotice, AnActionThatRebuildsItsNoticeOutlivesItsPressAndItsEnter)
{
    RebuildingAction pressed;
    if (!pressed.Build())
        GTEST_SKIP() << pressed.Fixture.Diagnostic;
    ASSERT_NE(pressed.Action, nullptr);
    pressed.Fixture.Ui->OnMouseMove(pressed.Action->GetLayoutX() + pressed.Action->GetLayoutWidth() * 0.5f,
                                    pressed.Action->GetLayoutY() + pressed.Action->GetLayoutHeight() * 0.5f);
    pressed.Fixture.Ui->Update(1.0f / 60.0f, /*interactive=*/true);
    pressed.Fixture.Ui->OnMouseButton(0, true);
    pressed.Fixture.Ui->OnMouseButton(0, false);
    EXPECT_EQ(pressed.Invoked, 1) << "a press and release did not reach the action";
    EXPECT_FALSE(pressed.DestroyedInsideAction) << "the notice was destroyed under its own press";
    pressed.Settle();
    EXPECT_TRUE(pressed.Destroyed) << "the rebuild never removed the old notice";
    EXPECT_EQ(pressed.RebuiltText(), "Rebuilt.");

    RebuildingAction entered;
    if (!entered.Build())
        GTEST_SKIP() << entered.Fixture.Diagnostic;
    ASSERT_NE(entered.Action, nullptr);
    entered.Fixture.Ui->FocusElement(entered.Action);
    entered.Fixture.Ui->OnKey(GameEngine::Input::kKeyCode_Enter, 1, 0);
    entered.Fixture.Ui->OnKey(GameEngine::Input::kKeyCode_Enter, 0, 0);
    EXPECT_EQ(entered.Invoked, 1) << "Enter on the focused action did not reach it";
    EXPECT_FALSE(entered.DestroyedInsideAction) << "the notice was destroyed under its own Enter";
    entered.Settle();
    EXPECT_EQ(entered.RebuiltText(), "Rebuilt.");
}

namespace
{

struct ColumnHeights
{
    bool Built = false;
    float Notice = 0.0f;
    float Plate = 0.0f;
    float Text = 0.0f;
};

// A notice between twelve wrapping sibling rows in a column `columnHeight` px tall, at 360 px.
ColumnHeights LayOutAColumn(uint32_t columnHeight)
{
    auto root = std::make_unique<UIElement>();
    auto columnOwned = std::make_unique<UIElement>();
    columnOwned->AddClass("test-column");
    UIElement* column = columnOwned.get();
    root->AddChild(std::move(columnOwned));
    constexpr int kSiblingsEachSide = 6;
    for (int i = 0; i < kSiblingsEachSide; ++i)
    {
        auto sibling = std::make_unique<Label>();
        sibling->SetText("A sibling row whose text wraps onto a second line at a narrow inspector width.");
        column->AddChild(std::move(sibling));
    }
    auto notice = std::make_unique<InspectorNotice>(
        "Rule 3 holds the maximum of 8 conditions. To narrow it further, split it into a second rule "
        "targeting the same material - the two rules' weights add.");
    notice->SetAction("Discard preserved value", "", []() {});
    InspectorNotice* raw = notice.get();
    column->AddChild(std::move(notice));
    for (int i = 0; i < kSiblingsEachSide; ++i)
    {
        auto sibling = std::make_unique<Label>();
        sibling->SetText("Another sibling row competing for the same column height.");
        column->AddChild(std::move(sibling));
    }

    InspectorLayoutFixture fixture;
    fixture.ViewportW = 360;
    fixture.ViewportH = 4000;
    fixture.ExtraSheets = kNoticeSheets;
    ColumnHeights heights;
    if (!fixture.Build(std::move(root)))
        return heights;
    GameEngine::Stylesheet sheet{};
    const std::string css = ".test-column { display: flex; flex-direction: column; height: " +
                            std::to_string(columnHeight) + "px; overflow: hidden; }";
    if (!GameEngine::UIParsing::CSSParser::ParseStylesFromString(css, sheet))
        return heights;
    sheet.SourceName = "test-column";
    fixture.Ui->AddStylesheet(std::make_shared<const GameEngine::Stylesheet>(std::move(sheet)));
    constexpr int kSettleFrames = 4;
    for (int i = 0; i < kSettleFrames; ++i)
        fixture.Ui->Update(1.0f / 60.0f, /*interactive=*/true);

    UIElement* plate = FindByClass(raw, "inspector-notice-plate");
    Label* text = TextOf(*raw);
    heights.Built = true;
    heights.Notice = raw->GetLayoutHeight();
    heights.Plate = plate ? plate->GetLayoutHeight() : -1.0f;
    heights.Text = text ? text->GetLayoutHeight() : -1.0f;
    return heights;
}

} // namespace

// A crowded column shrinks its rows to fit; a notice keeps its full height there, as in a roomy one,
// rather than shrinking to a sliver that shows the tops of its first line.
TEST(InspectorNoticeLayout, ACrowdedColumnDoesNotSqueezeTheNotice)
{
    constexpr uint32_t kRoomy = 4000;
    constexpr uint32_t kCrowded = 120;
    const ColumnHeights roomy = LayOutAColumn(kRoomy);
    const ColumnHeights crowded = LayOutAColumn(kCrowded);
    if (!roomy.Built || !crowded.Built)
        GTEST_SKIP() << "no Vulkan device";
    ASSERT_GT(roomy.Text, 0.0f) << "no text measured, so a squeeze cannot be told from a fixture without a font";

    EXPECT_NEAR(crowded.Notice, roomy.Notice, kLayoutTolerance) << "the notice shrank in a crowded column";
    EXPECT_NEAR(crowded.Plate, roomy.Plate, kLayoutTolerance) << "the plate shrank in a crowded column";
    EXPECT_NEAR(crowded.Text, roomy.Text, kLayoutTolerance) << "the text shrank in a crowded column";
}
