#include "Rendering/Materials/MaterialDocument.h"
#include "Rendering/ShaderGraph/SgGlslSignatureReader.h"
#include "Rendering/ShaderGraph/SgGraphCompiler.h"
#include "Rendering/ShaderGraph/SgGraphFileIO.h"
#include "Rendering/ShaderGraph/SgNodeReflector.h"
#include "Rendering/ShaderGraph/SgPropertyBinding.h"
#include "Rendering/ShaderGraph/SgPseudoNodes.h"
#include "Rendering/ShaderGraph/SgTagParser.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>

using namespace GameEngine::ShaderGraph;

TEST(ShaderGraphCompilerTests, DetectsShaderGraphAfterPreambleComments)
{
    const char* source = R"(// Auto-generated. The @sg-* tag block is authoritative.
// The body below is regenerated by the graph editor on save.
//
// @sg-graph     GraphSampleRed
// @sg-version   1
)";
    EXPECT_TRUE(IsShaderGraphSource(source));
}

TEST(ShaderGraphCompilerTests, ParsesGraphTags)
{
    const char* source = R"(// @sg-graph     TestGraph
// @sg-version   1
// @sg-node      n0 type=FloatConstant pos=(0,0) value=1.0
// @sg-node      out type=SurfaceOutput pos=(200,0)
// @sg-edge      n0.value -> out.BaseColor
)";
    ASSERT_TRUE(IsShaderGraphSource(source));
    const auto doc = ParseGraphDocumentFromTags(ParseShaderGraphSource(source).TagBlock);
    EXPECT_EQ(doc.GraphName, "TestGraph");
    ASSERT_EQ(doc.Nodes.size(), 2u);
}

TEST(ShaderGraphCompilerTests, MaterializedTagRoundTrips)
{
    // A materialized (built) surface carries the semantic tags of its graph
    // and no nodes; the tag is what tells a reader not to compile it again.
    SgGraphDocument doc;
    doc.GraphName = "Built";
    doc.Materialized = true;
    const std::string text = SerializeGraphFileText(doc, "void EvaluateSurface() {}\n");
    EXPECT_NE(text.find("// @sg-materialized true"), std::string::npos);
    ASSERT_TRUE(IsShaderGraphSource(text));
    const auto parsed = ParseGraphDocumentFromTags(ParseShaderGraphSource(text).TagBlock);
    EXPECT_TRUE(parsed.Materialized);
    EXPECT_TRUE(parsed.Nodes.empty());

    SgGraphDocument authored;
    authored.GraphName = "Authored";
    const std::string authoredText = SerializeGraphFileText(authored, "");
    EXPECT_EQ(authoredText.find("@sg-materialized"), std::string::npos);
    EXPECT_FALSE(ParseGraphDocumentFromTags(ParseShaderGraphSource(authoredText).TagBlock).Materialized);
}

TEST(ShaderGraphCompilerTests, CompilesSimpleGraph)
{
    SgGraphDocument doc;
    doc.GraphName = "Simple";
    doc.Nodes.push_back({"n0", "FloatConstant", 0.f, 0.f, {{"value", "0.5"}}});
    doc.Nodes.push_back({"out", "SurfaceOutput", 200.f, 0.f, {}});
    doc.Edges.push_back({"n0", "value", "out", "BaseColor"});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    EXPECT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    EXPECT_NE(result.Body.find("EvaluateSurface"), std::string::npos);
}

TEST(ShaderGraphCompilerTests, VertexAndSurfaceEntryPointsAreStageGuarded)
{
    SgGraphDocument doc;
    doc.GraphName = "VertexOffset";
    doc.Nodes.push_back({"n0", "FloatConstant", 0.f, 0.f, {{"value", "0.25"}}});
    doc.Nodes.push_back({"out", "SurfaceOutput", 200.f, 0.f, {}});
    doc.Nodes.push_back({"vout", "VertexOutput", 200.f, 200.f, {}});
    doc.Edges.push_back({"n0", "value", "vout", "PositionOffset"});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);

    // One file serves both adapters, so each entry point hides from the other stage.
    const size_t surfaceGuard = result.Body.find("#ifndef GE_STAGE_VERTEX");
    const size_t surfaceFn = result.Body.find("SurfaceOutput EvaluateSurface(");
    const size_t vertexGuard = result.Body.find("#ifdef GE_STAGE_VERTEX");
    const size_t vertexFn = result.Body.find("vec3 ModifyVertex(");
    ASSERT_NE(surfaceGuard, std::string::npos);
    ASSERT_NE(surfaceFn, std::string::npos);
    ASSERT_NE(vertexGuard, std::string::npos);
    ASSERT_NE(vertexFn, std::string::npos);
    EXPECT_LT(surfaceGuard, surfaceFn);
    EXPECT_LT(vertexGuard, vertexFn);
    EXPECT_NE(std::find(result.VariantDefines.begin(), result.VariantDefines.end(), "HAS_VERTEX_MODIFIER"),
              result.VariantDefines.end());
}

TEST(ShaderGraphCompilerTests, FragmentOnlyEngineInputIntoVertexPosIsAGraphError)
{
    SgGraphDocument doc;
    doc.GraphName = "BadVertexInput";
    doc.Nodes.push_back({"in", "EngineInput", 0.f, 0.f, {}});
    doc.Nodes.push_back({"out", "SurfaceOutput", 200.f, 0.f, {}});
    doc.Nodes.push_back({"vout", "VertexOutput", 200.f, 200.f, {}});
    doc.Edges.push_back({"in", "WorldNormal", "vout", "PositionOffset"});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    EXPECT_FALSE(result.Success);
    ASSERT_FALSE(result.Errors.empty());
    EXPECT_NE(result.Errors.front().Message.find("not available in the vertex stage"), std::string::npos)
        << result.Errors.front().Message;
    // The interpolated surface inputs never reach the vertex body.
    const size_t vertexFn = result.Body.find("vec3 ModifyVertex(");
    ASSERT_NE(vertexFn, std::string::npos);
    EXPECT_EQ(result.Body.find("sIn.", vertexFn), std::string::npos);
}

TEST(ShaderGraphCompilerTests, VertexStageEngineInputsUseVertexExpressions)
{
    SgGraphDocument doc;
    doc.GraphName = "VertexUboInput";
    doc.Nodes.push_back({"in", "EngineInput", 0.f, 0.f, {}});
    doc.Nodes.push_back({"out", "SurfaceOutput", 200.f, 0.f, {}});
    doc.Nodes.push_back({"vout", "VertexOutput", 200.f, 200.f, {}});
    doc.Edges.push_back({"in", "CameraPosition", "vout", "PositionOffset"});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    const size_t vertexFn = result.Body.find("vec3 ModifyVertex(");
    ASSERT_NE(vertexFn, std::string::npos);
    EXPECT_NE(result.Body.find("Cam.uCameraPos.xyz", vertexFn), std::string::npos);
}

// The Time port is one graph node with two meanings. In the vertex stage it is the endpoint's
// deformation clock — the value the adapter stamped into the InstanceData argument — so the
// same ModifyVertex can run at a second endpoint. A fragment has no endpoint and keeps the
// per-view clock.
TEST(ShaderGraphCompilerTests, TimeIsTheEndpointClockInTheVertexStageAndTheGlobalClockInTheFragmentStage)
{
    SgGraphDocument doc;
    doc.GraphName = "TimeBothStages";
    doc.Nodes.push_back({"in", "EngineInput", 0.f, 0.f, {}});
    doc.Nodes.push_back({"out", "SurfaceOutput", 200.f, 0.f, {}});
    doc.Nodes.push_back({"vout", "VertexOutput", 200.f, 200.f, {}});
    doc.Edges.push_back({"in", "Time", "vout", "PositionOffset"});
    doc.Edges.push_back({"in", "Time", "out", "BaseColor"});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);

    const size_t surfaceFn = result.Body.find("SurfaceOutput EvaluateSurface(");
    const size_t vertexFn = result.Body.find("vec3 ModifyVertex(");
    ASSERT_NE(surfaceFn, std::string::npos);
    ASSERT_NE(vertexFn, std::string::npos);
    ASSERT_LT(surfaceFn, vertexFn) << "the vertex entry point is emitted after the surface one";
    const std::string surfaceBody = result.Body.substr(surfaceFn, vertexFn - surfaceFn);
    const std::string vertexBody = result.Body.substr(vertexFn);

    EXPECT_NE(vertexBody.find("inst.deformationTimeSeconds"), std::string::npos)
        << "the vertex stage must read Time from its InstanceData endpoint";
    EXPECT_EQ(vertexBody.find("Light.uTimeParams"), std::string::npos)
        << "the vertex stage must not read the per-view global clock";
    EXPECT_NE(surfaceBody.find("Light.uTimeParams.x"), std::string::npos)
        << "the fragment stage keeps the per-view clock";
    EXPECT_EQ(surfaceBody.find("deformationTimeSeconds"), std::string::npos)
        << "the fragment stage has no endpoint and no InstanceData argument";
}

TEST(ShaderGraphCompilerTests, RejectsVec3ToVec4WithoutNode)
{
    EXPECT_FALSE(ArePortTypesCompatible("float3", "float4"));
    EXPECT_TRUE(ArePortTypesCompatible("float", "float3"));
}

TEST(ShaderGraphCompilerTests, ParsesPropertyVecDefaultWithCommas)
{
    const auto attrs = ParseTagAttributes("// @sg-property  uTint vec3 default=1, 0.5, 0.2");
    EXPECT_EQ(FindTagAttribute(attrs, "arg0").value_or(""), "uTint");
    EXPECT_EQ(FindTagAttribute(attrs, "arg1").value_or(""), "vec3");
    ASSERT_TRUE(FindTagAttribute(attrs, "default").has_value());
    EXPECT_EQ(*FindTagAttribute(attrs, "default"), "1, 0.5, 0.2");
}

TEST(ShaderGraphCompilerTests, ParsesPropertyAttributesAfterVecDefault)
{
    const auto attrs =
        ParseTagAttributes("// @sg-property  uTiling float default=0.25 range=0,1 hint=slider");
    EXPECT_EQ(FindTagAttribute(attrs, "arg0").value_or(""), "uTiling");
    EXPECT_EQ(FindTagAttribute(attrs, "arg1").value_or(""), "float");
    EXPECT_EQ(FindTagAttribute(attrs, "default").value_or(""), "0.25");
    EXPECT_EQ(FindTagAttribute(attrs, "range").value_or(""), "0,1");
    EXPECT_EQ(FindTagAttribute(attrs, "hint").value_or(""), "slider");
}

TEST(ShaderGraphCompilerTests, ReflectsHelperFileCategoryOntoNodes)
{
    const std::filesystem::path nodesRoot = GetEngineGraphNodesRoot();
    const std::filesystem::path basicPath = nodesRoot / "Math" / "Basic.glsl";
    if (!std::filesystem::exists(basicPath))
        GTEST_SKIP() << "Math/Basic.glsl not present at " << basicPath.string();

    const SgNodeLibraryIndex index = SgNodeReflector::BuildIndex(nodesRoot, {});
    const auto addIt = index.NodesByType.find("Add");
    ASSERT_NE(addIt, index.NodesByType.end());
    EXPECT_EQ(addIt->second.Category, "Math/Basic");
}

TEST(ShaderGraphCompilerTests, ParsesNodePosWithCommaInsideValue)
{
    const auto attrs =
        ParseTagAttributes("// @sg-node      node_color type=ColorConstant pos=(120,140) r=0.08");
    EXPECT_EQ(FindTagAttribute(attrs, "arg0").value_or(""), "node_color");
    EXPECT_EQ(FindTagAttribute(attrs, "type").value_or(""), "ColorConstant");
    EXPECT_EQ(FindTagAttribute(attrs, "pos").value_or(""), "(120,140)");
    EXPECT_EQ(FindTagAttribute(attrs, "r").value_or(""), "0.08");
}

TEST(ShaderGraphCompilerTests, ParsesPropertyPublicFlag)
{
    const auto attrs =
        ParseTagAttributes("// @sg-property  uTiling float default=0.25 public=true");
    EXPECT_EQ(FindTagAttribute(attrs, "arg0").value_or(""), "uTiling");
    EXPECT_EQ(FindTagAttribute(attrs, "public").value_or(""), "true");

    const char* source = R"(// @sg-graph     PropsTest
// @sg-version   1
// @sg-property  uTint vec3 default=1, 0.5, 0.2 public=true
// @sg-property  uHidden float default=0.5
// @sg-node      out type=SurfaceOutput pos=(0,0)
)";
    const auto doc = ParseGraphDocumentFromTags(ParseShaderGraphSource(source).TagBlock);
    ASSERT_EQ(doc.Properties.size(), 2u);
    EXPECT_TRUE(doc.Properties[0].IsPublic);
    EXPECT_FALSE(doc.Properties[1].IsPublic);
}

TEST(ShaderGraphCompilerTests, ParsesGraphPropertyRoundTripInDocument)
{
    const char* source = R"(// @sg-graph     PropsTest
// @sg-version   1
// @sg-property  uTint vec3 default=1, 0.5, 0.2
// @sg-node      out type=SurfaceOutput pos=(0,0)
)";
    const auto doc = ParseGraphDocumentFromTags(ParseShaderGraphSource(source).TagBlock);
    ASSERT_EQ(doc.Properties.size(), 1u);
    EXPECT_EQ(doc.Properties[0].Name, "uTint");
    EXPECT_EQ(doc.Properties[0].Type, "vec3");
    EXPECT_EQ(doc.Properties[0].DefaultValue, "1, 0.5, 0.2");
}

TEST(ShaderGraphCompilerTests, ResolvePublicPropertyBindings)
{
    const auto base = ResolvePublicPropertyBinding("uBaseColor", "vec3");
    ASSERT_TRUE(base.has_value());
    EXPECT_EQ(base->ParameterSlot, 0);
    EXPECT_EQ(base->MaterialPropertyKeys.front(), "baseColor");

    const auto metallic = ResolvePublicPropertyBinding("uMetallic", "float");
    ASSERT_TRUE(metallic.has_value());
    EXPECT_EQ(metallic->ParameterSlot, 1);
    EXPECT_EQ(metallic->FloatComponent, "x");
    EXPECT_EQ(metallic->MaterialPropertyKeys.front(), "metallic");

    const auto rim = ResolvePublicPropertyBinding("uRimColor", "vec3");
    ASSERT_TRUE(rim.has_value());
    EXPECT_EQ(rim->ParameterSlot, 2);
    ASSERT_EQ(rim->MaterialPropertyKeys.size(), 3u);

    EXPECT_FALSE(ResolvePublicPropertyBinding("uCustomTint", "vec3").has_value());
}

TEST(ShaderGraphCompilerTests, ResolveParameterSlotMaterialBindings)
{
    const auto tint = ResolveParameterSlotMaterialBinding(0, "ColorParameter", "x");
    ASSERT_TRUE(tint.has_value());
    EXPECT_EQ(tint->MaterialPropertyKeys.front(), "baseColor");

    const auto roughness = ResolveParameterSlotMaterialBinding(1, "FloatParameter", "y");
    ASSERT_TRUE(roughness.has_value());
    EXPECT_EQ(roughness->MaterialPropertyKeys.front(), "roughness");

    const auto rim = ResolveParameterSlotMaterialBinding(2, "Vec3Parameter", "x");
    ASSERT_TRUE(rim.has_value());
    ASSERT_EQ(rim->MaterialPropertyKeys.size(), 3u);
}

TEST(ShaderGraphCompilerTests, ApplyPublicPropertiesToMaterialDocument)
{
    GameEngine::MaterialDocument doc = GameEngine::MaterialDocument::CreateDefaultPBR("Test");

    SgGraphProperty rim{};
    rim.Name = "uRimColor";
    rim.Type = "vec3";
    rim.DefaultValue = "1.45, 0.48, 0.04";
    rim.IsPublic = true;
    ApplyShaderGraphPropertiesToMaterialDocument({rim}, doc);
    EXPECT_FLOAT_EQ(std::get<float>(doc.properties["flipbookColumns"]), 1.45f);
    EXPECT_FLOAT_EQ(std::get<float>(doc.properties["flipbookRows"]), 0.48f);
    EXPECT_FLOAT_EQ(std::get<float>(doc.properties["flipbookFps"]), 0.04f);
    ASSERT_EQ(doc.shaderGraphPublicProperties.size(), 1u);
    EXPECT_EQ(doc.shaderGraphPublicProperties[0].GraphName, "uRimColor");
    EXPECT_EQ(doc.shaderGraphPublicProperties[0].Type, "vec3");
    ASSERT_EQ(doc.shaderGraphPublicProperties[0].MaterialPropertyKeys.size(), 3u);
    EXPECT_EQ(PrettyGraphPropertyLabel("uRimColor"), "Rim Color");
    EXPECT_TRUE(UsesDedicatedShaderGraphInspectorRow(*ResolvePublicPropertyBinding("uRimColor", "vec3"),
                                                     "uRimColor"));
    EXPECT_FALSE(UsesDedicatedShaderGraphInspectorRow(*ResolvePublicPropertyBinding("uBaseColor", "vec3"),
                                                      "uBaseColor"));

    rim.IsPublic = false;
    ApplyShaderGraphPropertiesToMaterialDocument({rim}, doc);
    EXPECT_EQ(doc.properties.find("flipbookColumns"), doc.properties.end());
    EXPECT_TRUE(doc.shaderGraphPublicProperties.empty());
}

// The signature reader must match EXACT function names only — a name that
// merely starts with the base name (SG_SampleTexture2DLOD vs
// SG_SampleTexture2D) is a different function — and must read parameter
// lists that wrap across lines (SG_SampleTexture2D's do).
TEST(ShaderGraphCompilerTests, SignatureReaderMatchesExactNamesAcrossLines)
{
    const std::string source = R"(
void SG_Sample(sampler2D tex, vec2 uv,
               out vec4 rgba, out vec3 rgb)
{
}
void SG_SampleLOD(sampler2D tex, vec2 uv, float lod, out vec3 rgb)
{
}
vec3 MySG_Sample(vec3 x) { return x; }
// a comment mentioning SG_Sample(with, a, paren) must not read as a signature
vec4 SG_Sample(GE_MaterialTexture tex, vec2 uv)
{
    return vec4(0.0);
}
)";
    const auto overloads = ReadTaggedFunctionOverloads(source, "SG_Sample");
    ASSERT_EQ(overloads.size(), 2u)
        << "exactly the two SG_Sample definitions: no LOD leak, no prefixed name, no comment";

    EXPECT_EQ(overloads[0].Inputs.size(), 2u) << "wrapped parameter list read in full";
    EXPECT_EQ(overloads[0].Outputs.size(), 2u);
    EXPECT_EQ(overloads[0].Inputs[0].GlslType, "sampler2D");

    EXPECT_EQ(overloads[1].Inputs.size(), 2u);
    ASSERT_EQ(overloads[1].Outputs.size(), 1u);
    EXPECT_EQ(overloads[1].Outputs[0].Name, "result");
    EXPECT_EQ(overloads[1].Outputs[0].GlslType, "vec4");

    EXPECT_TRUE(ReadTaggedFunctionOverloads(source, "SG_Sam").empty())
        << "a base name that is only a prefix of real functions matches nothing";
}

// The real library: SampleTexture2D's def must carry its own two overloads
// (sampler2D + the GE_MaterialTexture bridge) with the full 2-in/6-out
// signature — and must NOT contain SampleTexture2DLOD's 3-input signature,
// which the old prefix-substring matcher leaked in while the per-line reader
// dropped the real (wrapped) ones.
TEST(ShaderGraphCompilerTests, SampleTexture2DDefCarriesItsOwnOverloadsOnly)
{
    const std::filesystem::path nodesRoot = GetEngineGraphNodesRoot();
    if (!std::filesystem::exists(nodesRoot / "Sampling" / "Texture.glsl"))
        GTEST_SKIP() << "Sampling/Texture.glsl not present under " << nodesRoot.string();

    const SgNodeLibraryIndex index = SgNodeReflector::BuildIndex(nodesRoot, {});
    const auto it = index.NodesByType.find("SampleTexture2D");
    ASSERT_NE(it, index.NodesByType.end());
    ASSERT_EQ(it->second.Overloads.size(), 2u);
    for (const auto& o : it->second.Overloads)
    {
        EXPECT_EQ(o.Inputs.size(), 2u) << "a 3-input entry is the LOD signature leaking in";
        EXPECT_EQ(o.Outputs.size(), 6u) << "rgba/rgb/r/g/b/a";
    }
    EXPECT_EQ(it->second.Overloads[0].Inputs[0].GlslType, "sampler2D")
        << "front overload feeds the editor palette ports";
    EXPECT_EQ(it->second.Overloads[1].Inputs[0].GlslType, "GE_MaterialTexture");

    const auto lodIt = index.NodesByType.find("SampleTexture2DLOD");
    ASSERT_NE(lodIt, index.NodesByType.end());
    ASSERT_EQ(lodIt->second.Overloads.size(), 2u);
    for (const auto& o : lodIt->second.Overloads)
    {
        EXPECT_EQ(o.Inputs.size(), 3u);
        EXPECT_EQ(o.Outputs.size(), 1u);
    }
}

// End-to-end: a SampleTexture2D graph emits a call matching the REAL 8-arg
// signature (with the polluted def it emitted a nonexistent 3-arg call).
TEST(ShaderGraphCompilerTests, CompilesSampleTexture2DGraphAgainstRealSignature)
{
    SgGraphDocument doc;
    doc.GraphName = "TexSample";
    doc.Nodes.push_back({"t0", "SampleTexture2D", 0.f, 0.f, {}});
    doc.Nodes.push_back({"out", "SurfaceOutput", 200.f, 0.f, {}});
    doc.Edges.push_back({"t0", "rgb", "out", "BaseColor"});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    const size_t callPos = result.Body.find("SG_SampleTexture2D(");
    ASSERT_NE(callPos, std::string::npos);
    const size_t callEnd = result.Body.find(')', callPos);
    ASSERT_NE(callEnd, std::string::npos);
    const std::string call = result.Body.substr(callPos, callEnd - callPos);
    EXPECT_EQ(std::count(call.begin(), call.end(), ','), 7) << "8-arg call: " << call;
}


// The graph-material compile path regenerates <stem>_built.glsl on EVERY
// compile. The shader-edit watcher keys on the file changing, so a rewrite of
// identical bytes re-arms it and the recompile rewrites the file again — a
// self-sustaining recompile loop on an idle editor. "No write when bytes are
// unchanged" is the invariant that breaks the cycle; the watcher-visible
// observable is the file's last-write time, so that is what this test ports.
TEST(ShaderGraphCompilerTests, SaveGraphFileSkipsRewriteWhenContentUnchanged)
{
    namespace fs = std::filesystem;
    const fs::path path =
        fs::temp_directory_path() /
        ("ge_sg_save_norewrite_" +
         std::to_string(::testing::UnitTest::GetInstance()->random_seed()) + ".glsl");
    std::error_code ec;
    fs::remove(path, ec);

    SgGraphDocument doc;
    doc.GraphName = "NoRewrite";
    const std::string body =
        "SurfaceOutput EvaluateSurface(SurfaceInput sIn) { return DefaultSurfaceOutput(); }\n";

    ASSERT_TRUE(SaveGraphFile(path, doc, body));
    const auto firstWrite = fs::last_write_time(path);

    // Sleep past filesystem timestamp granularity so an unwanted rewrite is
    // guaranteed to move the mtime.
    std::this_thread::sleep_for(std::chrono::milliseconds(150));

    ASSERT_TRUE(SaveGraphFile(path, doc, body));
    EXPECT_EQ(fs::last_write_time(path), firstWrite)
        << "identical content was rewritten (mtime advanced) — this re-arms the "
           "shader-edit watcher and loops";

    // Changed content must still be written; prove it by readback, not mtime.
    ASSERT_TRUE(SaveGraphFile(path, doc, body + "// changed\n"));
    std::ifstream in(path);
    const std::string onDisk((std::istreambuf_iterator<char>(in)),
                             std::istreambuf_iterator<char>());
    EXPECT_NE(onDisk.find("// changed"), std::string::npos);

    fs::remove(path, ec);
}

// ---- Minimal walkthrough examples: smallest v2 tag-block graph that parses
// ---- AND compiles, and one mutation of it that fails with a real error.

namespace {
const char* kMinimalGraphSource = R"(// @sg-graph     MinimalRed
// @sg-version   1
// @sg-stage     surface
// @sg-lighting  StandardPBR
// @sg-node      c0  type=ColorConstant  pos=(0,0)  r=1.0 g=0.0 b=0.0
// @sg-node      out type=SurfaceOutput  pos=(240,0)
// @sg-edge      c0.value -> out.BaseColor
)";
}

TEST(ShaderGraphCompilerTests, MinimalExample_GraphParsesAndCompiles)
{
    ASSERT_TRUE(IsShaderGraphSource(kMinimalGraphSource));
    const auto doc =
        ParseGraphDocumentFromTags(ParseShaderGraphSource(kMinimalGraphSource).TagBlock);
    EXPECT_EQ(doc.GraphName, "MinimalRed");
    EXPECT_EQ(doc.LightingModel, "StandardPBR");
    ASSERT_EQ(doc.Nodes.size(), 2u);
    ASSERT_EQ(doc.Edges.size(), 1u);

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    EXPECT_NE(result.Body.find("EvaluateSurface"), std::string::npos);
    EXPECT_NE(result.Body.find("SG_ColorConstant("), std::string::npos) << result.Body;
    std::cout << "[minimal graph] compiled body:\n" << result.Body << "\n";
}

TEST(ShaderGraphCompilerTests, MinimalExample_UnknownNodeType_FailsWithRealError)
{
    std::string mutated = kMinimalGraphSource;
    const std::string from = "ColorConstant";
    const size_t pos = mutated.find(from);
    ASSERT_NE(pos, std::string::npos);
    mutated.replace(pos, from.size(), "BogusConstant");

    const auto doc = ParseGraphDocumentFromTags(ParseShaderGraphSource(mutated).TagBlock);
    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    EXPECT_FALSE(result.Success);
    ASSERT_FALSE(result.Errors.empty());
    std::cout << "[mutated graph] compiler error: " << result.Errors.front().Message << "\n";
    EXPECT_NE(result.Errors.front().Message.find("unknown node type"), std::string::npos);
}

// ---- Positional single-value tags. @sg-lighting / @sg-variant carry their value
// ---- as a bare token, exactly as SerializeGraphDocumentTags writes it, so parse
// ---- and serialize must round-trip.

TEST(ShaderGraphCompilerTests, ParsesPositionalLightingModel)
{
    const char* source = R"(// @sg-graph     UnlitGraph
// @sg-version   1
// @sg-stage     surface
// @sg-lighting  Unlit
// @sg-node      c0  type=ColorConstant  pos=(0,0)  r=1.0 g=0.0 b=0.0
// @sg-node      out type=SurfaceOutput  pos=(240,0)
// @sg-edge      c0.value -> out.BaseColor
)";
    const auto doc = ParseGraphDocumentFromTags(ParseShaderGraphSource(source).TagBlock);
    EXPECT_EQ(doc.LightingModel, "Unlit");
}

TEST(ShaderGraphCompilerTests, ParsesPositionalVariantDefines)
{
    const char* source = R"(// @sg-graph     VariantGraph
// @sg-version   1
// @sg-variant   GE_USER_SNOW
// @sg-variant   GE_USER_WETNESS
// @sg-node      out type=SurfaceOutput pos=(0,0)
)";
    const auto doc = ParseGraphDocumentFromTags(ParseShaderGraphSource(source).TagBlock);
    ASSERT_EQ(doc.VariantDefines.size(), 2u);
    EXPECT_EQ(doc.VariantDefines[0], "GE_USER_SNOW");
    EXPECT_EQ(doc.VariantDefines[1], "GE_USER_WETNESS");
}

TEST(ShaderGraphCompilerTests, SerializeThenParseRoundTripsLightingAndVariants)
{
    SgGraphDocument doc;
    doc.GraphName = "RoundTrip";
    doc.LightingModel = "Unlit";
    doc.VariantDefines = {"GE_USER_SNOW"};
    SgGraphNode sink;
    sink.Id = "out";
    sink.TypeId = "SurfaceOutput";
    doc.Nodes.push_back(sink);

    const std::string serialized = SerializeGraphDocumentTags(doc);
    const auto reparsed = ParseGraphDocumentFromTags(serialized);

    EXPECT_EQ(reparsed.GraphName, "RoundTrip");
    EXPECT_EQ(reparsed.LightingModel, "Unlit") << serialized;
    ASSERT_EQ(reparsed.VariantDefines.size(), 1u) << serialized;
    EXPECT_EQ(reparsed.VariantDefines[0], "GE_USER_SNOW");
}

TEST(ShaderGraphCompilerTests, SerializeEmitsStandardPBRLightingTag)
{
    SgGraphDocument doc;
    doc.GraphName = "LightingKeep";
    doc.LightingModel = "StandardPBR";

    const std::string serialized = SerializeGraphDocumentTags(doc);
    EXPECT_NE(serialized.find("// @sg-lighting  StandardPBR"), std::string::npos) << serialized;
}

TEST(ShaderGraphCompilerTests, UnknownTagsSurviveSerializeRoundTrip)
{
    const char* source = R"(// @sg-graph     ForwardCompat
// @sg-version   1
// @sg-stage     surface
// @sg-futuretag mode=fancy strength=2.0
// @sg-node      out type=SurfaceOutput pos=(0,0)
)";
    const auto doc = ParseGraphDocumentFromTags(ParseShaderGraphSource(source).TagBlock);
    ASSERT_EQ(doc.UnknownTags.size(), 1u);
    EXPECT_EQ(doc.UnknownTags[0], "// @sg-futuretag mode=fancy strength=2.0");

    const std::string serialized = SerializeGraphDocumentTags(doc);
    EXPECT_NE(serialized.find("// @sg-futuretag mode=fancy strength=2.0"), std::string::npos)
        << serialized;

    const auto reparsed = ParseGraphDocumentFromTags(serialized);
    ASSERT_EQ(reparsed.UnknownTags.size(), 1u);
    EXPECT_EQ(reparsed.UnknownTags[0], "// @sg-futuretag mode=fancy strength=2.0");
}

namespace {
void ExpectSameGraphDocument(const SgGraphDocument& a, const SgGraphDocument& b,
                             const std::string& context)
{
    EXPECT_EQ(a.GraphName, b.GraphName) << context;
    EXPECT_EQ(a.Version, b.Version) << context;
    EXPECT_EQ(a.Stage, b.Stage) << context;
    EXPECT_EQ(a.LightingModel, b.LightingModel) << context;
    EXPECT_EQ(a.VariantDefines, b.VariantDefines) << context;
    EXPECT_EQ(a.UnknownTags, b.UnknownTags) << context;
    EXPECT_FLOAT_EQ(a.ViewportPanX, b.ViewportPanX) << context;
    EXPECT_FLOAT_EQ(a.ViewportPanY, b.ViewportPanY) << context;
    EXPECT_FLOAT_EQ(a.ViewportZoom, b.ViewportZoom) << context;

    ASSERT_EQ(a.Properties.size(), b.Properties.size()) << context;
    for (size_t i = 0; i < a.Properties.size(); ++i)
    {
        EXPECT_EQ(a.Properties[i].Name, b.Properties[i].Name) << context;
        EXPECT_EQ(a.Properties[i].Type, b.Properties[i].Type) << context;
        EXPECT_EQ(a.Properties[i].DefaultValue, b.Properties[i].DefaultValue) << context;
        EXPECT_EQ(a.Properties[i].RangeMin, b.Properties[i].RangeMin) << context;
        EXPECT_EQ(a.Properties[i].RangeMax, b.Properties[i].RangeMax) << context;
        EXPECT_EQ(a.Properties[i].Hint, b.Properties[i].Hint) << context;
        EXPECT_EQ(a.Properties[i].IsPublic, b.Properties[i].IsPublic) << context;
    }

    ASSERT_EQ(a.Textures.size(), b.Textures.size()) << context;
    for (size_t i = 0; i < a.Textures.size(); ++i)
    {
        EXPECT_EQ(a.Textures[i].Name, b.Textures[i].Name) << context;
        EXPECT_EQ(a.Textures[i].Guid, b.Textures[i].Guid) << context;
        EXPECT_EQ(a.Textures[i].Hint, b.Textures[i].Hint) << context;
    }

    ASSERT_EQ(a.Nodes.size(), b.Nodes.size()) << context;
    auto findNode = [](const SgGraphDocument& doc, const std::string& id) -> const SgGraphNode* {
        for (const auto& node : doc.Nodes)
        {
            if (node.Id == id)
                return &node;
        }
        return nullptr;
    };
    for (const auto& node : a.Nodes)
    {
        const SgGraphNode* other = findNode(b, node.Id);
        ASSERT_NE(other, nullptr) << context << " node " << node.Id;
        EXPECT_EQ(node.TypeId, other->TypeId) << context << " node " << node.Id;
        EXPECT_FLOAT_EQ(node.PositionX, other->PositionX) << context << " node " << node.Id;
        EXPECT_FLOAT_EQ(node.PositionY, other->PositionY) << context << " node " << node.Id;
        EXPECT_EQ(node.PortDefaults, other->PortDefaults) << context << " node " << node.Id;
    }

    ASSERT_EQ(a.Edges.size(), b.Edges.size()) << context;
    auto edgeKey = [](const SgGraphEdge& e) {
        return e.SourceNodeId + "." + e.SourcePortId + "->" + e.TargetNodeId + "." + e.TargetPortId;
    };
    std::vector<std::string> aEdges, bEdges;
    for (const auto& e : a.Edges)
        aEdges.push_back(edgeKey(e));
    for (const auto& e : b.Edges)
        bEdges.push_back(edgeKey(e));
    std::sort(aEdges.begin(), aEdges.end());
    std::sort(bEdges.begin(), bEdges.end());
    EXPECT_EQ(aEdges, bEdges) << context;
}
} // namespace

TEST(ShaderGraphCompilerTests, EveryTagKindRoundTripsSemantically)
{
    const char* source = R"(// Auto-generated. The @sg-* tag block is authoritative.
// The body below is regenerated by the graph editor on save.
//
// @sg-graph     KitchenSink
// @sg-version   3
// @sg-stage     both
// @sg-lighting  StandardPBR
// @sg-variant   GE_USER_SNOW
// @sg-property  Tint float3 default=1,0,0 hint=color public=true
// @sg-property  Power float default=4.0 range=0.5,8.0
// @sg-texture   Albedo "11112222-3333-4444-5555-666677778888" hint=srgb
// @sg-viewport  panX=120.5 panY=-42.25 zoom=1.5
// @sg-futuretag mode=fancy
// @sg-node      c0  type=ColorConstant pos=(-200,140) r=0.08 g=0.28 b=1.0
// @sg-node      out type=SurfaceOutput pos=(1120,160)
// @sg-edge      c0.value -> out.BaseColor
SurfaceOutput EvaluateSurface(SurfaceInput sIn) { return DefaultSurfaceOutput(); }
)";
    const SgParsedFile parsed = ParseShaderGraphSource(source);
    const SgGraphDocument doc = ParseGraphDocumentFromTags(parsed.TagBlock);

    const std::string serialized = SerializeGraphDocumentTags(doc);
    const SgGraphDocument reparsed = ParseGraphDocumentFromTags(serialized);
    ExpectSameGraphDocument(doc, reparsed, "save/reload");
    EXPECT_NE(serialized.find("// @sg-lighting  StandardPBR"), std::string::npos) << serialized;
    EXPECT_NE(serialized.find("// @sg-futuretag mode=fancy"), std::string::npos) << serialized;

    // The loader must not care about tag-line order: nodes after edges, header
    // tags interleaved with node tags.
    const char* reordered = R"(// @sg-edge      c0.value -> out.BaseColor
// @sg-node      out type=SurfaceOutput pos=(1120,160)
// @sg-viewport  panX=120.5 panY=-42.25 zoom=1.5
// @sg-node      c0  type=ColorConstant pos=(-200,140) r=0.08 g=0.28 b=1.0
// @sg-texture   Albedo "11112222-3333-4444-5555-666677778888" hint=srgb
// @sg-property  Tint float3 default=1,0,0 hint=color public=true
// @sg-property  Power float default=4.0 range=0.5,8.0
// @sg-futuretag mode=fancy
// @sg-variant   GE_USER_SNOW
// @sg-lighting  StandardPBR
// @sg-stage     both
// @sg-version   3
// @sg-graph     KitchenSink
)";
    const SgGraphDocument shuffled =
        ParseGraphDocumentFromTags(ParseShaderGraphSource(reordered).TagBlock);
    ExpectSameGraphDocument(doc, shuffled, "reordered tags");
}

// ---- Port-width adaptation. The topo pre-pass in Compile caches every live
// ---- node's port expressions before edges resolve, so adaptation must apply to
// ---- cached expressions too, and unwired ports need width-matched fallbacks.

namespace {
SgCompileResult CompileTagSource(const char* source)
{
    const auto doc = ParseGraphDocumentFromTags(ParseShaderGraphSource(source).TagBlock);
    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    return SgGraphCompiler::Compile(doc, library);
}
}

TEST(ShaderGraphCompilerTests, BroadcastsScalarNodeOutputOntoVectorPort)
{
    const char* source = R"(// @sg-graph     ScalarOntoVector
// @sg-version   1
// @sg-stage     surface
// @sg-lighting  StandardPBR
// @sg-node      f0  type=FloatConstant  pos=(0,0)   value=0.25
// @sg-node      c0  type=ColorConstant  pos=(0,80)  r=1.0 g=0.5 b=0.25
// @sg-node      m0  type=VectorMultiply pos=(240,0)
// @sg-node      out type=SurfaceOutput  pos=(480,0)
// @sg-edge      f0.value -> m0.a
// @sg-edge      c0.value -> m0.b
// @sg-edge      m0.result -> out.BaseColor
)";
    const auto result = CompileTagSource(source);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    EXPECT_NE(result.Body.find("SG_VectorMultiply(vec3(_f0_result)"), std::string::npos) << result.Body;
}

TEST(ShaderGraphCompilerTests, UnwiredVectorPortFallsBackToWidthMatchedZero)
{
    const char* source = R"(// @sg-graph     UnwiredVector
// @sg-version   1
// @sg-stage     surface
// @sg-lighting  StandardPBR
// @sg-node      c0  type=ColorConstant  pos=(0,0)  r=1.0 g=0.5 b=0.25
// @sg-node      m0  type=VectorMultiply pos=(240,0)
// @sg-node      out type=SurfaceOutput  pos=(480,0)
// @sg-edge      c0.value -> m0.a
// @sg-edge      m0.result -> out.BaseColor
)";
    const auto result = CompileTagSource(source);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    EXPECT_NE(result.Body.find("SG_VectorMultiply(vec3(_c0_result), vec3(0.0))"), std::string::npos)
        << result.Body;
}

TEST(ShaderGraphCompilerTests, UnwiredPortWithNodeDefaultKeepsDeclaredDefault)
{
    // Control: a port default carried on the node tag wins over the zero fallback.
    const char* source = R"(// @sg-graph     PortDefault
// @sg-version   1
// @sg-stage     surface
// @sg-lighting  StandardPBR
// @sg-node      c0  type=ColorConstant  pos=(0,0)  r=1.0 g=0.5 b=0.25
// @sg-node      m0  type=VectorMultiply pos=(240,0)  a=vec3(0.5)
// @sg-node      out type=SurfaceOutput  pos=(480,0)
// @sg-edge      c0.value -> m0.b
// @sg-edge      m0.result -> out.BaseColor
)";
    const auto result = CompileTagSource(source);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    EXPECT_NE(result.Body.find("SG_VectorMultiply(vec3(0.5), "), std::string::npos) << result.Body;
}

TEST(ShaderGraphCompilerTests, SurfaceOutputIsTheOnlySurfaceSinkTypeId)
{
    // One master node: the retired "Output" spelling is no longer aliased onto
    // the surface sink, so a graph that still names it fails loudly.
    EXPECT_EQ(ResolveNodeTypeAlias("Output"), "Output");
    EXPECT_FALSE(IsPseudoNodeType("Output"));
    EXPECT_TRUE(IsPseudoNodeType("SurfaceOutput"));

    SgGraphDocument doc;
    doc.GraphName = "RetiredSink";
    doc.Nodes.push_back({"out", "Output", 0.f, 0.f, {}});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    EXPECT_FALSE(result.Success);
    ASSERT_FALSE(result.Errors.empty());
    EXPECT_NE(result.Errors.front().Message.find("missing SurfaceOutput node"), std::string::npos);
}

TEST(ShaderGraphCompilerTests, DiagnosticsCarryTheOffendingNodeId)
{
    SgGraphDocument doc;
    doc.GraphName = "TaggedDiagnostics";
    doc.Nodes.push_back({"out", "SurfaceOutput", 0.f, 0.f, {}});
    doc.Nodes.push_back({"n_bogus", "NoSuchNodeType", 0.f, 0.f, {}});
    doc.Edges.push_back({"n_bogus", "out", "out", "BaseColor"});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    ASSERT_FALSE(result.Success);
    ASSERT_FALSE(result.Errors.empty());
    EXPECT_NE(result.Errors.front().Message.find("unknown node type"), std::string::npos);
    EXPECT_EQ(result.Errors.front().NodeId, "n_bogus");
}

TEST(ShaderGraphCompilerTests, GraphScopedDiagnosticCarriesNoNodeId)
{
    SgGraphDocument doc;
    doc.GraphName = "NoSink";
    doc.Nodes.push_back({"c0", "ColorConstant", 0.f, 0.f, {}});

    const auto library = SgNodeReflector::BuildIndex(GetEngineGraphNodesRoot(), {});
    const auto result = SgGraphCompiler::Compile(doc, library);
    ASSERT_FALSE(result.Success);
    ASSERT_EQ(result.Errors.size(), 1u);
    EXPECT_NE(result.Errors.front().Message.find("missing SurfaceOutput node"), std::string::npos);
    EXPECT_TRUE(result.Errors.front().NodeId.empty());
}

namespace {

std::string ReadNodeLibrarySource(const char* relativePath)
{
    const std::filesystem::path path = GetEngineGraphNodesRoot() / relativePath;
    std::ifstream in(path);
    std::ostringstream text;
    text << in.rdbuf();
    return text.str();
}

} // namespace

TEST(ShaderGraphCompilerTests, CompareFunctionSelectorsAreDeclaredNamesTheShaderBranchesOn)
{
    /* A node parameter is spliced into the emitted call verbatim, so an enum
       whose values are prose ("greater") compiles to an undefined identifier.
       Every value the editor can store has to be declared in the node source
       AND read by SG_Compare, or the dropdown is decorative at best. */
    const std::string nodeSource = ReadNodeLibrarySource("Utility/Nodes.glsl");
    ASSERT_FALSE(nodeSource.empty());

    for (const char* selector :
         {"SG_COMPARE_GREATER", "SG_COMPARE_LESS", "SG_COMPARE_EQUAL", "SG_COMPARE_NOT_EQUAL",
          "SG_COMPARE_GREATER_EQUAL", "SG_COMPARE_LESS_EQUAL"})
    {
        EXPECT_NE(nodeSource.find(std::string("const float ") + selector + " ="),
                  std::string::npos)
            << selector << " is not declared in Utility/Nodes.glsl";
    }

    // Every selector but the code-0 default has to be branched on by name;
    // the default is the function's fall-through return.
    for (const char* selector :
         {"SG_COMPARE_LESS", "SG_COMPARE_EQUAL", "SG_COMPARE_NOT_EQUAL",
          "SG_COMPARE_GREATER_EQUAL", "SG_COMPARE_LESS_EQUAL"})
    {
        EXPECT_NE(nodeSource.find(std::string("function == ") + selector), std::string::npos)
            << selector << " selects nothing in SG_Compare";
    }
}

TEST(ShaderGraphCompilerTests, CompareNodeEmitsItsSelectorAsTheFunctionArgument)
{
    const char* source = R"(// @sg-graph     CompareSelector
// @sg-version   1
// @sg-stage     surface
// @sg-lighting  StandardPBR
// @sg-node      cmp type=Compare       pos=(0,0)  function=SG_COMPARE_LESS_EQUAL
// @sg-node      out type=SurfaceOutput pos=(240,0)
// @sg-edge      cmp.result -> out.Metallic
)";
    const auto result = CompileTagSource(source);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    EXPECT_NE(result.Body.find("SG_Compare(0.0, 0.0, SG_COMPARE_LESS_EQUAL)"), std::string::npos)
        << result.Body;
}

TEST(ShaderGraphCompilerTests, CompareNodeWithNoSelectorFallsBackToTheDefaultCode)
{
    // No function parameter: the compiler substitutes the width-matched zero,
    // which SG_Compare defines as the same comparison the schema defaults to.
    const char* source = R"(// @sg-graph     CompareDefault
// @sg-version   1
// @sg-stage     surface
// @sg-lighting  StandardPBR
// @sg-node      cmp type=Compare       pos=(0,0)
// @sg-node      out type=SurfaceOutput pos=(240,0)
// @sg-edge      cmp.result -> out.Metallic
)";
    const auto result = CompileTagSource(source);
    ASSERT_TRUE(result.Success) << (result.Errors.empty() ? "" : result.Errors.front().Message);
    EXPECT_NE(result.Body.find("SG_Compare(0.0, 0.0, 0.0)"), std::string::npos) << result.Body;

    const std::string nodeSource = ReadNodeLibrarySource("Utility/Nodes.glsl");
    EXPECT_NE(nodeSource.find("const float SG_COMPARE_GREATER = 0.0;"), std::string::npos);
}

TEST(ShaderGraphCompilerTests, ParsesQuotedPositionalArgumentAsOneToken)
{
    // A quoted positional keeps its quotes so a consumer can tell "Pulse Speed"
    // (a display name) from a bare flag word; spaces inside it do not split it.
    const auto attrs =
        ParseTagAttributes("// @property float pulseSpeed \"Pulse Speed\" default=2.0 range=0,8 hdr");
    EXPECT_EQ(FindTagAttribute(attrs, "arg0").value_or(""), "float");
    EXPECT_EQ(FindTagAttribute(attrs, "arg1").value_or(""), "pulseSpeed");
    EXPECT_EQ(FindTagAttribute(attrs, "arg2").value_or(""), "\"Pulse Speed\"");
    EXPECT_FALSE(FindTagAttribute(attrs, "arg3").has_value());
    EXPECT_EQ(FindTagAttribute(attrs, "default").value_or(""), "2.0");
    EXPECT_EQ(FindTagAttribute(attrs, "range").value_or(""), "0,8 hdr")
        << "a value still runs to the next key=; the property parser peels trailing flags";
}

TEST(ShaderGraphCompilerTests, QuotedValueIsOneSpanWhateverItContains)
{
    // The value scan must not hunt for the next key= inside a quoted value, and
    // a bare '=' never starts a key. The quotes stay on, as with a quoted
    // positional, so a consumer can tell verbatim text from a bare value.
    const auto attrs = ParseTagAttributes(
        "// @property float emissionScale tooltip=\"scene-linear; 1.0 == 203 nits\" range=0,4");
    EXPECT_EQ(FindTagAttribute(attrs, "tooltip").value_or(""), "\"scene-linear; 1.0 == 203 nits\"");
    EXPECT_EQ(FindTagAttribute(attrs, "range").value_or(""), "0,4");
    EXPECT_FALSE(FindTagAttribute(attrs, "=").has_value());
}
