# Read the small source manifest shared by the desktop target and SDK exporter.
function(ge_read_desktop_player_sources player_root output)
    set(manifest "${player_root}/DesktopSources.txt")
    if(NOT EXISTS "${manifest}")
        message(FATAL_ERROR "Desktop Player source manifest not found: ${manifest}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    file(STRINGS "${manifest}" lines)
    set(sources)
    foreach(line IN LISTS lines)
        string(STRIP "${line}" source)
        if(source STREQUAL "" OR source MATCHES "^#")
            continue()
        endif()
        if(IS_ABSOLUTE "${source}" OR source MATCHES "[:;\\\\]" OR
           source MATCHES "(^|/)\\.\\.?(/|$)" OR NOT source MATCHES "\\.(cpp|h)$")
            message(FATAL_ERROR "Invalid desktop Player source '${source}' in ${manifest}")
        endif()
        if(NOT EXISTS "${player_root}/Source/${source}" OR IS_DIRECTORY "${player_root}/Source/${source}")
            message(FATAL_ERROR "Desktop Player template source not found: ${player_root}/Source/${source}")
        endif()
        list(APPEND sources "${source}")
    endforeach()
    list(REMOVE_DUPLICATES sources)
    if(NOT sources)
        message(FATAL_ERROR "Empty desktop Player source list: ${manifest}")
    endif()
    set(${output} "${sources}" PARENT_SCOPE)
endfunction()
